import Solutions.PalomarCorpus.E249_14

#print axioms PalomarCorpus.E249.PaperStatementsAJ.dyadicMixedGuard_iff_twoBitBand
#print axioms PalomarCorpus.E249.PaperStatementsAJ.dyadicScale_unique_in_open_interval
#print axioms PalomarCorpus.E249.PaperStatementsAJ.rough_integer_prime_count_and_totient_bound
#print axioms PalomarCorpus.E249.PaperStatementsAK.totient_mul_eq_totient_mul_gcd_div_totient_gcd
#print axioms PalomarCorpus.E249.PaperStatementsAT.actualLcmTailOrbit_global_to_local
#print axioms PalomarCorpus.E249.PaperStatementsAT.actualLcmTailOrbit_pos
#print axioms PalomarCorpus.E249.PaperStatementsAT.actualLcm_integral_forces_topEdgeResidue_paper
#print axioms PalomarCorpus.E249.PaperStatementsAT.actualLcm_tailDiff_shift_pos_paper
#print axioms PalomarCorpus.E249.PaperStatementsAT.exists_certifiedKill_iff_twoBitResidueTest
#print axioms PalomarCorpus.E249.PaperStatementsAU.lcmRayArithmeticLetter_eq_totient_difference
#print axioms PalomarCorpus.E249.PaperStatementsAU.lcmRay_divisor_clean_formula
#print axioms PalomarCorpus.E249.PaperStatementsAU.lcmRay_divisor_denominators_pos
#print axioms PalomarCorpus.E249.PaperStatementsAU.lcmRay_divisor_gcd_example
#print axioms PalomarCorpus.E249.PaperStatementsAU.lcmRay_divisor_product_formula
#print axioms PalomarCorpus.E249.PaperStatementsAU.lcmRay_nondivisor_literal
#print axioms PalomarCorpus.E249.PaperStatementsAU.penultimate_shortWindow_difference_eq_half
#print axioms PalomarCorpus.E249.PaperStatementsAU.shortWindow_totient_difference_pos
#print axioms PalomarCorpus.E249.PaperStatementsAU.tendsto_actualLcmRawErrorRadius_atTop_nhds_zero
#print axioms PalomarCorpus.E249.PaperStatementsAU.weighted_shortWindow_band_iff_certifiedKill
#print axioms PalomarCorpus.E249.PaperStatementsAU.weighted_shortWindow_sum_eq_windowDiscrepancy
#print axioms PalomarCorpus.E249.PaperStatementsAX.abs_actualLcmTailOrbit_sub_rawApprox_lt_explicit
