import Solutions.ExternalVerification249TotientRigidity

#print axioms Erdos249257.ExternalVerification249TotientRigidity.one_prime_law_and_little_o_forces_totient
#print axioms Erdos249257.ExternalVerification249TotientRigidity.totient_prime_mul_of_dvd
#print axioms Erdos249257.ExternalVerification249TotientRigidity.totient_prime_mul_of_not_dvd
#print axioms Erdos249257.ExternalVerification249TotientRigidity.even_law_and_eventual_congruence_forces_totient
#print axioms Erdos249257.ExternalVerification249TotientRigidity.totient_two_mul_of_odd
#print axioms Erdos249257.ExternalVerification249TotientRigidity.totient_two_mul_of_even
