import Solutions.ExternalVerification251PaperStatementsF

#print axioms Erdos249257.ExternalVerification251PaperStatementsF.denominator_floor_decimal
#print axioms Erdos249257.ExternalVerification251PaperStatementsF.finite_perturbation_stability
