import Solutions.PalomarCorpus.E257_17

#print axioms PalomarCorpus.E257.PaperStatementsAD.channelProduct_coprime_mobiusNumerator_of_one_le
#print axioms PalomarCorpus.E257.PaperStatementsAD.lcmHeight_scaledMobiusShadow_den_lower_bound
#print axioms PalomarCorpus.E257.PaperStatementsAD.paperA_eq_mobiusNumerator
#print axioms PalomarCorpus.E257.PaperStatementsAD.paperB_eq_baseMobiusShadow
#print axioms PalomarCorpus.E257.PaperStatementsAD.paperB_eq_divInt_paperA
#print axioms PalomarCorpus.E257.PaperStatementsAD.paper_channel_factor_gcd_eq_one
#print axioms PalomarCorpus.E257.PaperStatementsAD.paper_channel_factors_pairwise_coprime
#print axioms PalomarCorpus.E257.PaperStatementsAD.paper_mersenne_channel_survival
#print axioms PalomarCorpus.E257.PaperStatementsAD.paper_mersenne_channel_survival_of_coprime_scale
#print axioms PalomarCorpus.E257.PaperStatementsAD.upperHalfChannel_survivorProduct_dvd_den_of_one_le
#print axioms PalomarCorpus.E257.PaperStatementsAD.upperHalfMersenneProduct_lower_bound
#print axioms PalomarCorpus.E257.PaperStatementsAG.erdosSupportSeries_multiples_eq_pow_base_full_support
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_erdosSum_two_pow_support
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_erdosSupportSeries_multiples
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_erdosSupportSeries_residueClass
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_intWeightedErdosSeries_periodic_of_coeff_nonneg_of_frequently_ne_zero
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_intWeightedErdosSeries_periodic_of_coeff_nonpos_of_frequently_ne_zero
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_or_bpow_mul_eq_intCast_intWeightedErdosSeries_periodic
