import Solutions.PalomarCorpus.E249_34

#print axioms PalomarCorpus.E249.RationalObservableClassification.rational_zmod_observable_iff
#print axioms PalomarCorpus.E249.RationalObservableClassification.residue_series_sharp_range
#print axioms PalomarCorpus.E249.RationalObservableClassification.zmod_observable_value
#print axioms PalomarCorpus.E249.ResidueClassTotientSeries.fixed_resolution_observable_irrational
#print axioms PalomarCorpus.E249.ResidueClassTotientSeries.irrational_dyadicValue_of_pulses
#print axioms PalomarCorpus.E249.ResidueClassTotientSeries.irrational_totientObservable
#print axioms PalomarCorpus.E249.ResidueClassTotientSeries.isolated_pulse_separation
#print axioms PalomarCorpus.E249.ResidueClassTotientSeries.residue_series_irrational
#print axioms PalomarCorpus.E249.ResidueClassTotientSeries.two_sided_prime_isolation
#print axioms PalomarCorpus.E249.TermwiseDyadicVacuous.termwise_dyadic_window_vacuous
#print axioms PalomarCorpus.E249.TotientAffineModeEscape.not_eventuallyAffine_pureDyadicEndpointError
#print axioms PalomarCorpus.E249.TotientRigidity.even_law_and_eventual_congruence_forces_totient
#print axioms PalomarCorpus.E249.TotientRigidity.one_prime_law_and_little_o_forces_totient
#print axioms PalomarCorpus.E249.TotientRigidity.totient_prime_mul_of_dvd
#print axioms PalomarCorpus.E249.TotientRigidity.totient_prime_mul_of_not_dvd
#print axioms PalomarCorpus.E249.TotientRigidity.totient_two_mul_of_even
#print axioms PalomarCorpus.E249.TotientRigidity.totient_two_mul_of_odd
