import Solutions.ExternalVerification257PaperStructuresBS

#print axioms Erdos249257.ExternalVerification257PaperStructuresBS.exists_support_paperCoverCost_ge
#print axioms Erdos249257.ExternalVerification257PaperStructuresBS.no_absolute_paperCoverCost_kappaOne_constant
#print axioms Erdos249257.ExternalVerification257PaperStructuresBS.sup_condExceedProb_le_paperCoverCost
