import Solutions.PalomarCorpus.E1041_02

#print axioms PalomarCorpus.E1041.PaperStatementsAC.circle_slice_packing
#print axioms PalomarCorpus.E1041.PaperStatementsAC.circle_slice_packing_abstract
#print axioms PalomarCorpus.E1041.PaperStatementsAC.dual_arity_floor_abstract
#print axioms PalomarCorpus.E1041.PaperStatementsC.cosh_dist_polar
#print axioms PalomarCorpus.E1041.PaperStatementsC.dist_polar_I
#print axioms PalomarCorpus.E1041.PaperStatementsC.exists_polar
#print axioms PalomarCorpus.E1041.PaperStatementsC.polar_zero_zero
#print axioms PalomarCorpus.E1041.PaperStatementsZ.circle_slice_packing
#print axioms PalomarCorpus.E1041.PaperStatementsZA.scaledLowCriticalFiveHalves_of_lowCritical
#print axioms PalomarCorpus.E1041.PaperStatementsZA.scaledLowCritical_of_lowCritical
