import Solutions.ExternalVerification249PaperStatementsAN

#print axioms Erdos249257.ExternalVerification249PaperStatementsAN.cos_pi_div_eight_gt
#print axioms Erdos249257.ExternalVerification249PaperStatementsAN.irrational_lacBeta
#print axioms Erdos249257.ExternalVerification249PaperStatementsAN.lacBeta_eq_factorial_series
#print axioms Erdos249257.ExternalVerification249PaperStatementsAN.lacCoef_bounds
#print axioms Erdos249257.ExternalVerification249PaperStatementsAN.lacunary_block_cos_gap
#print axioms Erdos249257.ExternalVerification249PaperStatementsAN.lacunary_block_norm_fails
