import Solutions.ExternalVerification269PaperStatementsG

#print axioms Erdos249257.ExternalVerification269PaperStatementsG.conditional_denominator_reduction_real_bound
#print axioms Erdos249257.ExternalVerification269PaperStatementsG.exact_denominators_and_minimal_clearing
#print axioms Erdos249257.ExternalVerification269PaperStatementsG.long_no_bounded_length
#print axioms Erdos249257.ExternalVerification269PaperStatementsG.short_window_equivalence
