import Solutions.PalomarCorpus.E257_37

#print axioms PalomarCorpus.E257.PaperStructuresCG.exists_seamWord_minimal_above
#print axioms PalomarCorpus.E257.PaperStructuresCG.integerGreedyBits_length
#print axioms PalomarCorpus.E257.PaperStructuresCG.paper_theoremA_right_branch_forces_small_deviation
#print axioms PalomarCorpus.E257.PaperStructuresCG.paper_two_sided_dyadic_bound
#print axioms PalomarCorpus.E257.PaperStructuresCG.paper_universal_band_condition_unfolded
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamAboveWord_minimal
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamAboveWord_strict
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamAdjacentCut_below_admissible
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamAdjacentCut_below_maximal
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamPerturbedFamily_gap_pos
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamPerturbedFamily_oldSum_injective
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamPerturbedFamily_separated
#print axioms PalomarCorpus.E257.PaperStructuresCG.seamWeights_length_eq
#print axioms PalomarCorpus.E257.PaperStructuresCG.wordPulse_le
