import Mathlib
import ErdosProblems.Erdos243.PaperCompleteR20.CubicModularSquareSpecialisation

/-!
# Erdős 243: the square-specialisation lemma from the Chebotarev density theorem

Paper form of `long243:res:squarespec` of `paper/reasoning-parts/erdos243/core.tex`
(lemma at line 303).

The paper's proof of that lemma uses one classical input that is absent from the
pinned Mathlib: the Chebotarev density theorem, and of it only the *qualitative*
statement that for a finite Galois extension `L/ℚ` and `σ ∈ Gal(L/ℚ)` there are
infinitely many rational primes with a prime of `L` above them whose Frobenius
element is exactly `σ`.  That input is stated here as `ChebotarevFrobenius`, in
the reduction form in which the paper actually uses it, and everything else is
proved.

`ChebotarevFrobenius` is **not** a restatement of the lemma: it mentions no
polynomial, no root modulo a prime and no square.  It says only that a prescribed
Galois element is realised as a Frobenius element at arbitrarily large primes.

What is proved here is the whole residue-field half of the paper's proof
(`frobenius_descent`): given a finite Galois extension `Lg / ℚ`, an element `σ`
of its Galois group fixing `α` and negating a square root `β` of `H (α)`, and
the Chebotarev input, the paper's modular hypothesis is contradicted.  The
remaining half is the purely Galois-theoretic construction of that `Lg` and `σ`
from "`H (α)` is not a square in `ℚ(α)`"; it is not done here.
-/

noncomputable section

namespace ErdosProblems.Erdos243.PaperCompleteR21

/-! ### The external input -/

/-- The data attached to one prime `𝔓` of a number field `L` whose Frobenius
element is `σ`: the residue field at `𝔓` (of characteristic `ℓ`), the reduction
homomorphism on a subring `A` of `L`, and the defining property of the Frobenius
element, `σ y ≡ y ^ ℓ` modulo `𝔓`. -/
structure FrobeniusReduction (L : Type) [Field L] [Algebra ℚ L]
    (σ : L ≃ₐ[ℚ] L) (A : Subalgebra ℤ L) (ℓ : ℕ) where
  /-- the residue field at the prime -/
  residue : Type
  [residueField : Field residue]
  [residueChar : CharP residue ℓ]
  /-- reduction modulo the prime, on the subring `A` -/
  red : A →+* residue
  /-- the Frobenius element at the prime is `σ` -/
  frobenius : ∀ (y : L) (hy : y ∈ A) (hy' : σ y ∈ A),
      red ⟨σ y, hy'⟩ = red ⟨y, hy⟩ ^ ℓ

attribute [instance] FrobeniusReduction.residueField FrobeniusReduction.residueChar

/-- **The Chebotarev density theorem**, in the qualitative Frobenius form used in
the paper's proof of the square-specialisation lemma (`core.tex`, lines 310-328,
citing Stevenhagen–Lenstra §3 p. 15: "only the infinitude is used").

For a finite Galois extension `L/ℚ`, an element `σ` of its Galois group, the
subring `ℤ[S]` of `L` generated by a finite set `S`, a nonzero `x ∈ ℤ[S]` and any
bound `N`, some prime `ℓ > N` carries a prime of `L` above it with Frobenius
element `σ`; reduction modulo that prime gives a ring homomorphism on `ℤ[S]`
which does not kill `x` and which turns `σ` into the `ℓ`-power map.

This is the only unproved input below. -/
def ChebotarevFrobenius : Prop :=
  ∀ (L : Type) [Field L] [Algebra ℚ L] [FiniteDimensional ℚ L] [IsGalois ℚ L]
    (σ : L ≃ₐ[ℚ] L) (S : Finset L) (x : L)
    (hx : x ∈ Algebra.adjoin ℤ (S : Set L)) (_hx0 : x ≠ 0) (N : ℕ),
    ∃ ℓ : ℕ, ℓ.Prime ∧ N < ℓ ∧
      ∃ red : FrobeniusReduction L σ (Algebra.adjoin ℤ (S : Set L)) ℓ,
        red.red ⟨x, hx⟩ ≠ 0

/-! ### Elementary bookkeeping lemmas -/

/-- In a field of prime characteristic `ℓ`, the solutions of `z ^ ℓ = z` are
exactly the elements of the prime field. -/
theorem mem_range_zmod_castHom_of_pow_eq
    {ℓ : ℕ} (hℓ : ℓ.Prime) (F : Type*) [Field F] [CharP F ℓ]
    (z : F) (hz : z ^ ℓ = z) :
    ∃ r : ZMod ℓ, ZMod.castHom (dvd_refl ℓ) F r = z := by
  classical
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  set ι : ZMod ℓ →+* F := ZMod.castHom (dvd_refl ℓ) F with hι
  have hinj : Function.Injective ι := ι.injective
  set q : Polynomial F := Polynomial.X ^ ℓ - Polynomial.X with hq
  have hdeglt : (Polynomial.X : Polynomial F).natDegree <
      ((Polynomial.X : Polynomial F) ^ ℓ).natDegree := by
    rw [Polynomial.natDegree_X_pow, Polynomial.natDegree_X]
    exact hℓ.one_lt
  have hdeg : q.natDegree = ℓ := by
    rw [hq, Polynomial.natDegree_sub_eq_left_of_natDegree_lt hdeglt,
      Polynomial.natDegree_X_pow]
  have hq0 : q ≠ 0 := by
    intro h
    rw [h, Polynomial.natDegree_zero] at hdeg
    exact hℓ.ne_zero hdeg.symm
  have hroot : ∀ y : F, y ^ ℓ = y → y ∈ q.roots := by
    intro y hy
    rw [Polynomial.mem_roots hq0]
    simp [Polynomial.IsRoot, hq, hy]
  set T : Finset F := Finset.image ι Finset.univ with hT
  have hTcard : T.card = ℓ := by
    rw [hT, Finset.card_image_of_injective _ hinj, Finset.card_univ, ZMod.card]
  have hTsub : T ⊆ q.roots.toFinset := by
    intro y hy
    rw [hT, Finset.mem_image] at hy
    obtain ⟨k, -, rfl⟩ := hy
    rw [Multiset.mem_toFinset]
    exact hroot _ (by rw [← map_pow, ZMod.pow_card])
  have hcard : q.roots.toFinset.card ≤ ℓ := by
    refine le_trans (Multiset.toFinset_card_le _) ?_
    rw [← hdeg]
    exact Polynomial.card_roots' q
  have hTeq : T = q.roots.toFinset :=
    Finset.eq_of_subset_of_card_le hTsub (by rw [hTcard]; exact hcard)
  have hzmem : z ∈ q.roots.toFinset := by
    rw [Multiset.mem_toFinset]
    exact hroot z hz
  rw [← hTeq, hT, Finset.mem_image] at hzmem
  obtain ⟨k, -, hk⟩ := hzmem
  exact ⟨k, hk⟩

/-- Evaluating an integer polynomial commutes with any ring homomorphism. -/
theorem eval₂_int_map {R S : Type*} [CommRing R] [CommRing S]
    (φ : R →+* S) (x : R) (P : Polynomial ℤ) :
    φ (Polynomial.eval₂ (Int.castRingHom R) x P) =
      Polynomial.eval₂ (Int.castRingHom S) (φ x) P := by
  rw [Polynomial.hom_eval₂]
  congr 1
  exact RingHom.ext_int _ _

/-- `aeval` over `ℤ` is `eval₂` along the canonical map. -/
theorem aeval_int_eq {A : Type*} [CommRing A] (x : A) (P : Polynomial ℤ) :
    Polynomial.aeval x P = Polynomial.eval₂ (Int.castRingHom A) x P := by
  rw [Polynomial.aeval_def]
  congr 1
  try exact RingHom.ext_int _ _

/-- Evaluating the rational model of an integer polynomial. -/
theorem aeval_map_int {A : Type*} [CommRing A] [Algebra ℚ A] (x : A)
    (P : Polynomial ℤ) :
    Polynomial.aeval x (P.map (Int.castRingHom ℚ)) =
      Polynomial.eval₂ (Int.castRingHom A) x P := by
  rw [Polynomial.aeval_def, Polynomial.eval₂_map]
  congr 1
  exact RingHom.ext_int _ _

/-- `eval₂` inside a subalgebra agrees with `eval₂` in the ambient ring. -/
theorem coe_eval₂_subalgebra {R : Type*} [CommRing R] (A : Subalgebra ℤ R) (x : A)
    (P : Polynomial ℤ) :
    ((Polynomial.eval₂ (Int.castRingHom A) x P : A) : R)
      = Polynomial.eval₂ (Int.castRingHom R) (x : R) P := by
  exact eval₂_int_map (A.val.toRingHom) x P

/-! ### The descent at a Frobenius prime -/

set_option maxHeartbeats 1000000 in
/-- The residue-field descent, once `σ` fixes `α` and negates a square root `β`
of `H (α)`.  Chebotarev supplies a prime at which `σ` is the Frobenius; there
`α` reduces into the prime field, so it is a root of the reduction of `f`, while
`H (α)` reduces to a nonsquare, contradicting the hypothesis. -/
theorem frobenius_descent (hCheb : ChebotarevFrobenius)
    (Lg : Type) [Field Lg] [Algebra ℚ Lg] [FiniteDimensional ℚ Lg] [IsGalois ℚ Lg]
    (σ : Lg ≃ₐ[ℚ] Lg) (αL βL : Lg)
    (hσα : σ αL = αL) (hσβ : σ βL = -βL) (hβ0 : βL ≠ 0)
    (f H : Polynomial ℚ)
    (hfαL : Polynomial.aeval αL f = 0) (hHαL : Polynomial.aeval αL H = βL ^ 2)
    (d : ℕ) (_hd : 0 < d) (G J : Polynomial ℤ)
    (hG : G.map (Int.castRingHom ℚ) = Polynomial.C (d : ℚ) * f)
    (hJ : J.map (Int.castRingHom ℚ) = Polynomial.C ((d : ℚ) ^ 2) * H)
    (hmod : ∃ N : ℕ, ∀ ℓ : ℕ, ℓ.Prime → N < ℓ → ∀ r : ZMod ℓ,
        (G.map (Int.castRingHom (ZMod ℓ))).eval r = 0 →
        (J.map (Int.castRingHom (ZMod ℓ))).eval r ≠ 0 ∧
          IsSquare ((J.map (Int.castRingHom (ZMod ℓ))).eval r)) :
    False := by
  classical
  obtain ⟨N₀, hN₀⟩ := hmod
  have hαA : αL ∈ Algebra.adjoin ℤ ((({αL, βL} : Finset Lg) : Set Lg)) :=
    Algebra.subset_adjoin (by simp)
  have hβA : βL ∈ Algebra.adjoin ℤ ((({αL, βL} : Finset Lg) : Set Lg)) :=
    Algebra.subset_adjoin (by simp)
  obtain ⟨ℓ, hℓp, hℓN, red, hredβ⟩ :=
    hCheb Lg σ ({αL, βL} : Finset Lg) βL hβA hβ0 (max N₀ 2)
  haveI : Fact ℓ.Prime := ⟨hℓp⟩
  have hℓN₀ : N₀ < ℓ := lt_of_le_of_lt (le_max_left _ _) hℓN
  have hℓ2 : 2 < ℓ := lt_of_le_of_lt (le_max_right _ _) hℓN
  set A : Subalgebra ℤ Lg := Algebra.adjoin ℤ ((({αL, βL} : Finset Lg) : Set Lg)) with hA
  set aA : A := ⟨αL, hαA⟩ with haA
  set bA : A := ⟨βL, hβA⟩ with hbA
  set b : red.residue := red.red bA with hbdef
  set z : red.residue := red.red aA with hzdef
  -- the two Frobenius identities
  have hzpow : z ^ ℓ = z := by
    have hmem : σ αL ∈ A := by rw [hσα]; exact hαA
    have h := red.frobenius αL hαA hmem
    rw [show (⟨σ αL, hmem⟩ : A) = aA from Subtype.ext hσα] at h
    rw [hzdef]
    exact h.symm
  have hbpow : b ^ ℓ = -b := by
    have hmem : σ βL ∈ A := by rw [hσβ]; exact neg_mem hβA
    have h := red.frobenius βL hβA hmem
    rw [show (⟨σ βL, hmem⟩ : A) = -bA from Subtype.ext (by simpa using hσβ)] at h
    rw [map_neg] at h
    rw [hbdef]
    exact h.symm
  -- the reduction of `α` lies in the prime field
  obtain ⟨r, hr⟩ := mem_range_zmod_castHom_of_pow_eq hℓp red.residue z hzpow
  set ι : ZMod ℓ →+* red.residue := ZMod.castHom (dvd_refl ℓ) red.residue with hιdef
  have hιinj : Function.Injective ι := ι.injective
  -- transport of the two integral models
  have hLg0 : Polynomial.eval₂ (Int.castRingHom Lg) αL G = 0 := by
    rw [← aeval_map_int αL G, hG, map_mul, hfαL, mul_zero]
  have hLgJ : Polynomial.eval₂ (Int.castRingHom Lg) αL J = ((d : Lg) * βL) ^ 2 := by
    rw [← aeval_map_int αL J, hJ, map_mul, Polynomial.aeval_C, hHαL, map_pow, map_natCast]
    ring
  have haAv : ((aA : Lg)) = αL := rfl
  have hA1 : Polynomial.eval₂ (Int.castRingHom A) aA G = 0 := by
    apply Subtype.ext
    rw [coe_eval₂_subalgebra, haAv, hLg0]
    simp
  have hA2 : Polynomial.eval₂ (Int.castRingHom A) aA J = ((d : A) * bA) ^ 2 := by
    apply Subtype.ext
    rw [coe_eval₂_subalgebra, haAv, hLgJ]
    push_cast
    rfl
  set w : red.residue := (d : red.residue) * b with hwdef
  have hGred : Polynomial.eval₂ (Int.castRingHom red.residue) z G = 0 := by
    rw [hzdef, ← eval₂_int_map red.red aA G, hA1, map_zero]
  have hJred : Polynomial.eval₂ (Int.castRingHom red.residue) z J = w ^ 2 := by
    rw [hzdef, ← eval₂_int_map red.red aA J, hA2, hwdef, hbdef]
    simp only [map_pow, map_mul, map_natCast]
  have hGr : (G.map (Int.castRingHom (ZMod ℓ))).eval r = 0 := by
    have h : ι (Polynomial.eval₂ (Int.castRingHom (ZMod ℓ)) r G) = 0 := by
      rw [eval₂_int_map ι r G, hr]
      exact hGred
    rw [Polynomial.eval_map]
    exact (map_eq_zero_iff ι hιinj).mp h
  have hJr : ι ((J.map (Int.castRingHom (ZMod ℓ))).eval r) = w ^ 2 := by
    rw [Polynomial.eval_map, eval₂_int_map ι r J, hr]
    exact hJred
  obtain ⟨hJne, hJsq⟩ := hN₀ ℓ hℓp hℓN₀ r hGr
  have hw0 : w ≠ 0 := by
    intro h
    apply hJne
    apply (map_eq_zero_iff ι hιinj).mp
    rw [hJr, h]
    simp
  obtain ⟨s, hs⟩ := hJsq
  have hsq2 : w ^ 2 = (ι s) ^ 2 := by
    rw [← hJr, hs, map_mul]
    ring
  have hwmem : ∃ t : ZMod ℓ, ι t = w := by
    have hfac : (w - ι s) * (w + ι s) = 0 := by linear_combination hsq2
    rcases mul_eq_zero.mp hfac with h | h
    · exact ⟨s, (sub_eq_zero.mp h).symm⟩
    · exact ⟨-s, by rw [map_neg]; linear_combination -h⟩
  obtain ⟨t, ht⟩ := hwmem
  have hwpow : w ^ ℓ = w := by
    rw [← ht, ← map_pow, ZMod.pow_card]
  have hdpow : (d : red.residue) ^ ℓ = (d : red.residue) := by
    have h : ι ((d : ZMod ℓ) ^ ℓ) = ι ((d : ZMod ℓ)) := by rw [ZMod.pow_card]
    rw [map_pow, map_natCast] at h
    exact h
  have hwneg : w ^ ℓ = -w := by
    rw [hwdef, mul_pow, hbpow, hdpow]
    ring
  have h2ne : (2 : red.residue) ≠ 0 := by
    have h : ((2 : ℕ) : red.residue) ≠ 0 := by
      rw [Ne, CharP.cast_eq_zero_iff red.residue ℓ 2]
      intro hdvd
      have := Nat.le_of_dvd (by norm_num) hdvd
      omega
    simpa using h
  have h2w : (2 : red.residue) * w = 0 := by
    have heq : w = -w := hwpow.symm.trans hwneg
    linear_combination heq
  rcases mul_eq_zero.mp h2w with h | h
  · exact h2ne h
  · exact hw0 h

#print axioms ErdosProblems.Erdos243.PaperCompleteR21.mem_range_zmod_castHom_of_pow_eq
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.frobenius_descent

end ErdosProblems.Erdos243.PaperCompleteR21
