import Mathlib
import ErdosProblems.Erdos243.PaperCompleteR21.ChebotarevSquareSpecialisation
import ErdosProblems.Erdos243.PaperCompleteR21.CubicRateExclusionChain

/-!
# Erdős 243: the Galois half of the square-specialisation lemma

`ChebotarevSquareSpecialisation.lean` states the external input `ChebotarevFrobenius`
and proves the residue-field half `frobenius_descent` of the proof of
`long243:res:squarespec` (`paper/reasoning-parts/erdos243/core.tex`, lemma at line 303).
The missing half was the purely Galois-theoretic construction of `core.tex:311-314`:
from "`H (α)` is not a square in `ℚ(α)`", produce a finite Galois `L / ℚ` containing
`ℚ(α)(β)` and `σ ∈ Gal(L/ℚ)` with `σ α = α` and `σ β = -β`.  That half is done here,
and `squareSpecialisation_of_chebotarev` assembles the paper's lemma from
`ChebotarevFrobenius` alone.

The construction avoids all quadratic-irreducibility and minimal-polynomial
bookkeeping over `ℚ(α)`.  Two observations do the work.

* The conclusion of the lemma is field-independent: `H (α)` is a square in `ℚ(α)`
  exactly when `f ∣ B ^ 2 - H` for some `B ∈ ℚ[X]`, because `ℚ(α)` is the range of
  `Polynomial.aeval α` and the kernel of that map is generated by `f`.  So the whole
  statement reduces to a statement about polynomials over `ℚ`, proved once inside an
  algebraic closure and then transported to any field `L₀` carrying a root of `f`.

* Inside a finite Galois `Lg / ℚ` holding a root `aL` of `f` and a square root `bL`
  of `H (aL)`, every `σ` fixing `aL` sends `bL` to `±bL`.  If none of them sends it to
  `-bL` then all of them fix it, so `bL` lies in the fixed field of the subgroup fixing
  `ℚ(aL)`, which is `ℚ(aL)` by the Galois correspondence.  Only the easy direction of
  the correspondence is needed, and no minimal polynomial over `ℚ(aL)` is ever computed.

The five #243 cubic rows stay conditional on Chebotarev: `covered_modulo_external`,
never `covered`.  What changes is that the reduction is now complete — the only
unproved input is the one faithfully stated classical theorem.
-/

noncomputable section

namespace ErdosProblems.Erdos243.PaperCompleteR21

open IntermediateField
open ErdosProblems.Erdos243.PaperCompleteR7
open ErdosProblems.Erdos243.PaperCompleteR9
open ErdosProblems.Erdos243.PaperCompleteR11
open ErdosProblems.Erdos243.PaperCompleteR20

/- Every field below has characteristic zero, so `DivisionRing.toRatAlgebra` competes
with the canonical `ℚ`-algebra structure on `AlgebraicClosure ℚ` and on the intermediate
fields, and instance search picks the generic one.  `Algebra.IsAlgebraic ℚ
(AlgebraicClosure ℚ)`, `Normal ℚ (AlgebraicClosure ℚ)` and
`AlgHomClass (↥E →ₐ[ℚ] Ω) ℚ ↥E Ω` then all fail to synthesise: this is the instance
diamond that blocked the previous attempt at this construction.  The two `ℚ`-algebra
structures are equal (`algebra_rat_subsingleton`), so demoting the generic one
file-locally changes nothing mathematically and removes the diamond outright.  With the
demotion in force, `Algebra ℚ (AlgebraicClosure ℚ)` synthesises to
`AlgebraicClosure.instAlgebra ℚ`, which is what Mathlib's `IsAlgClosure` instances are
stated about. -/
attribute [local instance 1] DivisionRing.toRatAlgebra

/-! ### Two bookkeeping lemmas -/

/-- If `f` is irreducible with root `x` and `p` also vanishes at `x`, then `f ∣ p`.
(The minimal polynomial of `x` is `f` up to the unit `C f.leadingCoeff⁻¹`.) -/
theorem dvd_of_aeval_eq_zero {L : Type*} [Field L] [Algebra ℚ L] {x : L}
    {f p : Polynomial ℚ} (hf : Irreducible f) (hx : Polynomial.aeval x f = 0)
    (hp : Polynomial.aeval x p = 0) : f ∣ p := by
  obtain ⟨q, hq⟩ := minpoly.dvd ℚ x hp
  refine ⟨Polynomial.C f.leadingCoeff⁻¹ * q, ?_⟩
  rw [hq, ← minpoly.eq_of_irreducible hf hx]
  ring

/-- Evaluating a rational polynomial in an intermediate field commutes with the
inclusion into the ambient field. -/
theorem coe_aeval_intermediateField {Ω : Type*} [Field Ω] [Algebra ℚ Ω]
    (E : IntermediateField ℚ Ω) (x : E) (P : Polynomial ℚ) :
    ((Polynomial.aeval x P : E) : Ω) = Polynomial.aeval (x : Ω) P := by
  have hcomp : (E.val.toRingHom).comp (algebraMap ℚ E) = algebraMap ℚ Ω :=
    RingHom.ext_rat _ _
  have h : E.val.toRingHom (Polynomial.eval₂ (algebraMap ℚ E) x P)
      = Polynomial.eval₂ ((E.val.toRingHom).comp (algebraMap ℚ E)) (E.val.toRingHom x) P :=
    Polynomial.hom_eval₂ ..
  rw [hcomp] at h
  exact h

/-! ### The sign flip inside a finite Galois extension -/

/-- **The Galois sign flip** (`core.tex:311-314`).  Let `Lg / ℚ` be finite Galois,
`aL ∈ Lg` a root of the irreducible `f`, and `bL ∈ Lg` a square root of `H (aL)`.
Then either some `σ ∈ Gal(Lg/ℚ)` fixes `aL` and negates `bL`, or `H` is a square
modulo `f`, i.e. `H (α)` is a square in `ℚ(α)` for every root `α` of `f`.

Only the easy inclusion of the Galois correspondence is used: if no `σ` fixing `aL`
negates `bL`, then every element of the subgroup fixing `ℚ⟮aL⟯` fixes `bL`, so
`bL ∈ fixedField (fixingSubgroup ℚ⟮aL⟯) = ℚ⟮aL⟯`. -/
theorem exists_sign_flip_or_sq_sub_dvd (Lg : Type) [Field Lg] [Algebra ℚ Lg]
    [FiniteDimensional ℚ Lg] [IsGalois ℚ Lg] (aL bL : Lg) (f H : Polynomial ℚ)
    (hf : Irreducible f) (hfL : Polynomial.aeval aL f = 0)
    (hHL : Polynomial.aeval aL H = bL ^ 2) :
    (∃ σ : Lg ≃ₐ[ℚ] Lg, σ aL = aL ∧ σ bL = -bL) ∨
      ∃ B : Polynomial ℚ, f ∣ B ^ 2 - H := by
  classical
  by_cases hex : ∃ σ : Lg ≃ₐ[ℚ] Lg, σ aL = aL ∧ σ bL = -bL
  · exact Or.inl hex
  refine Or.inr ?_
  push_neg at hex
  -- every Galois element fixing `aL` fixes `bL`
  have key : ∀ σ : Lg ≃ₐ[ℚ] Lg, σ aL = aL → σ bL = bL := by
    intro σ hσ
    have h1 : Polynomial.aeval (σ aL) H = σ (Polynomial.aeval aL H) :=
      Polynomial.aeval_algHom_apply σ aL H
    rw [hσ, hHL, map_pow] at h1
    have hfac : (σ bL - bL) * (σ bL + bL) = 0 := by linear_combination -h1
    rcases mul_eq_zero.mp hfac with h | h
    · exact sub_eq_zero.mp h
    · exact absurd (eq_neg_of_add_eq_zero_left h) (hex σ hσ)
  -- hence `bL` is in the fixed field of the subgroup fixing `ℚ⟮aL⟯`
  have hbmem : bL ∈ IntermediateField.fixedField
      (IntermediateField.fixingSubgroup (ℚ⟮aL⟯ : IntermediateField ℚ Lg)) := by
    simp only [IntermediateField.mem_fixedField_iff]
    intro σ hσ
    simp only [IntermediateField.mem_fixingSubgroup_iff] at hσ
    exact key σ (hσ aL (IntermediateField.mem_adjoin_simple_self ℚ aL))
  rw [IsGalois.fixedField_fixingSubgroup] at hbmem
  -- `ℚ⟮aL⟯` is the range of `aeval aL`
  have halg : IsAlgebraic ℚ aL := ⟨f, hf.ne_zero, hfL⟩
  have hsub : (ℚ⟮aL⟯ : IntermediateField ℚ Lg).toSubalgebra
      = Algebra.adjoin ℚ ({aL} : Set Lg) :=
    IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic halg
  have hbmem2 : bL ∈ Algebra.adjoin ℚ ({aL} : Set Lg) := by
    rw [← hsub]
    exact hbmem
  rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.mem_range] at hbmem2
  obtain ⟨B, hB⟩ := hbmem2
  refine ⟨B, dvd_of_aeval_eq_zero hf hfL ?_⟩
  rw [map_sub, map_pow, hB, hHL, sub_self]

/-! ### A finite Galois witness for one root of `f` and a square root of `H` there -/

/-- Inside `AlgebraicClosure ℚ`, a finite Galois extension of `ℚ` carrying a root `aL`
of the irreducible `f` together with a nonzero square root `bL` of `H (aL)`.

`Lg` is the normal closure of `ℚ(a, b)` for `a` a root of `f` and `b` a square root of
`H (a)` in the algebraic closure; `FiniteDimensional` and `IsGalois` are propositions,
so they travel in the existential and the caller never has to name `Lg`. -/
theorem exists_finite_galois_witness (f H : Polynomial ℚ) (hf : Irreducible f)
    (hfH : ¬ f ∣ H) :
    ∃ (Lg : IntermediateField ℚ (AlgebraicClosure ℚ)) (aL bL : Lg),
      FiniteDimensional ℚ Lg ∧ IsGalois ℚ Lg ∧
        Polynomial.aeval aL f = 0 ∧ Polynomial.aeval aL H = bL ^ 2 ∧ bL ≠ 0 := by
  classical
  obtain ⟨a, ha⟩ : ∃ a : AlgebraicClosure ℚ, Polynomial.aeval a f = 0 :=
    IsAlgClosed.exists_aeval_eq_zero_of_injective (AlgebraicClosure ℚ)
      (algebraMap ℚ (AlgebraicClosure ℚ)).injective f
      (Polynomial.degree_pos_of_irreducible hf).ne'
  have haH : Polynomial.aeval a H ≠ 0 := fun h => hfH (dvd_of_aeval_eq_zero hf ha h)
  obtain ⟨b, hb⟩ : ∃ b : AlgebraicClosure ℚ, b ^ 2 = Polynomial.aeval a H :=
    IsAlgClosed.exists_pow_nat_eq _ two_pos
  have hb0 : b ≠ 0 := by
    intro h
    apply haH
    rw [← hb, h]
    ring
  have hia : IsIntegral ℚ a := IsAlgebraic.isIntegral ⟨f, hf.ne_zero, ha⟩
  have hib : IsIntegral ℚ b := (Algebra.IsAlgebraic.isAlgebraic b).isIntegral
  haveI : FiniteDimensional ℚ (ℚ⟮a, b⟯ : IntermediateField ℚ (AlgebraicClosure ℚ)) :=
    IntermediateField.finiteDimensional_adjoin_pair hia hib
  have hle := IntermediateField.le_normalClosure
    (ℚ⟮a, b⟯ : IntermediateField ℚ (AlgebraicClosure ℚ))
  refine ⟨_, ⟨a, hle (IntermediateField.subset_adjoin ℚ _ (by simp))⟩,
    ⟨b, hle (IntermediateField.subset_adjoin ℚ _ (by simp))⟩, inferInstance, ⟨⟩, ?_, ?_, ?_⟩
  · apply Subtype.ext
    rw [coe_aeval_intermediateField]
    simpa using ha
  · apply Subtype.ext
    rw [coe_aeval_intermediateField]
    push_cast
    exact hb.symm
  · intro h
    exact hb0 (congrArg Subtype.val h)

/-! ### The square-specialisation lemma, from Chebotarev alone -/

set_option maxHeartbeats 1000000 in
/-- The polynomial form of `long243:res:squarespec`: under the paper's modular
hypothesis, `H` is a square modulo the irreducible `f`. -/
theorem sq_sub_dvd_of_chebotarev (hCheb : ChebotarevFrobenius)
    (f H : Polynomial ℚ) (hf : Irreducible f) (hfH : ¬ f ∣ H)
    (d : ℕ) (hd : 0 < d) (G J : Polynomial ℤ)
    (hG : G.map (Int.castRingHom ℚ) = Polynomial.C (d : ℚ) * f)
    (hJ : J.map (Int.castRingHom ℚ) = Polynomial.C ((d : ℚ) ^ 2) * H)
    (hmod : ∃ N : ℕ, ∀ ℓ : ℕ, ℓ.Prime → N < ℓ → ∀ r : ZMod ℓ,
        (G.map (Int.castRingHom (ZMod ℓ))).eval r = 0 →
        (J.map (Int.castRingHom (ZMod ℓ))).eval r ≠ 0 ∧
          IsSquare ((J.map (Int.castRingHom (ZMod ℓ))).eval r)) :
    ∃ B : Polynomial ℚ, f ∣ B ^ 2 - H := by
  classical
  obtain ⟨Lg, aL, bL, hfd, hgal, hfL, hHL, hbne⟩ := exists_finite_galois_witness f H hf hfH
  haveI := hfd
  haveI := hgal
  rcases exists_sign_flip_or_sq_sub_dvd (Lg : Type) aL bL f H hf hfL hHL with
    ⟨σ, hσa, hσb⟩ | hres
  · exact absurd
      (frobenius_descent hCheb (Lg : Type) σ aL bL hσa hσb hbne f H hfL hHL d hd G J hG hJ hmod)
      not_false
  · exact hres

/-- **`long243:res:squarespec`, reduced to Chebotarev.**  The paper's square
specialisation lemma follows from the single external input `ChebotarevFrobenius`
with no unfinished local bridge.  The row remains `covered_modulo_external`: the
Chebotarev density theorem is not proved here, nor is it in the pinned Mathlib. -/
theorem squareSpecialisation_of_chebotarev (hC : ChebotarevFrobenius) :
    SquareSpecialisation := by
  intro L₀ _ _ α f H hf hfα hHα d hd G J hG hJ hmod
  have hfH : ¬ f ∣ H := by
    intro hdvd
    obtain ⟨q, hq⟩ := hdvd
    exact hHα (by rw [hq, map_mul, hfα, zero_mul])
  obtain ⟨B, hB⟩ := sq_sub_dvd_of_chebotarev hC f H hf hfH d hd G J hG hJ hmod
  have hsq : Polynomial.aeval α B ^ 2 = Polynomial.aeval α H := by
    obtain ⟨q, hq⟩ := hB
    have h1 : Polynomial.aeval α (B ^ 2 - H) = Polynomial.aeval α (f * q) := by rw [hq]
    rw [map_sub, map_pow, map_mul, hfα, zero_mul, sub_eq_zero] at h1
    exact h1
  refine ⟨Polynomial.aeval α B, ?_, ?_, hsq⟩
  · have hmem : Polynomial.aeval α B ∈ Algebra.adjoin ℚ ({α} : Set L₀) := by
      rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.mem_range]
      exact ⟨B, rfl⟩
    have hle : Algebra.adjoin ℚ ({α} : Set L₀)
        ≤ (IntermediateField.adjoin ℚ ({α} : Set L₀)).toSubalgebra :=
      Algebra.adjoin_le fun x hx => IntermediateField.subset_adjoin ℚ _ hx
    exact hle hmem
  · intro h
    apply hHα
    rw [← hsq, h]
    ring

/-! ### The four downstream rows, with Chebotarev as the only hypothesis -/

/-- `long243:res:transportsquare` from `ChebotarevFrobenius` alone. -/
theorem transport_square_of_chebotarev (hCheb : ChebotarevFrobenius)
    (a u v : ℕ → ℕ) (m : ℕ) (c : ℤ) (T : ℕ) (hm : 0 < m)
    (hv : ∀ n, T ≤ n → 0 < v n)
    (hnum : ∀ n, T ≤ n → u (n + 1) + v n = a n * u n)
    (hden : ∀ n, T ≤ n → v (n + 1) = a n * v n)
    (hcop : ∀ n, T ≤ n → Nat.Coprime (u n) (v n))
    (hzero : ZeroLowerDensity
      {n : ℕ | (u n : ℤ) ≠ (m : ℤ) * risingBinomial n + c})
    (L₀ : Type) [Field L₀] [Algebra ℚ L₀] (α : L₀)
    (hroot : α ^ 3 = α - algebraMap ℚ L₀ (6 * (c : ℚ) / (m : ℚ))) :
    ∃ β ∈ IntermediateField.adjoin ℚ ({α} : Set L₀),
      β ≠ 0 ∧ β ^ 2 = α ^ 2 - 1 :=
  transport_square (squareSpecialisation_of_chebotarev hCheb) a u v m c T hm hv hnum hden
    hcop hzero L₀ α hroot

/-- `long243:res:cubicexclusion` from `ChebotarevFrobenius` alone. -/
theorem cubic_exclusion_of_chebotarev (hCheb : ChebotarevFrobenius)
    (a C D : ℕ → ℤ) (ha : ∀ n, 0 < a n) (hC : ∀ n, 0 < C n) (hD : ∀ n, 0 < D n)
    (hCrec : ∀ n, C (n + 1) = a n * C n - D n)
    (hDrec : ∀ n, D (n + 1) = a n * D n)
    (A B : ℚ) (hA : 0 < A) :
    (∃ dens : ℝ, 0 < dens ∧ ∃ N : ℕ, ∀ X : ℕ, N ≤ X →
        dens * (X : ℝ) ≤ (exceptionCount
          {n : ℕ | (C n : ℚ) ≠ A * (n : ℚ) * ((n : ℚ) + 1) * ((n : ℚ) + 2) + B}
          (X + 1) : ℝ)) ∧
      ¬ ∃ N : ℕ, ∀ n, N ≤ n →
        (C n : ℚ) = A * (n : ℚ) * ((n : ℚ) + 1) * ((n : ℚ) + 2) + B :=
  cubic_exclusion (squareSpecialisation_of_chebotarev hCheb) a C D ha hC hD hCrec hDrec A B hA

/-- `res:cubicrate` / `long243:res:cubicrate` from `ChebotarevFrobenius` alone. -/
theorem cubic_rate_irrationality_of_chebotarev (hCheb : ChebotarevFrobenius)
    (a : ℕ → ℕ) (ha : StrictMono a) (hpos : ∀ n, 0 < a n)
    (hrate : Filter.Tendsto (fun n : ℕ => (n : ℝ) ^ 3 *
      ((a n : ℝ) ^ 2 / (a (n + 1) : ℝ) - (1 + 3 / (n : ℝ))))
      Filter.atTop (nhds 0))
    (Sv : ℝ) (hS : HasSum (fun n : ℕ => 1 / (a n : ℝ)) Sv) :
    Irrational Sv :=
  cubic_rate_irrationality (squareSpecialisation_of_chebotarev hCheb) a ha hpos hrate Sv hS

#print axioms ErdosProblems.Erdos243.PaperCompleteR21.dvd_of_aeval_eq_zero
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.exists_sign_flip_or_sq_sub_dvd
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.exists_finite_galois_witness
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.sq_sub_dvd_of_chebotarev
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.squareSpecialisation_of_chebotarev
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.transport_square_of_chebotarev
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.cubic_exclusion_of_chebotarev
#print axioms ErdosProblems.Erdos243.PaperCompleteR21.cubic_rate_irrationality_of_chebotarev

end ErdosProblems.Erdos243.PaperCompleteR21
