import Solutions.ExternalVerification269AllScaleLattice
#print axioms Erdos249257.ExternalVerification269AllScaleLattice.qsmul_normalizedTailState_eq_int_of_value_eq_rat
#print axioms Erdos249257.ExternalVerification269AllScaleLattice.exists_normalizedTailState_collision_of_value_eq_rat
#print axioms Erdos249257.ExternalVerification269AllScaleLattice.smoothHeight_mul_prime_dvd_boundaryHeight
#print axioms Erdos249257.ExternalVerification269AllScaleLattice.dyadicShellTsumTailR235_eq_range_add
#print axioms Erdos249257.ExternalVerification269AllScaleLattice.heightNormalizer235_mul_windowMass_eq_int
#print axioms Erdos249257.ExternalVerification269AllScaleLattice.two_mul_heightNormalizer235
