import Solutions.PalomarCorpus.E249bg

#print axioms PalomarCorpus.E249.PaperStatementsBG.abs_mobiusMersenneTheta_sub_prefix_le
#print axioms PalomarCorpus.E249.PaperStatementsBG.mobiusMersenneTheta_ge_alpha
#print axioms PalomarCorpus.E249.PaperStatementsBG.mobiusMersenneTheta_lt_one
#print axioms PalomarCorpus.E249.PaperStatementsBG.mobiusMersenneTheta_one_and_two
#print axioms PalomarCorpus.E249.PaperStatementsBG.positive_direct_sum_sub_theta_two_gt
#print axioms PalomarCorpus.E249.PaperStatementsBG.primitive_form_abs_gt
#print axioms PalomarCorpus.E249.PaperStatementsBG.rankOneSubrankQuotient_one_five_sub_theta_two_lt_one_div_fifteen
#print axioms PalomarCorpus.E249.PaperStatementsBG.rankOneSubrankQuotient_sub_theta_two_gt
#print axioms PalomarCorpus.E249.PaperStatementsBG.theta_hankel_det_neg
#print axioms PalomarCorpus.E249.PaperStatementsBG.theta_hankel_two_neg
#print axioms PalomarCorpus.E249.PaperStatementsBG.theta_strict_logConcave
