import Solutions.ExternalVerification257PaperStatementsQ

#print axioms Erdos249257.ExternalVerification257PaperStatementsQ.paper_exact_row_integerHalfCarry_eq_one
#print axioms Erdos249257.ExternalVerification257PaperStatementsQ.paper_integerHalfCarry_eq_two_pow_sub_localPrefixQuotient
#print axioms Erdos249257.ExternalVerification257PaperStatementsQ.paper_mobiusCenteredHalfCarry_add_two
