import Solutions.PalomarCorpus.E1049_06

#print axioms PalomarCorpus.E1049.PaperStatementsX.no_finite_simultaneous_two_three_system
#print axioms PalomarCorpus.E1049.PaperStructuresL.no_finite_simultaneous_two_three_system_unconditional
