import Solutions.ExternalVerification68PaperStatementsC

#print axioms Erdos249257.ExternalVerification68PaperStatementsC.supported_breakpoint_escape
#print axioms Erdos249257.ExternalVerification68PaperStatementsC.supported_first_band_cancellation
#print axioms Erdos249257.ExternalVerification68PaperStatementsC.supported_integral_normal_form
#print axioms Erdos249257.ExternalVerification68PaperStatementsC.supported_quotient_band
#print axioms Erdos249257.ExternalVerification68PaperStatementsC.uniform_family_boundary
#print axioms Erdos249257.ExternalVerification68PaperStatementsC.uniform_family_members
