import Solutions.ExternalVerification1041DiskFamilySeparation

#print axioms Erdos249257.ExternalVerification1041DiskFamilySeparation.diskFamilyCoefficient_lt_two_of_uniform_separation
#print axioms Erdos249257.ExternalVerification1041DiskFamilySeparation.diskFamilyCoefficient_radius_two_lt_two
#print axioms Erdos249257.ExternalVerification1041DiskFamilySeparation.diskFamilyCoefficient_three_six_fifths_lt_two
#print axioms Erdos249257.ExternalVerification1041DiskFamilySeparation.diskFamily_length_lt_two_of_squared_bound
#print axioms Erdos249257.ExternalVerification1041DiskFamilySeparation.diskFamily_length_lt_two_of_uniform_separation
