import Solutions.PalomarCorpus.E257ah

#print axioms PalomarCorpus.E257.PaperStatementsAH.greedy_survives_of_mem_mersenneAchievementSet
#print axioms PalomarCorpus.E257.PaperStatementsAH.halfTwoChannelCap_lt_mersenneTail
#print axioms PalomarCorpus.E257.PaperStatementsAH.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms PalomarCorpus.E257.PaperStatementsAH.half_mem_mersenneAchievementSet_of_secondChannelSeparation
#print axioms PalomarCorpus.E257.PaperStatementsAH.half_mem_mersenneAchievementSet_of_secondChannelSeparationRat_from_seven
#print axioms PalomarCorpus.E257.PaperStatementsAH.half_mem_mersenneAchievementSet_of_skipped_dyadicCap
#print axioms PalomarCorpus.E257.PaperStatementsAH.half_mem_mersenneAchievementSet_of_skipped_twoChannelCap
#print axioms PalomarCorpus.E257.PaperStatementsAH.irrational_erdosBorweinMersenneConstant
#print axioms PalomarCorpus.E257.PaperStatementsAH.mem_mersenneAchievementSet_iff_greedy_survival
#print axioms PalomarCorpus.E257.PaperStatementsAH.mem_mersenneAchievementSet_of_greedySkippedSupport_infinite
#print axioms PalomarCorpus.E257.PaperStatementsAH.mem_mersenneAchievementSet_of_greedy_survival
#print axioms PalomarCorpus.E257.PaperStatementsAH.mersenneGap_pos
#print axioms PalomarCorpus.E257.PaperStatementsAH.mersenneTail_eq_weight_add
#print axioms PalomarCorpus.E257.PaperStatementsAH.mersenneTail_le_two_mul_weight
#print axioms PalomarCorpus.E257.PaperStatementsAH.mersenneTail_lt_weight
#print axioms PalomarCorpus.E257.PaperStatementsAH.two_mul_mersenneWeight_succ_lt
