import Solutions.PalomarCorpus.E249_22

#print axioms PalomarCorpus.E249.PaperStatementsAT.actualLcm_corridor_pos
#print axioms PalomarCorpus.E249.PaperStatementsAT.corridor_height_lt_letter
#print axioms PalomarCorpus.E249.PaperStatementsAT.corridor_letter_pos
#print axioms PalomarCorpus.E249.PaperStatementsAU.irrational_of_topEdgeResidueGapSupply
#print axioms PalomarCorpus.E249.PaperStatementsAU.topEdgeResidueGap_forces_nonintegral
#print axioms PalomarCorpus.E249.PaperStatementsAU.topEdgeResidueGap_orbit_nonintegral
#print axioms PalomarCorpus.E249.PaperStatementsAU.topEdgeResidueGap_unfolded
#print axioms PalomarCorpus.E249.PaperStatementsAX.irrational_of_paperAdjacentSuffixMidbandSupply
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperAdjacentSuffixMidbandSupply_of_adjacentSuffixMidband
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperAdjacentSuffixMidbandSupply_of_flexibleActualTopEdgeMagnitude
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperAdjacentSuffixMidbandSupply_of_oddGuardTopEdgeHalfWordBand
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperTeChain_fifth_gives_nonintegrality
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperTeChain_first_four_imply_topEdgeSupply
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperTeChain_five_sufficient_for_irrationality
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperTeChain_item_one_unfolded
