import Solutions.ExternalVerification1049AdelicHeightBridge

#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.zudilin_firstTransformedRow_initialMonomial
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.threePow_fortyOne_lt_twoPow_sixtyFive
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.twoPow_sixtyFour_lt_threePow_fortyOne
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.threeHalves_rectangular_hp_gap_gt_threeThirteenths
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.threeHalves_hankelChargeThreshold_lt_eightFortyOne
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.zudilinScalarContent_cannot_meet_required_charge
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.zudilinScalarPlusBorder_cannot_meet_required_charge
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.three_two_scalar_margin_lt_explicit
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.exists_distinct_binary_selectors_same_fourJet_of_rank_41
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.fourJet_card_gt_two_pow_of_rank_41
#print axioms Erdos249257.ExternalVerification1049AdelicHeightBridge.exists_ne_map_eq_map_ne_of_card_mul_lt
