import Solutions.ExternalVerification249PrefixTwoAdicExclusion

#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.totientPrefix
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.totientPrefix_succ
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.totientPrefix_eq_corpusForm
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.prefixTail
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.oddPart_mul_prefixTail_eq_intCast
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.prefix_twoAdic_denominator_exclusion
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.prefix_twoAdic_denominator_lower_bound
#print axioms Erdos249257.ExternalVerification249PrefixTwoAdicExclusion.prefix_twoAdic_odd_denominator_floor
