import Solutions.PalomarCorpus.E257ar

#print axioms PalomarCorpus.E257.PaperStatementsAR.abs_exactLocalMersenneRowValue_sub_half_le
#print axioms PalomarCorpus.E257.PaperStatementsAR.abs_localMersennePrefixValue_sub_half_le
#print axioms PalomarCorpus.E257.PaperStatementsAR.cofinalExactLocalMersenneHalfRows_of_criticalQuotientSupply
#print axioms PalomarCorpus.E257.PaperStatementsAR.exactLocalMersenneHalfRow_two_mul_sub_two_of_skippedCoreSharpCapacity
#print axioms PalomarCorpus.E257.PaperStatementsAR.exists_exactRowStrictUpperExtension_two_mul_sub_one_of_exact_below
#print axioms PalomarCorpus.E257.PaperStatementsAR.exists_exactRowStrictUpperFill_of_skippedCoreSharpCapacity
#print axioms PalomarCorpus.E257.PaperStatementsAR.exists_first_localMersenne_crossing
#print axioms PalomarCorpus.E257.PaperStatementsAR.half_mem_mersenneAchievementSet_of_cofinalExactLocalRows
#print axioms PalomarCorpus.E257.PaperStatementsAR.half_mem_mersenneAchievementSet_of_criticalQuotientSupply
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_one_lt_upperWindow_of_exact_below
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometric
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometricCore
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_capacity_band_exclusion
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_exact_row_from_skipped_prefix
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_finite_row_value_ne_half
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_fractional_mass_bound_not_necessary
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_fractional_mass_bound_suffices_for_sharp_capacity
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_real_quotient_core
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_real_quotient_margins
#print axioms PalomarCorpus.E257.PaperStatementsAR.precriticalCrossingTax_of_futureThreshold
