import Solutions.ExternalVerification257PaperStructuresBL

#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.paper_seam_limit_unconditional
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.paper_theoremA_half_membership
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.paper_universal_band_condition_would_close_half
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.tendsto_seamGreedyFiniteValue_greedyHalfTargetValue
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.tendsto_seamGreedyNormalizedRemainder
#print axioms Erdos249257.ExternalVerification257PaperStructuresBL.wordPulse_le
