import Solutions.ExternalVerification249PaperStatementsBB

#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.canonicalTotientKernelFamily_entries
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.canonicalTotientKernelFamily_independent_card_and_span
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.canonical_family_basis_through_level
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.canonical_level_zero_channels
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.card_canonical_dyadic_index
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.completeLevelZeroTruncation_is_totient_and_rank_one
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.finrank_throughLevel_zero_eq_one
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.linearIndependent_canonical_dyadic_family
#print axioms Erdos249257.ExternalVerification249PaperStatementsBB.retainedSections_basis_and_rank
