import Solutions.PalomarCorpus.E251_07

#print axioms PalomarCorpus.E251.LcmDiagonalCriterion.irrationalInitial_iff_allLcmDiagonal_nonintegral
#print axioms PalomarCorpus.E251.LcmDiagonalCriterion.irrationalInitial_iff_cofinalNonintegralTailShifts
#print axioms PalomarCorpus.E251.LcmDiagonalCriterion.irrationalInitial_iff_nonintegral_on_schedule
#print axioms PalomarCorpus.E251.LcmDiagonalCriterion.tailShiftIntegral_iff_orderOf_dvd
#print axioms PalomarCorpus.E251.PolynomialShiftCountermodel.polynomialGapTailCountermodel
#print axioms PalomarCorpus.E251.PrimeGapIdentity.prime0_le_polynomial
#print axioms PalomarCorpus.E251.PrimeGapIdentity.primeDisplayedSeries_eq_four_add_two_primeGapSeries
#print axioms PalomarCorpus.E251.PrimeGapIdentity.primeDisplayedSeries_irrational_iff_primeGapSeries
#print axioms PalomarCorpus.E251.PrimeGapIdentity.primeGapSeries_summable
#print axioms PalomarCorpus.E251.PrimeGapIdentity.primeSeries_eq_two_add_primeGapSeries
#print axioms PalomarCorpus.E251.PrimeGapIdentity.primeSeries_irrational_iff_primeGapSeries
#print axioms PalomarCorpus.E251.PrimeGapIdentity.primeSeries_summable
#print axioms PalomarCorpus.E251.PrimeGapNonperiodicity.primeGap0_not_eventually_periodic
