import Solutions.ExternalVerification1049RationalBaseContour

#print axioms Erdos249257.ExternalVerification1049RationalBaseContour.eightyOne_twoHundredths_lt_zudilinContour
#print axioms Erdos249257.ExternalVerification1049RationalBaseContour.zudilinContour_lt_half
#print axioms Erdos249257.ExternalVerification1049RationalBaseContour.threeHalves_outside_zudilinContourRegion
#print axioms Erdos249257.ExternalVerification1049RationalBaseContour.thirtyoneFour_power_mem_zudilinContourRegion
#print axioms Erdos249257.ExternalVerification1049RationalBaseContour.zudilinJ_ge
#print axioms Erdos249257.ExternalVerification1049RationalBaseContour.zudilinC0_gt
