import Solutions.ExternalVerification243RepairEntropy
#print axioms Erdos249257.ExternalVerification243RepairEntropy.repairedFamily_recovery_energy_divisionFree
#print axioms Erdos249257.ExternalVerification243RepairEntropy.repaired_card_bound_of_independent
#print axioms Erdos249257.ExternalVerification243RepairEntropy.eventually_recoveryPayment_eq_one_of_fixedLength
