import Solutions.ExternalVerification257PaperStructuresBB

#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.SeamTwoSidedDyadicCellEscape.twoSided
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.largestSkipLateAt_fourteen
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.mem_seamGreedySupport_iff_scaled
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.paperResetSqrtEscape_iff_square
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamGreedy_terminal_false_iff_upperOrMiddle
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamUpperBranch_remainder_add_resetCharge_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBB.wordPulse_le
