import Solutions.ExternalVerification257PaperStructuresCB

#print axioms Erdos249257.ExternalVerification257PaperStructuresCB.exists_infinite_positive_support_half_of_cofinalCylinderStages
#print axioms Erdos249257.ExternalVerification257PaperStructuresCB.halfTerminalOnlyStripWitness_of_feedbackAdvance
#print axioms Erdos249257.ExternalVerification257PaperStructuresCB.halfTerminalOnlyStripWitness_of_inStripTwoSheetStage_via_carries_three_four
#print axioms Erdos249257.ExternalVerification257PaperStructuresCB.paper_shared_prefix_family_strip_witness_after_feedback_all_depths
#print axioms Erdos249257.ExternalVerification257PaperStructuresCB.paper_shared_prefix_family_strip_witness_after_feedback_of_all_depths
