import Erdos257PeriodNoncollapse.BooleanMobiusCarry
import ErdosProblems.Erdos257.HalfCounterexampleFrontier

/-!
# Erdős #257: cofinal one-step repairs for the four-ninths greedy orbit

This module transfers the weakest surviving repair consumer from the audited
`1/21` orbit to the independently promising target `4/9`.  The target-specific
coordinate is

`Q_N = floor (4 * 2^N / 9) - P_N`,

where `P_N` is the binary Lambert prefix numerator of the actual greedy
support.  Its exact recurrence has only a binary floor bit and the usual
support-divisor load.  If `4/9` were outside the Mersenne achievement set,
the fatal-tail alternative would force `Q_N` to grow geometrically and hence
eventually make every step a strict increase.  Therefore repairs beyond every
cutoff already force membership.

The theorem proved here is a consumer.  Finite computation can test its
cofinal-repair hypothesis but cannot establish the cofinal quantifier.
-/

namespace ErdosProblems.Erdos257

open Erdos257PeriodNoncollapse
open Filter

/-- Integral dyadic floor of the target `4/9`. -/
def fourNinthsBinaryFloor (N : ℕ) : ℕ :=
  4 * 2 ^ N / 9

/-- The actual greedy Lambert prefix lies below the integral `4/9` floor. -/
theorem fourNinthsGreedyPrefixNumerator_le_floor (N : ℕ) :
    binaryCoeffPrefixNumerator
        (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))) N
      ≤ fourNinthsBinaryFloor N := by
  let c := supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))
  let P := binaryCoeffPrefixNumerator c N
  have hprefix :=
    binaryCoeffPrefix_greedySupport_le
      (x := (4 / 9 : ℝ)) (by norm_num) N
  have hnum := binaryCoeffPrefixNumerator_div_pow c N
  have hpowpos : (0 : ℝ) < (2 : ℝ) ^ N := by positivity
  have hnum_le : 9 * P ≤ 4 * 2 ^ N := by
    have hreal : (9 : ℝ) * (P : ℝ) ≤ 4 * (2 : ℝ) ^ N := by
      change
        (9 : ℝ) *
            (binaryCoeffPrefixNumerator
              (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))) N : ℝ)
          ≤ 4 * (2 : ℝ) ^ N
      change
        (binaryCoeffPrefixNumerator c N : ℝ) / (2 : ℝ) ^ N =
          binaryCoeffPrefix c N at hnum
      change binaryCoeffPrefix c N ≤ (4 / 9 : ℝ) at hprefix
      have hnum_eq :
          (binaryCoeffPrefixNumerator c N : ℝ) =
            (2 : ℝ) ^ N * binaryCoeffPrefix c N := by
        simpa [mul_comm] using
          (div_eq_iff (ne_of_gt hpowpos)).mp hnum
      rw [hnum_eq]
      nlinarith
    exact_mod_cast hreal
  change P ≤ 4 * 2 ^ N / 9
  omega

/-- Natural defect after removing the periodic floor orbit of `4/9`. -/
noncomputable def fourNinthsGreedyDefect (N : ℕ) : ℕ :=
  fourNinthsBinaryFloor N -
    binaryCoeffPrefixNumerator
      (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))) N

/-- The next digit of the dyadic floor orbit of `4/9`. -/
def fourNinthsFloorBit (N : ℕ) : ℤ :=
  (fourNinthsBinaryFloor (N + 1) : ℤ) -
    2 * (fourNinthsBinaryFloor N : ℤ)

theorem fourNinthsGreedyDefect_cast_eq (N : ℕ) :
    (fourNinthsGreedyDefect N : ℤ) =
      (fourNinthsBinaryFloor N : ℤ) -
        (binaryCoeffPrefixNumerator
          (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))) N : ℤ) := by
  exact Nat.cast_sub (fourNinthsGreedyPrefixNumerator_le_floor N)

/-- Exact one-step recurrence; the only nonperiodic input is the actual
greedy divisor load. -/
theorem fourNinthsGreedyDefect_succ (N : ℕ) :
    (fourNinthsGreedyDefect (N + 1) : ℤ) =
      2 * (fourNinthsGreedyDefect N : ℤ) +
        fourNinthsFloorBit N -
          (supportCoeff
            (greedyMersenneSupport (4 / 9 : ℝ)) (N + 1) : ℤ) := by
  rw [fourNinthsGreedyDefect_cast_eq, fourNinthsGreedyDefect_cast_eq,
    binaryCoeffPrefixNumerator]
  unfold fourNinthsFloorBit
  push_cast
  ring

/-- Quotient-remainder form of the target floor bit. -/
theorem fourNinthsFloorBit_eq_two_mul_mod_div (N : ℕ) :
    fourNinthsFloorBit N =
      ((2 * ((4 * 2 ^ N) % 9) / 9 : ℕ) : ℤ) := by
  have hpow : 4 * 2 ^ (N + 1) = 2 * (4 * 2 ^ N) := by
    rw [pow_succ]
    ring
  have hdecomp := Nat.mod_add_div (4 * 2 ^ N) 9
  have hquot :
      2 * (4 * 2 ^ N) / 9 =
        2 * ((4 * 2 ^ N) / 9) + 2 * ((4 * 2 ^ N) % 9) / 9 := by
    omega
  unfold fourNinthsFloorBit fourNinthsBinaryFloor
  rw [hpow, hquot]
  push_cast
  ring

theorem fourNinthsFloorBit_nonneg (N : ℕ) :
    0 ≤ fourNinthsFloorBit N := by
  rw [fourNinthsFloorBit_eq_two_mul_mod_div]
  positivity

theorem fourNinthsFloorBit_le_one (N : ℕ) :
    fourNinthsFloorBit N ≤ 1 := by
  rw [fourNinthsFloorBit_eq_two_mul_mod_div]
  have hmod : (4 * 2 ^ N) % 9 < 9 := Nat.mod_lt _ (by omega)
  have hbit : 2 * ((4 * 2 ^ N) % 9) / 9 ≤ 1 := by omega
  exact_mod_cast hbit

/-- Scaled future-multiple tail generated by the already selected prefix. -/
noncomputable def fourNinthsGreedyFinitePrefixTail (N : ℕ) : ℝ :=
  binaryCoeffTail
    (supportCoeff
      (greedyMersenneSupport (4 / 9 : ℝ) ∩ Set.Iic N)) N

theorem fourNinthsGreedyFinitePrefixTail_nonneg (N : ℕ) :
    0 ≤ fourNinthsGreedyFinitePrefixTail N :=
  binaryCoeffTail_nonneg _ N

/-- Exact real bridge from the integral target carry to the actual greedy
remainder and the finite-prefix divisor tail. -/
theorem fourNinths_targetCarry_eq_scaled_remainder_add_tail (N : ℕ) :
    (4 * (2 : ℝ) ^ N -
        9 * (binaryCoeffPrefixNumerator
          (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))) N : ℝ)) =
      9 * ((2 : ℝ) ^ N * greedyMersenneRemainder (4 / 9 : ℝ) N +
        fourNinthsGreedyFinitePrefixTail N) := by
  let A := greedyMersenneSupport (4 / 9 : ℝ)
  let AN := A ∩ Set.Iic N
  have hprefixValue :
      (∑ k ∈ Finset.range N,
          Set.indicator A mersenneWeight (k + 1)) =
        binaryCoeffPrefix (supportCoeff A) N +
          binaryCoeffTail (supportCoeff AN) N / (2 : ℝ) ^ N := by
    calc
      (∑ k ∈ Finset.range N,
          Set.indicator A mersenneWeight (k + 1)) =
          positiveMersenneSupportValue AN := by
            exact
              (positiveMersenneSupportValue_inter_Iic_eq_prefix A N).symm
      _ = erdosSupportSeries 2 AN :=
            positiveMersenneSupportValue_eq_erdosSupportSeries AN
      _ = binaryCoeffSeries (supportCoeff AN) :=
            erdosSupportSeries_two_eq_binaryCoeffSeries AN
      _ = binaryCoeffPrefix (supportCoeff AN) N +
            binaryCoeffTail (supportCoeff AN) N / (2 : ℝ) ^ N :=
              binaryCoeffSeries_eq_prefix_add_tail
                (supportCoeff AN) (supportCoeff_le_self AN) N
      _ = binaryCoeffPrefix (supportCoeff A) N +
            binaryCoeffTail (supportCoeff AN) N / (2 : ℝ) ^ N := by
              rw [binaryCoeffPrefix_supportCoeff_inter_Iic_eq A le_rfl]
  have hgreedy := greedyMersenne_prefix_add_remainder (4 / 9 : ℝ) N
  change
    (4 / 9 : ℝ) =
      (∑ k ∈ Finset.range N,
        Set.indicator A mersenneWeight (k + 1)) +
          greedyMersenneRemainder (4 / 9 : ℝ) N at hgreedy
  rw [hprefixValue] at hgreedy
  have hnum := binaryCoeffPrefixNumerator_div_pow (supportCoeff A) N
  have hpow : (2 : ℝ) ^ N ≠ 0 := by positivity
  change
    (binaryCoeffPrefixNumerator (supportCoeff A) N : ℝ) /
        (2 : ℝ) ^ N = binaryCoeffPrefix (supportCoeff A) N at hnum
  change
    4 * (2 : ℝ) ^ N -
        9 * (binaryCoeffPrefixNumerator (supportCoeff A) N : ℝ) =
      9 * ((2 : ℝ) ^ N * greedyMersenneRemainder (4 / 9 : ℝ) N +
        binaryCoeffTail (supportCoeff AN) N)
  field_simp [hpow] at hgreedy hnum
  nlinarith

/-- The scaled actual remainder is bounded by the natural defect plus one. -/
theorem fourNinths_scaled_greedyRemainder_le_defect_add_one (N : ℕ) :
    (2 : ℝ) ^ N * greedyMersenneRemainder (4 / 9 : ℝ) N ≤
      (fourNinthsGreedyDefect N : ℝ) + 1 := by
  have hbridge := fourNinths_targetCarry_eq_scaled_remainder_add_tail N
  have htail := fourNinthsGreedyFinitePrefixTail_nonneg N
  have hcast := fourNinthsGreedyDefect_cast_eq N
  have hmodNat := Nat.mod_add_div (4 * 2 ^ N) 9
  have hmod : (4 * 2 ^ N) % 9 < 9 := Nat.mod_lt _ (by omega)
  have hmodR : (((4 * 2 ^ N) % 9 : ℕ) : ℝ) < 9 := by exact_mod_cast hmod
  have hfloorR :
      (4 : ℝ) * (2 : ℝ) ^ N =
        9 * (fourNinthsBinaryFloor N : ℝ) + ((4 * 2 ^ N) % 9 : ℕ) := by
    exact_mod_cast (show
      4 * 2 ^ N = 9 * fourNinthsBinaryFloor N + (4 * 2 ^ N) % 9 by
        unfold fourNinthsBinaryFloor
        omega)
  have hdefR :
      (fourNinthsGreedyDefect N : ℝ) =
        (fourNinthsBinaryFloor N : ℝ) -
          (binaryCoeffPrefixNumerator
            (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ))) N : ℝ) := by
    exact_mod_cast hcast
  nlinarith

/-- A fatal `4/9` state forces geometric growth in the defect. -/
theorem fourNinthsGreedyDefect_geometricLower_of_not_mem
    (hnot : (4 / 9 : ℝ) ∉ mersenneAchievementSet) :
    ∃ n : ℕ, ∃ δ : ℝ, 0 < δ ∧
      ∀ k : ℕ,
        (2 : ℝ) ^ (n + k) * δ ≤
          (fourNinthsGreedyDefect (n + k) : ℝ) + 1 := by
  have hnotSurvive :
      ¬ ∀ n : ℕ,
        greedyMersenneRemainder (4 / 9 : ℝ) n ≤ mersenneTail n := by
    intro hsurvive
    exact hnot
      ((mem_mersenneAchievementSet_iff_greedy_survival
        (4 / 9 : ℝ)).2 ⟨by norm_num, hsurvive⟩)
  push Not at hnotSurvive
  obtain ⟨n, hn⟩ := hnotSurvive
  let δ := greedyMersenneRemainder (4 / 9 : ℝ) n - mersenneTail n
  have hfatal : GreedyMersenneFatalAt (4 / 9 : ℝ) n := hn
  refine ⟨n, δ, sub_pos.mpr hn, ?_⟩
  intro k
  have heq := greedyMersenneRemainder_sub_tail_eq_of_fatalAt_add hfatal k
  have htail := mersenneTail_nonneg (n + k)
  have hrem : δ ≤ greedyMersenneRemainder (4 / 9 : ℝ) (n + k) := by
    dsimp [δ]
    linarith
  have hscaled := mul_le_mul_of_nonneg_left hrem
    (by positivity : (0 : ℝ) ≤ (2 : ℝ) ^ (n + k))
  exact hscaled.trans
    (fourNinths_scaled_greedyRemainder_le_defect_add_one (n + k))

/-- On non-membership the defect eventually dominates the identity. -/
theorem fourNinthsDefect_eventually_gt_add_two_of_not_mem
    (hnot : (4 / 9 : ℝ) ∉ mersenneAchievementSet) :
    ∃ M : ℕ, ∀ m : ℕ, M ≤ m → m + 2 < fourNinthsGreedyDefect m := by
  obtain ⟨n, δ, hδ, hgeo⟩ :=
    fourNinthsGreedyDefect_geometricLower_of_not_mem hnot
  have hN : Tendsto (fun m : ℕ => (m : ℝ) / (2 : ℝ) ^ m)
      atTop (nhds 0) := by
    simpa using tendsto_pow_const_div_const_pow_of_one_lt 1
      (by norm_num : (1 : ℝ) < 2)
  have hOne : Tendsto (fun m : ℕ => (1 : ℝ) / (2 : ℝ) ^ m)
      atTop (nhds 0) :=
    tendsto_const_nhds.div_atTop
      (tendsto_pow_atTop_atTop_of_one_lt (by norm_num : (1 : ℝ) < 2))
  have hratio : Tendsto
      (fun m : ℕ => ((m : ℝ) + 3) / (2 : ℝ) ^ m)
      atTop (nhds 0) := by
    have h := hN.add (hOne.const_mul 3)
    convert h using 1
    · funext m
      ring
    · simp
  obtain ⟨K, hK⟩ := (Metric.tendsto_atTop.1 hratio) δ hδ
  refine ⟨max n K, ?_⟩
  intro m hm
  have hmn : n ≤ m := (le_max_left n K).trans hm
  have hKm : K ≤ m := (le_max_right n K).trans hm
  have hgeo' : ((2 : ℝ) ^ m) * δ ≤
      (fourNinthsGreedyDefect m : ℝ) + 1 := by
    have h := hgeo (m - n)
    have hidx : n + (m - n) = m := by omega
    rwa [hidx] at h
  have hdist := hK m hKm
  have hratioPos :
      0 ≤ ((m : ℝ) + 3) / (2 : ℝ) ^ m := by positivity
  have hsmall : ((m : ℝ) + 3) / (2 : ℝ) ^ m < δ := by
      rw [Real.dist_eq, sub_zero, abs_of_nonneg hratioPos] at hdist
      exact hdist
  have hlin : (m : ℝ) + 3 < (2 : ℝ) ^ m * δ := by
    simpa [mul_comm] using
      (div_lt_iff₀ (by positivity : (0 : ℝ) < (2 : ℝ) ^ m)).mp hsmall
  have hfinal : ((m : ℕ) : ℝ) + 3 <
      (fourNinthsGreedyDefect m : ℝ) + 1 := hlin.trans_le hgeo'
  have hcast : (((m + 2 : ℕ) : ℝ)) < (fourNinthsGreedyDefect m : ℝ) := by
    push_cast
    linarith
  exact_mod_cast hcast

/-- Once the defect dominates the identity, every later step strictly rises. -/
theorem fourNinthsGreedyDefect_strictSucc_of_gt
    {N : ℕ} (hbig : N + 2 < fourNinthsGreedyDefect N) :
    fourNinthsGreedyDefect (N + 1) > fourNinthsGreedyDefect N := by
  have href := fourNinthsGreedyDefect_succ N
  have hbitpos := fourNinthsFloorBit_nonneg N
  have hload := supportCoeff_le_self
    (greedyMersenneSupport (4 / 9 : ℝ)) (N + 1)
  have hcap :
      (supportCoeff (greedyMersenneSupport (4 / 9 : ℝ)) (N + 1) : ℤ) ≤
        ((N + 1 : ℕ) : ℤ) := by exact_mod_cast hload
  have hQN : (((N + 3 : ℕ) : ℤ)) ≤ (fourNinthsGreedyDefect N : ℤ) := by
    have hc : (((N + 2 : ℕ) : ℤ)) < (fourNinthsGreedyDefect N : ℤ) := by
      exact_mod_cast hbig
    omega
  have hstrict : (fourNinthsGreedyDefect N : ℤ) <
      (fourNinthsGreedyDefect (N + 1) : ℤ) := by
    linarith
  exact_mod_cast hstrict

/-- A one-step repair means that the defect fails to rise. -/
def FourNinthsOneStepRepairSucc (N : ℕ) : Prop :=
  (fourNinthsGreedyDefect (N + 1) : ℤ) ≤ (fourNinthsGreedyDefect N : ℤ)

/-- Repairs occur beyond every cutoff, without a periodicity requirement. -/
def FourNinthsOneStepRepairCofinal : Prop :=
  ∀ K : ℕ, ∃ N : ℕ, K ≤ N ∧ FourNinthsOneStepRepairSucc N

/-- **Weakest-form four-ninths endpoint.**  Cofinal one-step repairs force
`4/9` into the Mersenne achievement set. -/
theorem four_ninths_mem_mersenneAchievementSet_of_repairCofinal
    (hrep : FourNinthsOneStepRepairCofinal) :
    (4 / 9 : ℝ) ∈ mersenneAchievementSet := by
  by_contra hnot
  obtain ⟨M, hM⟩ := fourNinthsDefect_eventually_gt_add_two_of_not_mem hnot
  obtain ⟨N, hMN, hrepN⟩ := hrep M
  have hinc : fourNinthsGreedyDefect N < fourNinthsGreedyDefect (N + 1) :=
    fourNinthsGreedyDefect_strictSucc_of_gt (hM N hMN)
  have hincZ : (fourNinthsGreedyDefect N : ℤ) <
      (fourNinthsGreedyDefect (N + 1) : ℤ) := by exact_mod_cast hinc
  exact (not_le_of_gt hincZ) hrepN

/-- The surviving periodic producer asks for an actual repair at every
positive multiple of `120`.  The argument below uses only its cofinality; the
all-depth arithmetic statement itself remains open. -/
def FourNinthsMultiple120RepairSupply : Prop :=
  ∀ k : ℕ,
    FourNinthsOneStepRepairSucc (120 * (k + 1) - 1)

theorem fourNinths_repairCofinal_of_multiple120RepairSupply
    (h120 : FourNinthsMultiple120RepairSupply) :
    FourNinthsOneStepRepairCofinal := by
  intro K
  refine ⟨120 * (K + 1) - 1, ?_, h120 K⟩
  omega

theorem four_ninths_mem_of_multiple120RepairSupply
    (h120 : FourNinthsMultiple120RepairSupply) :
    (4 / 9 : ℝ) ∈ mersenneAchievementSet :=
  four_ninths_mem_mersenneAchievementSet_of_repairCofinal
    (fourNinths_repairCofinal_of_multiple120RepairSupply h120)

/-! ## Finite-support exclusion and the full counterexample endpoint -/

/-- No finite Boolean support using ranks at least two sums to `4/9`.
The reduced-denominator order theorem makes the support lcm divide six, so
every selected rank is `2`, `3`, or `6`; exact arithmetic excludes all eight
subsets. -/
theorem finiteErdosSum_ne_four_div_nine
    (F : Finset ℕ) (hF : ∀ n ∈ F, 2 ≤ n) :
    finiteErdosSum F 2 ≠ (4 : ℚ) / 9 := by
  intro heq
  have h0 : 0 ∉ F := by
    intro hzero
    have := hF 0 hzero
    omega
  have hne : F.Nonempty := by
    by_contra hempty
    rw [Finset.not_nonempty_iff_eq_empty.mp hempty] at heq
    norm_num [finiteErdosSum] at heq
  have horder :=
    oddDoublingOrder_finiteErdosSum_den_eq_lcm F hne h0
  have hden : (finiteErdosSum F 2).den = 9 := by
    rw [heq]
    norm_num
  have horder' :
      oddDoublingOrder 9 (by decide : Odd 9) = F.lcm id := by
    simpa only [hden] using horder
  let hcop : Nat.Coprime 2 9 := by decide
  have h_ord_dvd_six :
      orderOf (ZMod.unitOfCoprime 2 hcop) ∣ 6 := by
    have hpow_unit : (ZMod.unitOfCoprime 2 hcop) ^ 6 = 1 := by
      apply Units.ext
      change (((ZMod.unitOfCoprime 2 hcop : (ZMod 9)ˣ) : ZMod 9) ^ 6) = 1
      rw [ZMod.coe_unitOfCoprime]
      decide
    exact (orderOf_dvd_iff_pow_eq_one).2 hpow_unit
  have hord : oddDoublingOrder 9 (by decide : Odd 9) ∣ 6 := by
    simpa [oddDoublingOrder] using h_ord_dvd_six
  have hlcm : F.lcm id ∣ 6 := by
    rw [← horder']
    exact hord
  have hlcm' : F.lcm (fun m : ℕ ↦ m) ∣ 6 := by
    simpa only [id_eq] using hlcm
  have hranks : ∀ n ∈ F, n = 2 ∨ n = 3 ∨ n = 6 := by
    intro n hn
    have hndvd : n ∣ 6 :=
      dvd_trans (Finset.dvd_lcm (f := fun m : ℕ ↦ m) hn) hlcm'
    have hnle : n ≤ 6 := Nat.le_of_dvd (by omega) hndvd
    obtain ⟨k, hk⟩ := hndvd
    have hn2 := hF n hn
    interval_cases n <;> omega
  have hF_eq :
      F = ({2, 3, 6} : Finset ℕ).filter (fun n ↦ n ∈ F) := by
    ext n
    simp only [Finset.mem_filter, Finset.mem_insert, Finset.mem_singleton]
    constructor
    · intro hn
      exact ⟨hranks n hn, hn⟩
    · exact fun hn ↦ hn.2
  by_cases h2 : 2 ∈ F <;>
    by_cases h3 : 3 ∈ F <;>
      by_cases h6 : 6 ∈ F <;> {
        rw [hF_eq] at heq
        simp only [finiteErdosSum, Finset.sum_filter] at heq
        norm_num [finiteErdosSum, h2, h3, h6] at heq
      }

/-- Cofinal repairs produce an infinite support whose reciprocal-Mersenne
series is exactly `4/9`. -/
theorem exists_infinite_four_ninths_counterexample_of_repairCofinal
    (hrep : FourNinthsOneStepRepairCofinal) :
    ∃ A : Set ℕ, A.Infinite ∧
      erdosSupportSeries 2 A = (4 : ℝ) / 9 := by
  classical
  rcases four_ninths_mem_mersenneAchievementSet_of_repairCofinal hrep with
    ⟨A, hA0, hvalue⟩
  have hseries : erdosSupportSeries 2 A = (4 : ℝ) / 9 := by
    rw [← positiveMersenneSupportValue_eq_erdosSupportSeries]
    exact hvalue.symm
  refine ⟨A, ?_, hseries⟩
  intro hfinite
  let F : Finset ℕ := hfinite.toFinset
  have hFA : (↑F : Set ℕ) = A := by
    dsimp [F]
    exact hfinite.coe_toFinset
  have hcast : ((finiteErdosSum F 2 : ℚ) : ℝ) = (4 : ℝ) / 9 := by
    rw [← erdosSupportSeries_finset_eq_cast_finiteErdosSum F, hFA]
    exact hseries
  have hrat : finiteErdosSum F 2 = (4 : ℚ) / 9 := by
    apply Rat.cast_injective (α := ℝ)
    simpa using hcast
  have hFzero : 0 ∉ F := by
    intro hzero
    apply hA0
    rw [← hFA]
    exact hzero
  have hFone : 1 ∉ F := by
    intro hone
    have hle :
        (1 / (((2 : ℚ) ^ 1) - 1)) ≤ finiteErdosSum F 2 := by
      unfold finiteErdosSum
      exact Finset.single_le_sum
        (f := fun n : ℕ => 1 / (((2 : ℚ) ^ n) - 1))
        (fun n _ => by
          apply div_nonneg (by norm_num)
          exact sub_nonneg.mpr (one_le_pow₀ (by norm_num : (1 : ℚ) ≤ 2)))
        hone
    rw [hrat] at hle
    norm_num at hle
  have hFmin : ∀ n ∈ F, 2 ≤ n := by
    intro n hn
    have hn0 : n ≠ 0 := fun h => hFzero (h ▸ hn)
    have hn1 : n ≠ 1 := fun h => hFone (h ▸ hn)
    omega
  exact finiteErdosSum_ne_four_div_nine F hFmin hrat

/-- **Full conditional endpoint.** Cofinal one-step repairs give an infinite
rational Mersenne subseries and therefore refute Erdős #257's universal
irrationality assertion. -/
theorem not_universal_of_fourNinths_repairCofinal
    (hrep : FourNinthsOneStepRepairCofinal) :
    ¬ UniversalMersenneSubseriesIrrationality := by
  obtain ⟨A, hA, hseries⟩ :=
    exists_infinite_four_ninths_counterexample_of_repairCofinal hrep
  intro huniversal
  have hirr := huniversal A hA
  rw [hseries] at hirr
  have hcast : (4 / 9 : ℝ) = ((4 / 9 : ℚ) : ℝ) := by norm_num
  rw [hcast] at hirr
  exact (Rat.not_irrational (4 / 9 : ℚ)) hirr

theorem not_universal_of_fourNinths_multiple120RepairSupply
    (h120 : FourNinthsMultiple120RepairSupply) :
    ¬ UniversalMersenneSubseriesIrrationality :=
  not_universal_of_fourNinths_repairCofinal
    (fourNinths_repairCofinal_of_multiple120RepairSupply h120)

#print axioms four_ninths_mem_mersenneAchievementSet_of_repairCofinal
#print axioms four_ninths_mem_of_multiple120RepairSupply
#print axioms finiteErdosSum_ne_four_div_nine
#print axioms exists_infinite_four_ninths_counterexample_of_repairCofinal
#print axioms not_universal_of_fourNinths_repairCofinal
#print axioms not_universal_of_fourNinths_multiple120RepairSupply

end ErdosProblems.Erdos257
