import Solutions.ExternalVerification257PaperStatementsAX

#print axioms Erdos249257.ExternalVerification257PaperStatementsAX.largestSkipLateAt_fourteen
#print axioms Erdos249257.ExternalVerification257PaperStatementsAX.mem_seamGreedySupport_iff_scaled
#print axioms Erdos249257.ExternalVerification257PaperStatementsAX.paper_exact_row_double_or_recycle
#print axioms Erdos249257.ExternalVerification257PaperStatementsAX.paper_exact_row_example_six_and_eleven
#print axioms Erdos249257.ExternalVerification257PaperStatementsAX.paper_returning_endpoint_may_fail_to_grow
