import Solutions.ExternalVerification249PaperStatementsAM

#print axioms Erdos249257.ExternalVerification249PaperStatementsAM.cos_nonpos_of_quarterFarFromInt
#print axioms Erdos249257.ExternalVerification249PaperStatementsAM.irrational_totientSeries_of_digitChange_count
#print axioms Erdos249257.ExternalVerification249PaperStatementsAM.irrational_totientSeries_of_quarterFarPhase_count
#print axioms Erdos249257.ExternalVerification249PaperStatementsAM.irrational_totientSeries_of_quarterFarPhase_proportion
#print axioms Erdos249257.ExternalVerification249PaperStatementsAM.quarterFarFromInt_iff_binaryDigitAt_change
#print axioms Erdos249257.ExternalVerification249PaperStatementsAM.quarterFarFromInt_iff_floor_bounds
