import Solutions.ExternalVerification68PaperStatementsA

#print axioms Erdos249257.ExternalVerification68PaperStatementsA.carry_characterisation
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.cofinal_first_prime_occurrences
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.companion_orbit
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.companion_orbit_boundary
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.divisor_channel_coordinates
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.finite_channel_moment_certificate
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.finite_channel_moment_certificate_eq
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.global_complementary_criterion_nat
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.global_complementary_criterion_prime
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.lower_interval_criterion
#print axioms Erdos249257.ExternalVerification68PaperStatementsA.maximal_prime_power_survival
