import Solutions.ExternalVerification269PaperStatementsD

#print axioms Erdos249257.ExternalVerification269PaperStatementsD.realPrefixLcm_eq_of_sameLogCell
#print axioms Erdos249257.ExternalVerification269PaperStatementsD.realPrefixLcm_jump_first
#print axioms Erdos249257.ExternalVerification269PaperStatementsD.realPrefixLcm_jump_second
#print axioms Erdos249257.ExternalVerification269PaperStatementsD.realPrefixLcm_jump_third
#print axioms Erdos249257.ExternalVerification269PaperStatementsD.realSmoothExponentShell_bounds
#print axioms Erdos249257.ExternalVerification269PaperStatementsD.running_lcm_real_cutoff_exact
#print axioms Erdos249257.ExternalVerification269PaperStatementsD.threePrimeKernelQ_eq_of_sameRealLogCell
