import Solutions.PalomarCorpus.E257_40

#print axioms PalomarCorpus.E257.AchievementSetGeometry.supportedMersenneAchievementSet_geometry_and_volume
#print axioms PalomarCorpus.E257.AchievementSetGeometry.volume_supportedMersenneAchievementSet_eq_zero_of_rat_value
#print axioms PalomarCorpus.E257.ActualUpperSuccessor.actualUpperRightPacketLinearEscape_iff_successorLinearEscape
#print axioms PalomarCorpus.E257.ActualUpperSuccessor.actualUpperSuccessorLinearEscape_completeCounterexample
#print axioms PalomarCorpus.E257.BooleanMobiusCarry.BooleanMobiusCarryCertificate.reconstructsSupport
#print axioms PalomarCorpus.E257.BooleanMobiusCarry.exists_booleanMobiusCarry_of_support_fraction
#print axioms PalomarCorpus.E257.BooleanMobiusCarry.exists_normalized_support_fraction_iff_exists_booleanMobiusCarry
#print axioms PalomarCorpus.E257.BooleanMobiusCarry.support_fraction_of_booleanMobiusCarry
#print axioms PalomarCorpus.E257.DyadicObservationSummability.dyadic_supportObservationMass_sum_le
#print axioms PalomarCorpus.E257.DyadicObservationSummability.summable_dyadic_supportObservationMass
#print axioms PalomarCorpus.E257.DyadicObservationSummability.tendsto_dyadic_supportObservationMass_mean
