import Solutions.PalomarCorpus.E243u

#print axioms PalomarCorpus.E243.PaperStructuresU.energySqrt_summable_iff
#print axioms PalomarCorpus.E243.PaperStructuresU.energy_criterion
#print axioms PalomarCorpus.E243.PaperStructuresU.energy_le_two_energySqrt
#print axioms PalomarCorpus.E243.PaperStructuresU.energy_summable_iff
#print axioms PalomarCorpus.E243.PaperStructuresU.exists_late_energy_window
#print axioms PalomarCorpus.E243.PaperStructuresU.oddPrimePower_supply
#print axioms PalomarCorpus.E243.PaperStructuresU.oddPrimePower_supply_nat
#print axioms PalomarCorpus.E243.PaperStructuresU.unitRecordIncrement_criterion
