import Solutions.ExternalVerification68PaperStatementsB

#print axioms Erdos249257.ExternalVerification68PaperStatementsB.prime_channel_corrector
#print axioms Erdos249257.ExternalVerification68PaperStatementsB.radius_no_eventual_ratio_upper
#print axioms Erdos249257.ExternalVerification68PaperStatementsB.radius_not_littleO
#print axioms Erdos249257.ExternalVerification68PaperStatementsB.square_subsequence_radius
#print axioms Erdos249257.ExternalVerification68PaperStatementsB.strict_successor_characterisation
