import Solutions.PalomarCorpus.E249_01

#print axioms PalomarCorpus.E249.PaperStatementsA.actualLcmTailDiff_shift_pos
#print axioms PalomarCorpus.E249.PaperStatementsA.actualLcm_integral_forces_topEdgeResidue
#print axioms PalomarCorpus.E249.PaperStatementsA.carryOrbit_eq_tail_diff
#print axioms PalomarCorpus.E249.PaperStatementsA.irrational_totient_series_iff_lcm_diagonal_certificate_supply
#print axioms PalomarCorpus.E249.PaperStatementsAD.certifiedKill_all_upto_sixteen
#print axioms PalomarCorpus.E249.PaperStatementsAD.dtwWindowSeparatedPairs_iff_irrational_totient_series
#print axioms PalomarCorpus.E249.PaperStatementsAD.irrational_totient_series_iff_certificate_supply
#print axioms PalomarCorpus.E249.PaperStatementsAG.exists_totientParity_arbitrarilyManySeparatedCarry_rational_countermodel
#print axioms PalomarCorpus.E249.PaperStatementsAI.tsum_totient_div_pow_two_ne_ratCast_of_den_le_79639646646701375323355774875831053
#print axioms PalomarCorpus.E249.PaperStatementsAK.gap_check_window_1_240_first_failure
#print axioms PalomarCorpus.E249.PaperStatementsAT.certifiedKill_diagonal_all_imported_through_t64
#print axioms PalomarCorpus.E249.PaperStatementsAT.irrational_totientSeries_iff_cofinalDirectedLcmCertificateSupply
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_101_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_121_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_125_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_127_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_128_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_67_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_81_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.certifiedKill_97_300
#print axioms PalomarCorpus.E249.PaperStatementsAU.exists_diagonalKill_le_82
#print axioms PalomarCorpus.E249.PaperStatementsAU.periodMultipleKillSupply_iff_irrational
#print axioms PalomarCorpus.E249.PaperStructuresN.certifiedKill_diagonal_t64
