import Solutions.ExternalVerification251PaperStatementsG

#print axioms Erdos249257.ExternalVerification251PaperStatementsG.carryPartialSum_eq
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.dyadicPartialSumQ_eq_start_add_differences
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.infinite_prime_gap_identity
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.irrational_realPrimeGapTail_zero_iff
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.irrational_tsum_primeDyadicTerm_iff_primeGap
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.irrationality_reformulation
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.polynomial_countermodel
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.prime0_dyadic_summation_by_parts
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.prime_gaps_not_eventually_periodic
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.rational_bounded_perturbation
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.rational_small_pair_bundle
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.rationality_classification
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.realPrimeGapTail_eq_tsum_shifted_gaps
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.realPrimeGapTail_recurrence
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.realPrimeGapTail_zero
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.real_signed_two_window
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.real_small_pair_prime_endpoint
#print axioms Erdos249257.ExternalVerification251PaperStatementsG.tailShift_integral_totient_of_odd_den
