import ExternalVerification251ActualPrimeGapTail.Solution

#print axioms Erdos249257.ExternalVerification251ActualPrimeGapTail.exists_rationalPrimeGapTailState_representation_of_not_irrational
#print axioms Erdos249257.ExternalVerification251ActualPrimeGapTail.rationalPrimeGapTailState_recurrence
#print axioms Erdos249257.ExternalVerification251ActualPrimeGapTail.rationalPrimeGapTailShift_eventuallyIntegral
#print axioms Erdos249257.ExternalVerification251ActualPrimeGapTail.rationalPrimeGapTail_has_positive_shift_not_eventually_small
