import Solutions.ExternalVerification1041PaperStatementsS

#print axioms Erdos249257.ExternalVerification1041PaperStatementsS.chebyshev_configuration_attains
#print axioms Erdos249257.ExternalVerification1041PaperStatementsS.exists_gap_le_comparisonBound
#print axioms Erdos249257.ExternalVerification1041PaperStatementsS.monicScaledChebyshev_eq_prod
#print axioms Erdos249257.ExternalVerification1041PaperStatementsS.sharp_collinear_equality_attained
