import Solutions.ExternalVerification249PaperStatementsAX

#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.finite_grid_nonintegral_pair
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.joint35ConeWindow_eq
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.joint35_nonintegral_of_separated_window
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.joint35_truncation_error
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.paperGridNumerator_eq
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.paperTeChain_item_one_unfolded
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.specified_euler_tail_period
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.sum_sq_dist_from_phase_one
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.tailDifference_eq_coefficient_mul_series
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.tailDifference_sub_rationalApproximation
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.teChain_item_five_unfolded
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.teChain_item_four_unfolded
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.teChain_item_three_unfolded
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.teChain_item_two_unfolded
#print axioms Erdos249257.ExternalVerification249PaperStatementsAX.totientTail_enclosure
