import ErdosProblems.Erdos257.PaperCompleteR8.CountableMeans
import ErdosProblems.Erdos257.PaperCompleteR7.AnalyticTargets
import ErdosProblems.Erdos257.PaperCompleteR7.CoverKernel

/-!
# The missing incidence-to-kernel bridge, by recurrence comparison

Proof module for the r8 upgrade. No additional analytic target is
assumed in this module. The actual modular kernel is retained.

Instead of exchanging the two infinite divisibility sums in the paper, compare
the exact one-step recurrences. The fractional frame potential is a subsolution
of the same expanding recurrence as its positive divisor majorant. A bounded
above expanding defect is nonpositive. This proves the needed bridge directly.

Pinned API: Mathlib/Analysis/SpecialFunctions/Pow/Real.lean (`mul_rpow`,
`rpow_nonneg` and its real-power order lemmas); the two-term subadditivity is already used in
the desk-checked PaperCompleteR7.CoverKernel.
-/

noncomputable section
namespace ErdosProblems.Erdos257.PaperCompleteR8
open Finset
open Erdos249257
open ErdosProblems.Erdos257.PaperCompleteR7

/-- The real-base carry identity, including the normalised conductor zero. -/
theorem kernelWeight_step (B : ℝ) (hB : 1 < B) (N d : ℕ) :
    B * kernelWeight B d N - kernelWeight B d (N + 1) =
      if 0 < d ∧ d ∣ N + 1 then 1 else 0 := by
  classical
  rcases Nat.eq_zero_or_pos d with rfl | hd
  · simp only [kernelWeight, pow_zero, sub_self, div_zero, mul_zero,
      Nat.lt_irrefl, false_and, if_false]
  have hden : B ^ d - 1 ≠ 0 := (kernel_den_pos hB hd).ne'
  by_cases hd1 : d = 1
  · subst d
    have hB1 : B - 1 ≠ 0 := (sub_pos.mpr hB).ne'
    simp only [kernelWeight, Nat.mod_one, pow_zero, pow_one, Nat.zero_lt_one,
      Nat.one_dvd, and_self, if_true]
    field_simp [hB1]
    <;> ring
  have hone : 1 % d = 1 := Nat.mod_eq_of_lt (by omega)
  have hsuccmod : (N + 1) % d = (N % d + 1) % d := by
    rw [Nat.add_mod, hone]
  have hmodlt : N % d < d := Nat.mod_lt N hd
  by_cases hwrap : d ∣ N + 1
  · have hs : (N + 1) % d = 0 := Nat.mod_eq_zero_of_dvd hwrap
    have hmul : d ∣ N % d + 1 := Nat.dvd_of_mod_eq_zero (by rw [← hsuccmod, hs])
    have hle : d ≤ N % d + 1 := Nat.le_of_dvd (by omega) hmul
    have hnext : N % d + 1 = d := by omega
    have hp : B * B ^ (N % d) = B ^ d := by
      rw [← pow_succ', hnext]
    simp only [kernelWeight, hs, pow_zero, hd, hwrap, and_self, if_true]
    calc
      B * (B ^ (N % d) / (B ^ d - 1)) - 1 / (B ^ d - 1)
          = (B * B ^ (N % d) - 1) / (B ^ d - 1) := by ring
      _ = 1 := by rw [hp]; exact div_self hden
  · have hs0 : (N + 1) % d ≠ 0 := by
      intro hz
      exact hwrap (Nat.dvd_of_mod_eq_zero hz)
    have hnlt : N % d + 1 < d := by
      have hle : N % d + 1 ≤ d := by omega
      apply lt_of_le_of_ne hle
      intro heq
      exact hs0 (by rw [hsuccmod, heq, Nat.mod_self])
    have hs : (N + 1) % d = N % d + 1 := by
      rw [hsuccmod, Nat.mod_eq_of_lt hnlt]
    simp only [kernelWeight, hs, pow_succ, hwrap, and_false, if_false]
    ring

/-- Potential generated by a positive divisor majorant; conductor zero has
zero kernel, so no sign assumption at that irrelevant index is needed. -/
def divisorPotential (B : ℝ) (c : ℕ → ℝ) (N : ℕ) : ℝ :=
  ∑' d : ℕ, c d * kernelWeight B d N

/-- Summability before using the recurrence or exchanging a mean and a sum. -/
theorem summable_divisorPotential_terms (B : ℝ) (hB : 1 < B)
    (c : ℕ → ℝ) (hc : ∀ d, 0 < d → 0 ≤ c d)
    (hs : Summable (fun d : ℕ => c d / (d : ℝ))) (N : ℕ) :
    Summable (fun d => c d * kernelWeight B d N) := by
  have hmajor : Summable (fun d : ℕ =>
      (2 * (N : ℝ) + 1) * ((c d / (d : ℝ)) / (B - 1))) :=
    (hs.div_const (B - 1)).mul_left (2 * (N : ℝ) + 1)
  -- Mathlib/Topology/Algebra/InfiniteSum/ENNReal.lean:
  -- Summable.of_nonneg_of_le.
  apply Summable.of_nonneg_of_le _ _ hmajor
  · intro d
    rcases Nat.eq_zero_or_pos d with rfl | hd
    · simp [kernelWeight]
    · exact mul_nonneg (hc d hd) (kernelWeight_nonneg hB d N)
  · intro d
    rcases Nat.eq_zero_or_pos d with rfl | hd
    · simp [kernelWeight]
    · have h := mul_le_mul_of_nonneg_left
        (kernelWeight_le_pointwise_majorant B hB d N hd) (hc d hd)
      simp only [div_eq_mul_inv, mul_inv_rev] at h ⊢
      convert h using 1 <;> ring

theorem divisorPotential_nonneg (B : ℝ) (hB : 1 < B)
    (c : ℕ → ℝ) (hc : ∀ d, 0 < d → 0 ≤ c d) (N : ℕ) :
    0 ≤ divisorPotential B c N := by
  apply tsum_nonneg
  intro d
  rcases Nat.eq_zero_or_pos d with rfl | hd
  · simp [kernelWeight]
  · exact mul_nonneg (hc d hd) (kernelWeight_nonneg hB d N)

/-- The infinite majorant's exact carry pulse is a FINITE divisor sum. -/
theorem divisorPotential_step (B : ℝ) (hB : 1 < B)
    (c : ℕ → ℝ) (hc : ∀ d, 0 < d → 0 ≤ c d)
    (hs : Summable (fun d : ℕ => c d / (d : ℝ))) (N : ℕ) :
    B * divisorPotential B c N - divisorPotential B c (N + 1) =
      ∑ d ∈ (N + 1).divisors, c d := by
  have hN := summable_divisorPotential_terms B hB c hc hs N
  have hN1 := summable_divisorPotential_terms B hB c hc hs (N + 1)
  have hpoint : ∀ d : ℕ,
      B * (c d * kernelWeight B d N) - c d * kernelWeight B d (N + 1) =
        if 0 < d ∧ d ∣ N + 1 then c d else 0 := by
    intro d
    calc
      _ = c d * (B * kernelWeight B d N - kernelWeight B d (N + 1)) := by ring
      _ = _ := by rw [kernelWeight_step B hB]; split_ifs <;> ring
  unfold divisorPotential
  rw [← tsum_mul_left, ← (hN.mul_left B).tsum_sub hN1, tsum_congr hpoint]
  rw [tsum_eq_sum (s := (N + 1).divisors)]
  · apply Finset.sum_congr rfl
    intro d hd
    have hdiv : d ∣ N + 1 := (Nat.mem_divisors.mp hd).1
    have hpos : 0 < d := Nat.pos_of_dvd_of_pos hdiv (Nat.succ_pos N)
    exact if_pos ⟨hpos, hdiv⟩
  · intro d hd
    have hnot : ¬ (0 < d ∧ d ∣ N + 1) := by
      intro hh
      exact hd (Nat.mem_divisors.mpr ⟨hh.2, Nat.succ_ne_zero N⟩)
    exact if_neg hnot

/-- A bounded-above expanding subsolution cannot be positive anywhere. -/
theorem expanding_subsolution_nonpos (B : ℝ) (hB : 1 < B)
    (z : ℕ → ℝ) (C : ℝ)
    (hstep : ∀ n : ℕ, B * z n ≤ z (n + 1))
    (hbound : ∀ n : ℕ, z n ≤ C) : ∀ n, z n ≤ 0 := by
  intro N
  by_contra hbad
  have hz : 0 < z N := lt_of_not_ge hbad
  have hiter : ∀ k : ℕ, B ^ k * z N ≤ z (N + k) := by
    intro k
    induction k with
    | zero => simp only [pow_zero, one_mul, Nat.add_zero, le_refl]
    | succ k ih =>
      calc
        B ^ (k + 1) * z N = B * (B ^ k * z N) := by rw [pow_succ]; ring
        _ ≤ B * z (N + k) := mul_le_mul_of_nonneg_left ih (le_of_lt (lt_trans zero_lt_one hB))
        _ ≤ z (N + (k + 1)) := by simpa only [Nat.add_assoc] using hstep (N + k)
  -- Mathlib/Algebra/Order/Archimedean/Basic.lean: pow_unbounded_of_one_lt.
  obtain ⟨k, hk⟩ := pow_unbounded_of_one_lt (C / z N) hB
  have hlarge : C < B ^ k * z N := (div_lt_iff₀ hz).mp hk
  exact (not_lt_of_ge ((hiter k).trans (hbound (N + k)))) hlarge

/-- The finite positive frame potential. -/
def framePotential (F : Finset ℕ) (N : ℕ) : ℝ :=
  ∑ a ∈ F, kernelWeight 2 a N

/-- Every binary modular atom is at most one. -/
theorem kernelWeight_two_le_one (d N : ℕ) : kernelWeight 2 d N ≤ 1 := by
  rcases Nat.eq_zero_or_pos d with rfl | hd
  · simp [kernelWeight]
  have hden : 0 < (2 : ℝ) ^ d - 1 := kernel_den_pos (by norm_num) hd
  have hm : N % d ≤ d - 1 := by have := Nat.mod_lt N hd; omega
  have hpow : (2 : ℝ) ^ (N % d) ≤ 2 ^ (d - 1) :=
    pow_le_pow_right₀ (by norm_num) hm
  have hone : (1 : ℝ) ≤ 2 ^ (d - 1) := one_le_pow₀ (by norm_num)
  have heq : (2 : ℝ) ^ d = 2 * 2 ^ (d - 1) := by
    rw [← pow_succ']; congr 1; omega
  apply (div_le_one hden).2
  rw [heq]
  linarith only [hpow, hone]

theorem framePotential_nonneg (F : Finset ℕ) (N : ℕ) : 0 ≤ framePotential F N :=
  Finset.sum_nonneg (fun a _ => kernelWeight_nonneg (by norm_num) a N)

theorem framePotential_le_card (F : Finset ℕ) (N : ℕ) :
    framePotential F N ≤ (F.card : ℝ) := by
  calc
    _ ≤ ∑ _a ∈ F, (1 : ℝ) := Finset.sum_le_sum (fun a _ => kernelWeight_two_le_one a N)
    _ = _ := by simp only [Finset.sum_const, nsmul_eq_mul, mul_one]

/-- The finite frame's pulse is its actual divisor incidence. -/
theorem framePotential_step (F : Finset ℕ) (hF : 0 ∉ F) (N : ℕ) :
    2 * framePotential F N - framePotential F (N + 1) =
      ((F.filter (fun a => a ∣ N + 1)).card : ℝ) := by
  classical
  unfold framePotential
  rw [Finset.mul_sum, ← Finset.sum_sub_distrib]
  calc
    _ = ∑ a ∈ F, if a ∣ N + 1 then (1 : ℝ) else 0 := by
      apply Finset.sum_congr rfl
      intro a ha
      have ha0 : 0 < a := Nat.pos_of_ne_zero (fun h => hF (h ▸ ha))
      rw [kernelWeight_step 2 (by norm_num)]
      simp only [ha0, true_and]
    _ = _ := by rw [← Finset.sum_filter]; simp only [Finset.sum_const, nsmul_eq_mul, mul_one]

/-- The actual bridge U_F(N)^alpha <= sum_d c_d w_(2^alpha,d)(N).
The proof uses the recurrence rather than an unproved rearrangement of two
infinite divisor-indexed sums. -/
theorem framePotential_rpow_le_divisorPotential
    (F : Finset ℕ) (hF : 0 ∉ F) (α : ℝ) (hα : 0 < α) (hα1 : α ≤ 1)
    (c : ℕ → ℝ) (hc : ∀ d, 0 < d → 0 ≤ c d)
    (hs : Summable (fun d : ℕ => c d / (d : ℝ)))
    (hmajor : ∀ n : ℕ, 0 < n →
      (((F.filter (fun a => a ∣ n)).card : ℝ) ^ α) ≤ ∑ d ∈ n.divisors, c d)
    (N : ℕ) :
    framePotential F N ^ α ≤ divisorPotential ((2 : ℝ) ^ α) c N := by
  let B : ℝ := (2 : ℝ) ^ α
  have hB : 1 < B := Real.one_lt_rpow_iff_of_pos (by norm_num) |>.mpr
    (Or.inl ⟨by norm_num, hα⟩)
  let z : ℕ → ℝ := fun n => framePotential F n ^ α - divisorPotential B c n
  have hstep : ∀ n : ℕ, B * z n ≤ z (n + 1) := by
    intro n
    let f : ℝ := ((F.filter (fun a => a ∣ n + 1)).card : ℝ)
    have hf : 0 ≤ f := Nat.cast_nonneg _
    have hlinear : 2 * framePotential F n = framePotential F (n + 1) + f := by
      have hh := framePotential_step F hF n
      dsimp [f]
      linarith only [hh]
    have hfrac : B * framePotential F n ^ α ≤ framePotential F (n + 1) ^ α + f ^ α := by
      calc
        _ = (2 * framePotential F n) ^ α :=
          (Real.mul_rpow (by norm_num : (0 : ℝ) ≤ 2) (framePotential_nonneg F n)).symm
        _ = (framePotential F (n + 1) + f) ^ α := congrArg (fun x : ℝ => x ^ α) hlinear
        _ ≤ _ := Real.rpow_add_le_add_rpow (framePotential_nonneg F (n + 1)) hf hα.le hα1
    have hpulse := hmajor (n + 1) (Nat.succ_pos n)
    have hV := divisorPotential_step B hB c hc hs n
    change B * (framePotential F n ^ α - divisorPotential B c n) ≤
      framePotential F (n + 1) ^ α - divisorPotential B c (n + 1)
    change f ^ α ≤ _ at hpulse
    nlinarith only [hfrac, hpulse, hV]
  have hbound : ∀ n : ℕ, z n ≤ (F.card : ℝ) ^ α := by
    intro n
    have hpow := Real.rpow_le_rpow (framePotential_nonneg F n)
      (framePotential_le_card F n) hα.le
    have hV := divisorPotential_nonneg B hB c hc n
    dsimp [z]
    linarith only [hpow, hV]
  have hz := expanding_subsolution_nonpos B hB z ((F.card : ℝ) ^ α) hstep hbound N
  exact sub_nonpos.mp hz

/-- The binary real-base kernel agrees with the desk's normalisation. -/
theorem kernelWeight_two_eq_shiftedRadixAtom (N d : ℕ) :
    kernelWeight 2 d N = shiftedRadixAtom 2 N d := by
  by_cases hd : d = 0
  · subst d; simp [kernelWeight, shiftedRadixAtom]
  · simp only [kernelWeight, shiftedRadixAtom, hd, if_false, Nat.cast_ofNat]

/-- A finite frame's displacement is bounded by its positive potential. -/
theorem displacement_finset_le_framePotential (F : Finset ℕ) (N : ℕ) :
    displacement 2 (F : Set ℕ) N ≤ framePotential F N := by
  classical
  rw [displacement_eq_tsum 2 (F : Set ℕ) N (by norm_num)]
  rw [tsum_eq_sum (s := F)]
  · apply Finset.sum_le_sum
    intro d hd
    rw [Set.indicator_of_mem (show d ∈ (F : Set ℕ) from hd), displacementAtom,
      ← kernelWeight_two_eq_shiftedRadixAtom, ← kernelWeight_two_eq_shiftedRadixAtom]
    exact sub_le_self _ (kernelWeight_nonneg (by norm_num) d 0)
  · intro d hd
    simp [hd]

/-- The bridge specialised to the actual desk PositiveCoverData. -/
theorem positiveCover_frame_bridge (C : PositiveCoverData) (j N : ℕ) :
    framePotential (C.frame j) N ^ C.exponent j ≤
      divisorPotential ((2 : ℝ) ^ C.exponent j) (C.coefficient j) N :=
  framePotential_rpow_le_divisorPotential (C.frame j) (C.frame_positive j)
    (C.exponent j) (C.exponent_bounds j).1 (C.exponent_bounds j).2
    (C.coefficient j) (C.coefficient_nonneg j) (C.column_summable j)
    (C.majorises j) N

end ErdosProblems.Erdos257.PaperCompleteR8
end
