import Solutions.ExternalVerification243PrimitiveRecordRigidity
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.primitive_valuation_no_drop
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.protectedPrimePower_persists
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.odd_record_cut
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.exists_oddMultiple_trapHeight
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.numerator_bounded_of_oddPrimePower
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.centeredZero_forces_unit
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.sylvesterStep_of_centeredZero_pair
#print axioms Erdos249257.ExternalVerification243PrimitiveRecordRigidity.recordRiseTwo_sylvesterNext_eventually
