import Solutions.ExternalVerification249ResidueClassTotientSeries

#print axioms Erdos249257.ExternalVerification249ResidueClassTotientSeries.residue_series_irrational
#print axioms Erdos249257.ExternalVerification249ResidueClassTotientSeries.irrational_totientObservable
#print axioms Erdos249257.ExternalVerification249ResidueClassTotientSeries.fixed_resolution_observable_irrational
#print axioms Erdos249257.ExternalVerification249ResidueClassTotientSeries.isolated_pulse_separation
#print axioms Erdos249257.ExternalVerification249ResidueClassTotientSeries.two_sided_prime_isolation
#print axioms Erdos249257.ExternalVerification249ResidueClassTotientSeries.irrational_dyadicValue_of_pulses
