import Solutions.ExternalVerification243SummableNegativeMassRigidity
#print axioms Erdos249257.ExternalVerification243SummableNegativeMassRigidity.summableNegativeMass_completeRigidity

#print axioms Erdos249257.ExternalVerification243SummableNegativeMassRigidity.finite_negative_mass_scalar
#print axioms Erdos249257.ExternalVerification243SummableNegativeMassRigidity.canonical_finite_negative_mass
