import Solutions.ExternalVerification243PaperStructuresAC

#print axioms Erdos249257.ExternalVerification243PaperStructuresAC.cubic_exclusion_unconditional
#print axioms Erdos249257.ExternalVerification243PaperStructuresAC.cubic_rate_irrationality_unconditional
#print axioms Erdos249257.ExternalVerification243PaperStructuresAC.squareSpecialisation
#print axioms Erdos249257.ExternalVerification243PaperStructuresAC.transport_square_unconditional
