import Solutions.ExternalVerification249CanonicalMersenneFrontier
#print axioms Erdos249257.ExternalVerification249CanonicalMersenneFrontier.fullMersenneBlockResidue_succ
#print axioms Erdos249257.ExternalVerification249CanonicalMersenneFrontier.fullMersenneCenteredResidueGapSupply_of_canonicalBasepoint
#print axioms Erdos249257.ExternalVerification249CanonicalMersenneFrontier.fullMersenneCanonicalBasepointResidueGapSupply_iff_irrational
