import Solutions.ExternalVerification249PaperStatementsI

#print axioms Erdos249257.ExternalVerification249PaperStatementsI.b6_synthetic_sequence_prescribed_differences
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.b6_synthetic_shift_combinations_same_form
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.certifiedKill_diagonal_table
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.exists_diagonalKill_le_82_paper
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.exists_diagonalKill_on_table
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.historical_table_and_complete_band
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.irrational_of_logarithmicDepth_diagonal_supply
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.periodLcm_seventeen_window_data
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.sixteen_certificates_and_exclusions
#print axioms Erdos249257.ExternalVerification249PaperStatementsI.small_certificates_and_exclusions
