import Solutions.ExternalVerification257AchievementSetGeometry

#print axioms Erdos249257.ExternalVerification257AchievementSetGeometry.volume_supportedMersenneAchievementSet_eq_zero_of_rat_value
#print axioms Erdos249257.ExternalVerification257AchievementSetGeometry.supportedMersenneAchievementSet_geometry_and_volume
