import Solutions.ExternalVerification249PaperStructuresS

#print axioms Erdos249257.ExternalVerification249PaperStructuresS.linearIndependent_one_and_least_residue_values
#print axioms Erdos249257.ExternalVerification249PaperStructuresS.positiveRadixValue_eq_of_even_constant
#print axioms Erdos249257.ExternalVerification249PaperStructuresS.radix_residue_series_irrational
#print axioms Erdos249257.ExternalVerification249PaperStructuresS.rational_mixed_moduli_with_constant_iff
#print axioms Erdos249257.ExternalVerification249PaperStructuresS.rational_zmod_radix_observable_iff
