import Solutions.ExternalVerification251AffineCircularity
#print axioms Erdos249257.ExternalVerification251AffineCircularity.adjacent_small_mismatch_iff_signed_two_window
#print axioms Erdos249257.ExternalVerification251AffineCircularity.cofinal_affinePowTwo_escape_iff_not_eventuallyIntegral
#print axioms Erdos249257.ExternalVerification251AffineCircularity.cofinal_blockResidue_escape_iff_not_eventuallyIntegral
