import Solutions.ExternalVerification249PaperStatementsAL

#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.basePower_dilation_not_universal
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.digit_block
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.exists_irrational_basePower_bounded_away
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.fract_mem_Icc_of_no_three_equal
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.fract_two_pow_mul_xi_mem_Icc
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.irrational_tail_zero
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.irrational_xi
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.no_three_consecutive_equal
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.not_approaches_int
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.not_eventually_periodic
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.not_near_integer_along_powers_of_two
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.one_div_eight_le_abs_sub_int
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.one_div_eight_le_dist_xi
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.strict_lower_bound_needed
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.tail_mem_Icc
#print axioms Erdos249257.ExternalVerification249PaperStatementsAL.upper_bound_needed_for_every_q
