import Solutions.ExternalVerification68CompanionOrbitBoundary

#print axioms Erdos249257.ExternalVerification68CompanionOrbitBoundary.companionOrbitBoundary_genericShift
#print axioms Erdos249257.ExternalVerification68CompanionOrbitBoundary.companionOrbitBoundary_factorialGapSeries
#print axioms Erdos249257.ExternalVerification68CompanionOrbitBoundary.tsum_unitFactTerm_eq_exp_one_sub_two
