import Solutions.ExternalVerification257PaperStructuresBH

#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.paper_compatible_finite_row_conditions
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.paper_largest_false_rank_algebra
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBH.wordPulse_le
