import Solutions.ExternalVerification249PaperStatementsAZ

#print axioms Erdos249257.ExternalVerification249PaperStatementsAZ.affineBinaryOrbit_difference_and_reset
#print axioms Erdos249257.ExternalVerification249PaperStatementsAZ.balancedPulse_common_history
#print axioms Erdos249257.ExternalVerification249PaperStatementsAZ.balancedPulse_label_lower_bound
#print axioms Erdos249257.ExternalVerification249PaperStatementsAZ.balancedPulse_no_decoder_from_common_state
#print axioms Erdos249257.ExternalVerification249PaperStatementsAZ.balancedPulse_series
#print axioms Erdos249257.ExternalVerification249PaperStatementsAZ.balancedPulse_tail_at
