import Solutions.PalomarCorpus.E257_39

#print axioms PalomarCorpus.E257.PaperStructuresCF.exists_seamWord_minimal_above
#print axioms PalomarCorpus.E257.PaperStructuresCF.integerGreedyBits_length
#print axioms PalomarCorpus.E257.PaperStructuresCF.paper_final_middle_cell_remaining_negative_values
#print axioms PalomarCorpus.E257.PaperStructuresCF.paper_finite_band_check_thirteen_to_thirty
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamAboveWord_minimal
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamAboveWord_strict
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamAdjacentCut_below_admissible
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamAdjacentCut_below_maximal
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamPerturbedFamily_gap_pos
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamPerturbedFamily_oldSum_injective
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamPerturbedFamily_separated
#print axioms PalomarCorpus.E257.PaperStructuresCF.seamWeights_length_eq
#print axioms PalomarCorpus.E257.PaperStructuresCF.wordPulse_le
