import Solutions.ExternalVerification257PaperStatementsP

#print axioms Erdos249257.ExternalVerification257PaperStatementsP.paper_carry_survivor_extinction
#print axioms Erdos249257.ExternalVerification257PaperStatementsP.paper_periodLcm_is_prefix_lcm
