import Solutions.ExternalVerification243PaperStructuresAB

#print axioms Erdos249257.ExternalVerification243PaperStructuresAB.exactOrbit_unbounded_of_error_not_eventually_zero
#print axioms Erdos249257.ExternalVerification243PaperStructuresAB.exists_multiplier_ge_four
#print axioms Erdos249257.ExternalVerification243PaperStructuresAB.slowNegative_eventually_zero_and_sylvesterNext_unconditional
#print axioms Erdos249257.ExternalVerification243PaperStructuresAB.tail_binaryTower_lower
