import Solutions.ExternalVerification257PaperStructuresAY

#print axioms Erdos249257.ExternalVerification257PaperStructuresAY.localMersenneHalfTarget_lower_word_eq_greedy_and_remainder_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresAY.localMersenneWeightsFrom_gapDominates
#print axioms Erdos249257.ExternalVerification257PaperStructuresAY.localMersenneWeights_gapDominates_even
#print axioms Erdos249257.ExternalVerification257PaperStructuresAY.localMersenneWeights_gapDominates_odd
