import Solutions.ExternalVerification68ChannelRadius

#print axioms Erdos249257.ExternalVerification68ChannelRadius.square_subsequence_radius_three_halves_lower
#print axioms Erdos249257.ExternalVerification68ChannelRadius.no_eventual_square_subsequence_three_halves_upper
#print axioms Erdos249257.ExternalVerification68ChannelRadius.not_isLittleO_square_subsequence_radius
#print axioms Erdos249257.ExternalVerification68ChannelRadius.square_subsequence_radius_cubic_lower
#print axioms Erdos249257.ExternalVerification68ChannelRadius.no_eventual_square_subsequence_cubic_upper
#print axioms Erdos249257.ExternalVerification68ChannelRadius.sharp_radius_satisfies_square_log_constraint
