import ExternalVerification68ChannelRadius.Solution

#print axioms Erdos249257.ExternalVerification68ChannelRadius.square_subsequence_radius_three_halves_lower
#print axioms Erdos249257.ExternalVerification68ChannelRadius.no_eventual_square_subsequence_three_halves_upper
#print axioms Erdos249257.ExternalVerification68ChannelRadius.not_isLittleO_square_subsequence_radius
