import Solutions.ExternalVerification257DyadicObservationSummability
#print axioms Erdos249257.ExternalVerification257DyadicObservationSummability.dyadic_supportObservationMass_sum_le
#print axioms Erdos249257.ExternalVerification257DyadicObservationSummability.summable_dyadic_supportObservationMass
#print axioms Erdos249257.ExternalVerification257DyadicObservationSummability.tendsto_dyadic_supportObservationMass_mean
