import Solutions.ExternalVerification249PaperStatementsG

#print axioms Erdos249257.ExternalVerification249PaperStatementsG.b6_adjugate_tail_cost_floor
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.b6_compressed_adjoint_identity_impossible
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.b6_rankOneSubrankQuotient_sub_totientSeries_offset_gt
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.diagonalPincerCertificateScales_list
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.diagonalPincerKillDepth_list
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.historical_table_size_and_initial_depths
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.sixteen_certificate_windows
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.small_certificate_windows
#print axioms Erdos249257.ExternalVerification249PaperStatementsG.totientBlock_eq_paper_indexed_sum
