import Solutions.ExternalVerification257PaperStatementsE

#print axioms Erdos249257.ExternalVerification257PaperStatementsE.half_of_cofinal_absolute_carry
#print axioms Erdos249257.ExternalVerification257PaperStatementsE.infinite_support_half_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms Erdos249257.ExternalVerification257PaperStatementsE.integerHalfCarry_eq_scaled_residual_add_tail
