import Solutions.PalomarCorpus.E1049c

#print axioms PalomarCorpus.E1049.PaperStatementsC.contour_enclosure
#print axioms PalomarCorpus.E1049.PaperStatementsC.four_rpow_mu_lt_thirtyOne
#print axioms PalomarCorpus.E1049.PaperStatementsC.inv_bvMu_eq
#print axioms PalomarCorpus.E1049.PaperStatementsC.omega_indicator
#print axioms PalomarCorpus.E1049.PaperStatementsC.paperBvMu_eq
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_bvMu
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_bv_cutoff
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_contour
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_contour_short
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_four_rpow_bvMu
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_four_rpow_mu
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_log_ratio
#print axioms PalomarCorpus.E1049.PaperStatementsC.printed_mu
#print axioms PalomarCorpus.E1049.PaperStatementsC.tailLow_le_trigammaSeries
#print axioms PalomarCorpus.E1049.PaperStatementsC.thirtyoneFour_between_rpow
#print axioms PalomarCorpus.E1049.PaperStatementsC.thirtyoneFour_ratio_chain
#print axioms PalomarCorpus.E1049.PaperStatementsC.trigammaSeries_le_tailHigh
#print axioms PalomarCorpus.E1049.PaperStatementsC.zudilinC0_enclosure
#print axioms PalomarCorpus.E1049.PaperStatementsC.zudilinContour_eq_inv_mu
#print axioms PalomarCorpus.E1049.PaperStatementsC.zudilinJ_enclosure
#print axioms PalomarCorpus.E1049.PaperStatementsC.zudilinMu_mul_zudilinContour
#print axioms PalomarCorpus.E1049.PaperStatementsC.zudilin_rpow_lt_iff_contourRegion
