import Solutions.PalomarCorpus.E257_33

#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_coeffTail_le_index_add_two
#print axioms PalomarCorpus.E257.PaperStatementsB.mem_mersenneAchievementSet_of_greedySkippedSupport_infinite
#print axioms PalomarCorpus.E257.PaperStatementsF.halfGreedy_precriticalSuffix_lt_iff_futureSkipCoverage
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_effective_horizon_test
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_eta_eq_coeffTail_sub_carry
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_eta_hasRationalValue
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_eventual_nonnegative_margin_equivalence
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_frozen_margin_limit_pos_iff
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_frozen_margin_normalised_monotone
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_frozen_margin_normalised_tendsto
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_frozen_margin_normalised_value
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_greedyHalfRemainder_ne_dyadicCap
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_halfGreedyPrefixSupport_eq_greedy_inter_Icc
