import Solutions.PalomarCorpus.E249ad

#print axioms PalomarCorpus.E249.PaperStatementsAD.certifiedKill_all_upto_sixteen
#print axioms PalomarCorpus.E249.PaperStatementsAD.certifiedKill_depth_floor
#print axioms PalomarCorpus.E249.PaperStatementsAD.dtwWindowSeparatedPairs_iff_irrational_totient_series
#print axioms PalomarCorpus.E249.PaperStatementsAD.exists_certifiedKill_iff_tail_diff_notMem_int
#print axioms PalomarCorpus.E249.PaperStatementsAD.irrational_totient_series_iff_all_tail_diffs_nonintegral
#print axioms PalomarCorpus.E249.PaperStatementsAD.irrational_totient_series_iff_certificate_supply
#print axioms PalomarCorpus.E249.PaperStatementsAD.tail_diff_int_of_den_dvd
#print axioms PalomarCorpus.E249.PaperStatementsAD.tail_diff_mem_int_iff_scaled_series_mem_int
#print axioms PalomarCorpus.E249.PaperStatementsAD.tail_diff_notMem_int_of_certifiedKill
#print axioms PalomarCorpus.E249.PaperStatementsAD.two_pow_mul_totient_series_eq
