import Solutions.PalomarCorpus.E257av

#print axioms PalomarCorpus.E257.PaperStatementsAV.dyadic_support_fraction_reciprocalMass_diverges_or_gt_one
#print axioms PalomarCorpus.E257.PaperStatementsAV.exists_unbounded_shifted_odd_tail_nat_state_of_support_fraction
#print axioms PalomarCorpus.E257.PaperStatementsAV.irrational_erdosSupportSeries_of_summable_reciprocal
#print axioms PalomarCorpus.E257.PaperStatementsAV.one_add_mul_card_le_two_mul_shifted_state
#print axioms PalomarCorpus.E257.PaperStatementsAV.one_lt_reciprocalMass_of_dyadic_support_fraction_of_two_pos_mem
#print axioms PalomarCorpus.E257.PaperStatementsAV.shifted_state_unbounded_of_infinite_support
