import Solutions.ExternalVerification249PaperStatementsBN

#print axioms Erdos249257.ExternalVerification249PaperStatementsBN.totient_convolution_weight_mul_zeta
#print axioms Erdos249257.ExternalVerification249PaperStatementsBN.totient_convolution_weight_not_periodic
#print axioms Erdos249257.ExternalVerification249PaperStatementsBN.totient_convolution_weight_prime
#print axioms Erdos249257.ExternalVerification249PaperStatementsBN.totient_convolution_weight_unbounded
