import Solutions.PalomarCorpus.E257_13

#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_coeff_series_of_weighted_coeff_block_certificates
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_erdosSum_factorial_support
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_erdosSum_of_lcm_gap
#print axioms PalomarCorpus.E257.PaperStatementsAG.irrational_erdosSupportSeries_pairwise_coprime
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_infinite_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_mobiusCenteredHalfCarry_nonneg
#print axioms PalomarCorpus.E257.PaperStatementsE.infinite_support_half_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms PalomarCorpus.E257.PaperStatementsF.half_mem_mersenneAchievementSet_of_skippedFullShellNonnegative
#print axioms PalomarCorpus.E257.PaperStatementsI.mobiusCenteredHalfCarry_nonneg_of_supportSeries_lt_half
#print axioms PalomarCorpus.E257.PaperStructuresBJ.half_mem_mersenneAchievementSet_of_skippedSeamEscape
#print axioms PalomarCorpus.E257.PaperStructuresBJ.skippedSeamAlignmentZero_iff_skippedFullShellNonnegative
