import Solutions.PalomarCorpus.E257_13

#print axioms PalomarCorpus.E257.PaperStructuresCD.exists_seamWord_minimal_above
#print axioms PalomarCorpus.E257.PaperStructuresCD.half_mem_mersenneAchievementSet_iff_unboundedUpperOrMiddle
#print axioms PalomarCorpus.E257.PaperStructuresCD.half_mem_mersenneAchievementSet_of_largestSkipLateStepSocket
#print axioms PalomarCorpus.E257.PaperStructuresCD.half_mem_mersenneAchievementSet_of_middleProducerCardEscape
#print axioms PalomarCorpus.E257.PaperStructuresCD.half_mem_mersenneAchievementSet_of_middleProducerRowEscape
#print axioms PalomarCorpus.E257.PaperStructuresCD.half_mem_mersenneAchievementSet_of_upperResetDyadicBandEscape
#print axioms PalomarCorpus.E257.PaperStructuresCD.integerGreedyBits_length
#print axioms PalomarCorpus.E257.PaperStructuresCD.middleProducer_allRight_forces_rational_skip
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamAboveWord_minimal
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamAboveWord_strict
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamAdjacentCut_below_admissible
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamAdjacentCut_below_maximal
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamPerturbedFamily_gap_pos
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamPerturbedFamily_oldSum_injective
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamPerturbedFamily_separated
#print axioms PalomarCorpus.E257.PaperStructuresCD.seamWeights_length_eq
#print axioms PalomarCorpus.E257.PaperStructuresCD.wordPulse_le
