import Solutions.PalomarCorpus.E257_26

#print axioms PalomarCorpus.E257.PaperStatementsAT.paper_terminal_strip_witness_six
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_infinite_of_cofinalStripReturn
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_infinite_of_mobiusCenteredHalfCarry_upperBound
#print axioms PalomarCorpus.E257.PaperStatementsK.paper_both_cofinal_statements_iff_half_membership
#print axioms PalomarCorpus.E257.PaperStatementsL.paper_terminal_strip_forces_half_membership
#print axioms PalomarCorpus.E257.PaperStatementsQ.paper_exact_row_integerHalfCarry_eq_one
#print axioms PalomarCorpus.E257.PaperStatementsQ.paper_integerHalfCarry_eq_two_pow_sub_localPrefixQuotient
#print axioms PalomarCorpus.E257.PaperStructuresBW.paper_seam_escape_implies_half_membership
