import Solutions.ExternalVerification257PaperStructuresBJ

#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.eventually_seamSupport_agrees
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_cofinalTerminalFalse
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_exists_unboundedSkippedRanksAlong
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_not_seamGreedyEventuallyRight
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_unboundedTerminalFalse
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.half_mem_mersenneAchievementSet_of_skippedSeamEscape
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.prefix_add_mersenneTail_lt_half_of_eventually_right
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.skippedSeamAlignmentZero_iff_skippedFullShellNonnegative
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.skipped_fullShell_neg_iff_alignment_and_seamRemainder_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBJ.unboundedTerminalFalse_iff_greedyMersenneSkippedSupport_infinite
