import Solutions.ExternalVerification1049PaperStatementsG

#print axioms Erdos249257.ExternalVerification1049PaperStatementsG.order_zudilinNormalizedHankelDet_all
#print axioms Erdos249257.ExternalVerification1049PaperStatementsG.thirtyoneFour_outside_bv_inside_contour
