import Solutions.ExternalVerification251PaperStatementsB

#print axioms Erdos249257.ExternalVerification251PaperStatementsB.finite_separation_complete
#print axioms Erdos249257.ExternalVerification251PaperStatementsB.one_tail_signed_certificate
