import Solutions.ExternalVerification257GeneralRepairCriterion
#print axioms Erdos249257.ExternalVerification257GeneralRepairCriterion.mem_iff_greedyBinaryDefect_cofinal_repairs
#print axioms Erdos249257.ExternalVerification257GeneralRepairCriterion.mem_iff_greedyBinaryDefect_sqrt_windows
