import ErdosProblems.Erdos1041.CyclicTetranomialCoefficientCase

/-!
# Erdős #1041: an L2 selector for cyclic tetranomials

For tails `c + b * v i`, a vanishing first moment removes the mixed term from
the total squared norm.  If that total is below `card S - 1`, at least two
distinct tails have norm below one.  Applied with `v i = w_i^s`, Newton's
identities provide the vanishing moment whenever `s` is absent from the
additive semigroup generated by `m-r` and `m-s` for

`g(w) = w^m + a*w^r + b*w^s + c`.

This module kernel-checks the finite-family mean-square identity, the two-point
selector, and a convenient coefficient-only budget.  The companion note gives
the Newton-semigroup specialization and cyclic-fibre consequence.
-/

open scoped ComplexConjugate

namespace ErdosProblems.Erdos1041

/-- Polarization of the squared norm of a translated complex multiple. -/
theorem normSq_const_add_mul (c b v : ℂ) :
    Complex.normSq (c + b * v) =
      Complex.normSq c + Complex.normSq b * Complex.normSq v +
        2 * (conj c * b * v).re := by
  simp [Complex.normSq_apply, Complex.mul_re, Complex.mul_im,
    Complex.add_re, Complex.add_im, Complex.conj_re, Complex.conj_im]
  ring

/-- Exact finite-family energy identity, including the mixed moment. -/
theorem sum_normSq_const_add_mul
    {ι : Type*} (S : Finset ι) (v : ι → ℂ) (b c : ℂ) :
    ∑ i ∈ S, Complex.normSq (c + b * v i) =
      (S.card : ℝ) * Complex.normSq c +
        Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) +
          2 * (conj c * b * (∑ i ∈ S, v i)).re := by
  have hcrossComplex :
      ∑ i ∈ S, conj c * b * v i = conj c * b * (∑ i ∈ S, v i) := by
    simp only [Finset.mul_sum]
  have hcrossReal :
      ∑ i ∈ S, (conj c * b * v i).re =
        (conj c * b * (∑ i ∈ S, v i)).re := by
    have h := congrArg Complex.re hcrossComplex
    simpa using h
  calc
    ∑ i ∈ S, Complex.normSq (c + b * v i) =
        ∑ i ∈ S, (Complex.normSq c +
          Complex.normSq b * Complex.normSq (v i) +
            2 * (conj c * b * v i).re) := by
          apply Finset.sum_congr rfl
          intro i hi
          exact normSq_const_add_mul c b (v i)
    _ = (S.card : ℝ) * Complex.normSq c +
          Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) +
            2 * ∑ i ∈ S, (conj c * b * v i).re := by
          simp only [Finset.sum_add_distrib, Finset.sum_const, nsmul_eq_mul,
            Finset.mul_sum]
    _ = (S.card : ℝ) * Complex.normSq c +
          Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) +
            2 * (conj c * b * (∑ i ∈ S, v i)).re := by
          nlinarith [hcrossReal]

/-- A vanishing first moment cancels the mixed term in the total tail energy. -/
theorem sum_normSq_const_add_mul_of_sum_eq_zero
    {ι : Type*} (S : Finset ι) (v : ι → ℂ) (b c : ℂ)
    (hmoment : ∑ i ∈ S, v i = 0) :
    ∑ i ∈ S, Complex.normSq (c + b * v i) =
      (S.card : ℝ) * Complex.normSq c +
        Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) := by
  rw [sum_normSq_const_add_mul S v b c, hmoment]
  simp

/-- If a finite real family has sum below its cardinality, one member is
strictly below one. -/
theorem exists_mem_lt_one_of_sum_lt_card
    {ι : Type*} (S : Finset ι) (x : ι → ℝ)
    (hsum : ∑ i ∈ S, x i < (S.card : ℝ)) :
    ∃ i ∈ S, x i < 1 := by
  by_contra h
  push_neg at h
  have hle : ∑ _i ∈ S, (1 : ℝ) ≤ ∑ i ∈ S, x i := by
    exact Finset.sum_le_sum fun i hi => h i hi
  have hcard : ∑ _i ∈ S, (1 : ℝ) = (S.card : ℝ) := by simp
  rw [hcard] at hle
  linarith

/-- Energy below `card S - 1` forces two distinct entries below one. -/
theorem exists_two_normSq_lt_one_of_sum_lt_card_sub_one
    {ι : Type*} (S : Finset ι) (x : ι → ℝ)
    (hcard : 2 ≤ S.card) (hx0 : ∀ i ∈ S, 0 ≤ x i)
    (hsum : ∑ i ∈ S, x i < (S.card : ℝ) - 1) :
    ∃ i ∈ S, ∃ j ∈ S, i ≠ j ∧ x i < 1 ∧ x j < 1 := by
  classical
  have hsumCard : ∑ i ∈ S, x i < (S.card : ℝ) := by linarith
  obtain ⟨i, hiS, hi⟩ := exists_mem_lt_one_of_sum_lt_card S x hsumCard
  have hEraseLe : ∑ j ∈ S.erase i, x j ≤ ∑ j ∈ S, x j := by
    rw [← Finset.sum_erase_add _ _ hiS]
    exact le_add_of_nonneg_right (hx0 i hiS)
  have hcardErase : ((S.erase i).card : ℝ) = (S.card : ℝ) - 1 := by
    rw [Finset.card_erase_of_mem hiS,
      Nat.cast_sub (by omega : 1 ≤ S.card)]
    norm_num
  have hsumErase : ∑ j ∈ S.erase i, x j < ((S.erase i).card : ℝ) := by
    rw [hcardErase]
    exact lt_of_le_of_lt hEraseLe hsum
  obtain ⟨j, hjErase, hj⟩ :=
    exists_mem_lt_one_of_sum_lt_card (S.erase i) x hsumErase
  have hjS : j ∈ S := (Finset.mem_erase.mp hjErase).2
  have hji : j ≠ i := (Finset.mem_erase.mp hjErase).1
  exact ⟨i, hiS, j, hjS, hji.symm, hi, hj⟩

/-- The exact mean-square selector, valid with a nonzero moment. -/
theorem exists_two_tails_norm_lt_one_of_exact_L2_budget
    {ι : Type*} (S : Finset ι) (v : ι → ℂ) (b c : ℂ)
    (hcard : 2 ≤ S.card)
    (hbudget :
      (S.card : ℝ) * Complex.normSq c +
          Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) +
            2 * (conj c * b * (∑ i ∈ S, v i)).re <
        (S.card : ℝ) - 1) :
    ∃ i ∈ S, ∃ j ∈ S, i ≠ j ∧
      ‖c + b * v i‖ < 1 ∧ ‖c + b * v j‖ < 1 := by
  have hsum :
      ∑ i ∈ S, Complex.normSq (c + b * v i) <
        (S.card : ℝ) - 1 := by
    rw [sum_normSq_const_add_mul S v b c]
    exact hbudget
  obtain ⟨i, hiS, j, hjS, hij, hi, hj⟩ :=
    exists_two_normSq_lt_one_of_sum_lt_card_sub_one S
      (fun k => Complex.normSq (c + b * v k)) hcard
      (fun k hk => Complex.normSq_nonneg _) hsum
  have hiNorm : ‖c + b * v i‖ < 1 := by
    rw [Complex.normSq_eq_norm_sq] at hi
    nlinarith [norm_nonneg (c + b * v i)]
  have hjNorm : ‖c + b * v j‖ < 1 := by
    rw [Complex.normSq_eq_norm_sq] at hj
    nlinarith [norm_nonneg (c + b * v j)]
  exact ⟨i, hiS, j, hjS, hij, hiNorm, hjNorm⟩

/-- The mean-square selector: a zero moment and energy below `card S - 1`
produce two distinct strict unit tails. -/
theorem exists_two_tails_norm_lt_one_of_L2_budget
    {ι : Type*} (S : Finset ι) (v : ι → ℂ) (b c : ℂ)
    (hcard : 2 ≤ S.card) (hmoment : ∑ i ∈ S, v i = 0)
    (hbudget :
      (S.card : ℝ) * Complex.normSq c +
          Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) <
        (S.card : ℝ) - 1) :
    ∃ i ∈ S, ∃ j ∈ S, i ≠ j ∧
      ‖c + b * v i‖ < 1 ∧ ‖c + b * v j‖ < 1 := by
  apply exists_two_tails_norm_lt_one_of_exact_L2_budget S v b c hcard
  rw [hmoment]
  simpa using hbudget

/-- A root-free Euclidean coefficient disk implies the L2 selector whenever
all moment vectors lie in the closed unit disk. -/
theorem exists_two_tails_norm_lt_one_of_coeff_L2_budget
    {ι : Type*} (S : Finset ι) (v : ι → ℂ) (b c : ℂ)
    (hcard : 2 ≤ S.card) (hmoment : ∑ i ∈ S, v i = 0)
    (hv : ∀ i ∈ S, Complex.normSq (v i) ≤ 1)
    (hcoeff :
      (S.card : ℝ) * (Complex.normSq b + Complex.normSq c) <
        (S.card : ℝ) - 1) :
    ∃ i ∈ S, ∃ j ∈ S, i ≠ j ∧
      ‖c + b * v i‖ < 1 ∧ ‖c + b * v j‖ < 1 := by
  have hsumV : ∑ i ∈ S, Complex.normSq (v i) ≤ (S.card : ℝ) := by
    calc
      ∑ i ∈ S, Complex.normSq (v i) ≤ ∑ _i ∈ S, (1 : ℝ) :=
        Finset.sum_le_sum fun i hi => hv i hi
      _ = (S.card : ℝ) := by simp
  have hb0 : 0 ≤ Complex.normSq b := Complex.normSq_nonneg _
  have hbudget :
      (S.card : ℝ) * Complex.normSq c +
          Complex.normSq b * ∑ i ∈ S, Complex.normSq (v i) <
        (S.card : ℝ) - 1 := by
    have hmul := mul_le_mul_of_nonneg_left hsumV hb0
    nlinarith
  exact exists_two_tails_norm_lt_one_of_L2_budget
    S v b c hcard hmoment hbudget

/-- A coefficient-level signed L2 selector with a supplied exact moment.  The
analytic companion computes that moment explicitly from Newton's identities. -/
theorem exists_two_tails_norm_lt_one_of_moment_coeff_budget
    {ι : Type*} (S : Finset ι) (v : ι → ℂ) (b c moment : ℂ)
    (hcard : 2 ≤ S.card) (hmoment : ∑ i ∈ S, v i = moment)
    (hv : ∀ i ∈ S, Complex.normSq (v i) ≤ 1)
    (hcoeff :
      (S.card : ℝ) * (Complex.normSq b + Complex.normSq c) +
          2 * (conj c * b * moment).re <
        (S.card : ℝ) - 1) :
    ∃ i ∈ S, ∃ j ∈ S, i ≠ j ∧
      ‖c + b * v i‖ < 1 ∧ ‖c + b * v j‖ < 1 := by
  have hsumV : ∑ i ∈ S, Complex.normSq (v i) ≤ (S.card : ℝ) := by
    calc
      ∑ i ∈ S, Complex.normSq (v i) ≤ ∑ _i ∈ S, (1 : ℝ) :=
        Finset.sum_le_sum fun i hi => hv i hi
      _ = (S.card : ℝ) := by simp
  have hb0 : 0 ≤ Complex.normSq b := Complex.normSq_nonneg _
  have hmul := mul_le_mul_of_nonneg_left hsumV hb0
  apply exists_two_tails_norm_lt_one_of_exact_L2_budget S v b c hcard
  rw [hmoment]
  nlinarith

/-- End-to-end finite-root form: the signed moment budget selects two roots
whose complete tetranomial spokes lie strictly below one. -/
theorem exists_two_tetranomialRoot_safeSpokes_of_moment_coeff_budget
    {ι : Type*} (S : Finset ι) (w : ι → ℂ)
    {m r s : ℕ} (hs : 1 ≤ s) (hsr : s ≤ r) (hrm : r ≤ m)
    {a b c moment : ℂ}
    (hcard : 2 ≤ S.card)
    (hroot : ∀ i ∈ S, w i ^ m + a * w i ^ r + b * w i ^ s + c = 0)
    (hw : ∀ i ∈ S, ‖w i‖ < 1) (hc : ‖c‖ < 1)
    (hmoment : ∑ i ∈ S, w i ^ s = moment)
    (hcoeff :
      (S.card : ℝ) * (Complex.normSq b + Complex.normSq c) +
          2 * (conj c * b * moment).re <
        (S.card : ℝ) - 1) :
    ∃ i ∈ S, ∃ j ∈ S, i ≠ j ∧
      (∀ u : ℝ, 0 ≤ u → u ≤ 1 →
        ‖(u : ℂ) ^ m * w i ^ m + a * (u : ℂ) ^ r * w i ^ r +
          b * (u : ℂ) ^ s * w i ^ s + c‖ < 1) ∧
      (∀ u : ℝ, 0 ≤ u → u ≤ 1 →
        ‖(u : ℂ) ^ m * w j ^ m + a * (u : ℂ) ^ r * w j ^ r +
          b * (u : ℂ) ^ s * w j ^ s + c‖ < 1) := by
  have hv : ∀ i ∈ S, Complex.normSq (w i ^ s) ≤ 1 := by
    intro i hi
    have hp : ‖w i‖ ^ s < 1 :=
      pow_lt_one₀ (norm_nonneg (w i)) (hw i hi) (by omega)
    rw [Complex.normSq_eq_norm_sq, norm_pow]
    nlinarith [pow_nonneg (norm_nonneg (w i)) s]
  obtain ⟨i, hiS, j, hjS, hij, hiTail, hjTail⟩ :=
    exists_two_tails_norm_lt_one_of_moment_coeff_budget
      S (fun k => w k ^ s) b c moment hcard hmoment hv hcoeff
  have hiSpoke : ∀ u : ℝ, 0 ≤ u → u ≤ 1 →
      ‖(u : ℂ) ^ m * w i ^ m + a * (u : ℂ) ^ r * w i ^ r +
        b * (u : ℂ) ^ s * w i ^ s + c‖ < 1 := by
    intro u hu0 hu1
    have htailEq : a * w i ^ r + w i ^ m = -(c + b * w i ^ s) := by
      linear_combination hroot i hiS
    have htail : ‖a * w i ^ r + w i ^ m‖ < 1 := by
      rw [htailEq, norm_neg]
      exact hiTail
    exact tetranomialRoot_spoke_norm_lt_one_of_tail
      hs hsr hrm (hroot i hiS) (hw i hiS) hc htail hu0 hu1
  have hjSpoke : ∀ u : ℝ, 0 ≤ u → u ≤ 1 →
      ‖(u : ℂ) ^ m * w j ^ m + a * (u : ℂ) ^ r * w j ^ r +
        b * (u : ℂ) ^ s * w j ^ s + c‖ < 1 := by
    intro u hu0 hu1
    have htailEq : a * w j ^ r + w j ^ m = -(c + b * w j ^ s) := by
      linear_combination hroot j hjS
    have htail : ‖a * w j ^ r + w j ^ m‖ < 1 := by
      rw [htailEq, norm_neg]
      exact hjTail
    exact tetranomialRoot_spoke_norm_lt_one_of_tail
      hs hsr hrm (hroot j hjS) (hw j hjS) hc htail hu0 hu1
  exact ⟨i, hiS, j, hjS, hij, hiSpoke, hjSpoke⟩

/-! ## An exact first-resonance family -/

/-- The first-resonance tetranomial is exactly a product of two binomials. -/
theorem resonantTetranomial_factorization
    (r s : ℕ) (U q w : ℂ) :
    w ^ (r + s) - U * w ^ r + q * w ^ s - U * q =
      (w ^ s - U) * (w ^ r + q) := by
  rw [pow_add]
  ring

/-- Every root of the left binomial has zero lower Abel tail. -/
theorem resonantTetranomial_leftRoot_tail_eq_zero
    {s : ℕ} {U q w : ℂ} (hws : w ^ s = U) :
    -U * q + q * w ^ s = 0 := by
  rw [hws]
  ring

/-- Every left-factor root has a completely safe spoke.  Analytically, when
`s >= 2` the left binomial supplies at least two distinct such roots. -/
theorem resonantTetranomial_leftRoot_spoke_norm_lt_one
    {r s : ℕ} (hs : 1 ≤ s) (hsr : s ≤ r)
    {U q w : ℂ} (hws : w ^ s = U)
    (hw : ‖w‖ < 1) (hUq : ‖U * q‖ < 1) {u : ℝ}
    (hu0 : 0 ≤ u) (hu1 : u ≤ 1) :
    ‖(u : ℂ) ^ (r + s) * w ^ (r + s) +
        (-U) * (u : ℂ) ^ r * w ^ r +
          q * (u : ℂ) ^ s * w ^ s - U * q‖ < 1 := by
  have hroot :
      w ^ (r + s) + (-U) * w ^ r + q * w ^ s + (-U * q) = 0 := by
    rw [pow_add, hws]
    ring
  have htail : (-U) * w ^ r + w ^ (r + s) = 0 := by
    rw [pow_add, hws]
    ring
  have hc : ‖-U * q‖ < 1 := by simpa using hUq
  have htailNorm : ‖(-U) * w ^ r + w ^ (r + s)‖ < 1 := by
    rw [htail, norm_zero]
    norm_num
  simpa [sub_eq_add_neg, add_assoc] using
    tetranomialRoot_spoke_norm_lt_one_of_tail
      hs hsr (Nat.le_add_right r s) hroot hw hc htailNorm hu0 hu1

/-- Exact rational certificate showing that the resonant quintic
`w^5-(1/2)w^3+(4/5)w^2-2/5` is strictly inside the signed L2 region. -/
theorem resonantQuintic_signedCoefficientBudget :
    (5 : ℝ) * ((4 / 5 : ℝ) ^ 2 + (-2 / 5 : ℝ) ^ 2) -
        2 * 2 * ((-2 / 5 : ℝ) * (4 / 5 : ℝ) * (-1 / 2 : ℝ)) <
      4 := by
  norm_num

end ErdosProblems.Erdos1041
