import ExternalVerification1049RationalBaseBarrier.Solution

#print axioms Erdos249257.ExternalVerification1049RationalBaseBarrier.rationalBaseClearedTailQ_succ
#print axioms Erdos249257.ExternalVerification1049RationalBaseBarrier.twoPow_le_rationalBaseForcingNat
#print axioms Erdos249257.ExternalVerification1049RationalBaseBarrier.threeHalves_no_coordinatewiseCorridor
