import Solutions.PalomarCorpus.E1041_01

#print axioms PalomarCorpus.E1041.PaperStatementsA.erdos1041_ani_degree_seven
#print axioms PalomarCorpus.E1041.PaperStatementsAA.all_degree_monic_trinomials_whole
#print axioms PalomarCorpus.E1041.PaperStatementsAA.complete_trinomial
#print axioms PalomarCorpus.E1041.PaperStatementsAE.erdos1041_hausdorff_answer_false
#print axioms PalomarCorpus.E1041.PaperStatementsAE.erdos1041_hausdorff_negation
#print axioms PalomarCorpus.E1041.PaperStatementsH.all_spokes
#print axioms PalomarCorpus.E1041.PaperStructuresAF.erdos1041_counterexample
#print axioms PalomarCorpus.E1041.PaperStructuresAG.erdos1041_counterexample_hausdorff
