import Solutions.ExternalVerification243PaperStatementsE

#print axioms Erdos249257.ExternalVerification243PaperStatementsE.growthDefect_eq_neg_relativeError_add_shiftedCorrection
#print axioms Erdos249257.ExternalVerification243PaperStatementsE.shiftedCorrectionTerm_pos_and_lt_three_div
#print axioms Erdos249257.ExternalVerification243PaperStatementsE.sylvesterTail_shiftedCorrection
