import Solutions.ExternalVerification1049BezoutPluckerJets
#print axioms Erdos249257.ExternalVerification1049BezoutPluckerJets.anchor_det_zero_forces_all_det_zero
#print axioms Erdos249257.ExternalVerification1049BezoutPluckerJets.binary_row_collision_of_anchor_det_zero
#print axioms Erdos249257.ExternalVerification1049BezoutPluckerJets.adjacent_det_zero_forces_all_det_zero
#print axioms Erdos249257.ExternalVerification1049BezoutPluckerJets.zmod_binary_tail_collision_of_two_three_depth
