import Solutions.ExternalVerification257PaperStatementsAF

#print axioms Erdos249257.ExternalVerification257PaperStatementsAF.card_divisors_le_divisorSubpowerConst_mul_rpow
#print axioms Erdos249257.ExternalVerification257PaperStatementsAF.card_divisors_pow_le_divisorSubpowerConst_pow_mul
#print axioms Erdos249257.ExternalVerification257PaperStatementsAF.divInt_le_nextDyadic_iff_excess_nonpos
#print axioms Erdos249257.ExternalVerification257PaperStatementsAF.dyadicResidual_denominator_sandwich
