import Solutions.ExternalVerification1041CollinearChord

#print axioms Erdos249257.ExternalVerification1041CollinearChord.CollinearScaleCriticalFamily.exists_erdos1041_chord
#print axioms Erdos249257.ExternalVerification1041CollinearChord.CollinearScaleCriticalFamily.exists_diameter_chord
#print axioms Erdos249257.ExternalVerification1041CollinearChord.polynomial_straightSegment_solution_of_collinearPeak
