import Solutions.ExternalVerification257PaperStructuresCJ

#print axioms Erdos249257.ExternalVerification257PaperStructuresCJ.above_newSum_le_capacity_iff
#print axioms Erdos249257.ExternalVerification257PaperStructuresCJ.below_newSum_le_capacity
#print axioms Erdos249257.ExternalVerification257PaperStructuresCJ.nextRemainder_trichotomy
#print axioms Erdos249257.ExternalVerification257PaperStructuresCJ.prefixChoice_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCJ.prefixRemainder_eq_capacity_sub_choice
