import Solutions.ExternalVerification257PaperStatementsAI

#print axioms Erdos249257.ExternalVerification257PaperStatementsAI.paper_forced_greedy_low_ranks
#print axioms Erdos249257.ExternalVerification257PaperStatementsAI.paper_forced_greedy_unique_support_and_criterion
#print axioms Erdos249257.ExternalVerification257PaperStatementsAI.paper_rung_finite_decision
