import Solutions.ExternalVerification257PaperStructuresAZ

#print axioms Erdos249257.ExternalVerification257PaperStructuresAZ.paper_dynamics
#print axioms Erdos249257.ExternalVerification257PaperStructuresAZ.paper_greedySupport_greedy_rule
#print axioms Erdos249257.ExternalVerification257PaperStructuresAZ.paper_greedySupport_isRowLower
#print axioms Erdos249257.ExternalVerification257PaperStructuresAZ.paper_greedySupport_mem
#print axioms Erdos249257.ExternalVerification257PaperStructuresAZ.paper_greedy_step
