import Solutions.ExternalVerification257PaperStatementsAE

#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.affineBinaryOrbit_mod_twoPow_eq
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.balancedPulse_endpoint_fanout
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.balancedPulse_label_card_lower_bound
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.balancedPulse_no_autonomous_decoder
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.balancedPulse_weighted_pair
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.binaryCoeffSeries_rational_iff_exists_temperedBinaryOrbit
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.binaryCoeffTail_div_pow_tendsto_zero
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.binaryCoeffTail_le
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.binaryCoeffTail_nonneg
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.not_irrational_binaryCoeffSeries_iff_exists_temperedBinaryOrbit
#print axioms Erdos249257.ExternalVerification257PaperStatementsAE.temperedBinaryOrbit_eq_scaledTail
