import Solutions.ExternalVerification1041FirstMergeCriticalValueSeparation

#print axioms Erdos249257.ExternalVerification1041FirstMergeCriticalValueSeparation.firstMerge_exact_convenient_thresholds
#print axioms Erdos249257.ExternalVerification1041FirstMergeCriticalValueSeparation.firstMerge_length_lt_two_of_squared_bound
