import Solutions.ExternalVerification251KernelDenominatorFloor

#print axioms Erdos249257.ExternalVerification251KernelDenominatorFloor.cert_10000
#print axioms Erdos249257.ExternalVerification251KernelDenominatorFloor.den_bound_of_certCheck
#print axioms Erdos249257.ExternalVerification251KernelDenominatorFloor.kernel_denominator_floor
#print axioms Erdos249257.ExternalVerification251KernelDenominatorFloor.kernel_denominator_floor_primeGap
