import Solutions.ExternalVerification249PaperStatementsAO

#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.four_thirds_tsum_eighth_pow_tail
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.mersenneRemainderTail_le
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.mersenneRemainder_identity_and_bound
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.mersenne_dvd_of_dvd
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.one_sub_half_pow_ge
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.paperNumerator_coeff_eq_gcd_divisor_sum
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.paperNumerator_coeff_eq_zero
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.paperNumerator_coeff_pos
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.paperNumerator_eq_gcdWordForm
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.paperNumerator_eval_two
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.paperNumerator_eval_two_primeSubsetForm
#print axioms Erdos249257.ExternalVerification249PaperStatementsAO.tsum_eighth_pow_tail
