import Solutions.ExternalVerification257PaperStatementsJ

#print axioms Erdos249257.ExternalVerification257PaperStatementsJ.paper_forced_greedy_unique_support_and_criterion
#print axioms Erdos249257.ExternalVerification257PaperStatementsJ.paper_rung_finite_decision
