import Solutions.ExternalVerification257ScaledGreedyTrap
#print axioms Erdos249257.ExternalVerification257ScaledGreedyTrap.mersenneAchievementSet_eq_scaledGreedyTrap
#print axioms Erdos249257.ExternalVerification257ScaledGreedyTrap.scaledGreedyRemainder_tendsto_atTop_of_not_mem
#print axioms Erdos249257.ExternalVerification257ScaledGreedyTrap.mem_mersenneAchievementSet_iff_scaledRemainder_cofinallyBounded
#print axioms Erdos249257.ExternalVerification257ScaledGreedyTrap.rat_mem_mersenneAchievementSet_iff_scaledLowerBranchCofinally
#print axioms Erdos249257.ExternalVerification257ScaledGreedyTrap.one_div_twentyOne_mem_iff_scaledLowerBranchCofinally
#print axioms Erdos249257.ExternalVerification257ScaledGreedyTrap.one_div_twentyOne_mem_iff_scaledRemainder_cofinallyBounded
