import Solutions.ExternalVerification243PaperStatementsI

#print axioms Erdos249257.ExternalVerification243PaperStatementsI.canonical_negativeError_limsup_gt_one
#print axioms Erdos249257.ExternalVerification243PaperStatementsI.maximal_gap_limsup_eq_inv_sigma
