import Solutions.ExternalVerification243WeightedRecordExcess
#print axioms Erdos249257.ExternalVerification243WeightedRecordExcess.weighted_record_excess
#print axioms Erdos249257.ExternalVerification243WeightedRecordExcess.weighted_growth_record_excess
