import ExternalVerification249RankOneSharpFloor.Solution

#print axioms Erdos249257.ExternalVerification249RankOneSharpFloor.rankOneSubrankQuotient_eq_one_five_iff
#print axioms Erdos249257.ExternalVerification249RankOneSharpFloor.rankOneSubrankQuotient_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms Erdos249257.ExternalVerification249RankOneSharpFloor.rankOneSubrankQuotient_sub_theta_two_gt_one_div_sixteen
#print axioms Erdos249257.ExternalVerification249RankOneSharpFloor.not_forall_rankOneSubrankQuotient_sub_theta_two_gt_one_div_fifteen
#print axioms Erdos249257.ExternalVerification249RankOneSharpFloor.positive_direct_sum_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms Erdos249257.ExternalVerification249RankOneSharpFloor.primitive_form_abs_gt_twentyOne_div_threeTwenty
