import Solutions.ExternalVerification249MobiusMersenneLadderStructure

#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.mobiusMersenneTheta_no_linearRecurrence
#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.mobiusMersenneTheta_no_linearRecurrence_of_eventually
#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.mobiusMersenneTheta_strict_logConcave
#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.mobiusMersenneTheta_hankel_two_neg
#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.mobiusMersenneLambertRung_eq
#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.lambertRung_shifted_hankelDet_eq_zero
#print axioms Erdos249257.ExternalVerification249MobiusMersenneLadderStructure.mobiusMersenneTheta_ne_mobiusMersenneLambertRung
