import Solutions.ExternalVerification249PaperStatementsAG

#print axioms Erdos249257.ExternalVerification249PaperStatementsAG.exists_later_arbitrarily_many_separated_parityCoboundaryWeight_carry_pairs
#print axioms Erdos249257.ExternalVerification249PaperStatementsAG.exists_totientParity_arbitrarilyManySeparatedCarry_rational_countermodel
#print axioms Erdos249257.ExternalVerification249PaperStatementsAG.parityCoboundaryWeight_le_self
#print axioms Erdos249257.ExternalVerification249PaperStatementsAG.parityCoboundaryWeight_le_six
#print axioms Erdos249257.ExternalVerification249PaperStatementsAG.parityCoboundaryWeight_mod_two_eq_totient
#print axioms Erdos249257.ExternalVerification249PaperStatementsAG.tsum_parityCoboundaryWeight_eq_three_halves
