import Solutions.ExternalVerification249PaperStatementsBG

#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.abs_mobiusMersenneTheta_sub_prefix_le
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.mobiusMersenneTheta_ge_alpha
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.mobiusMersenneTheta_lt_one
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.mobiusMersenneTheta_one_and_two
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.positive_direct_sum_sub_theta_two_gt
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.primitive_form_abs_gt
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.rankOneSubrankQuotient_one_five_sub_theta_two_lt_one_div_fifteen
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.rankOneSubrankQuotient_sub_theta_two_gt
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.theta_hankel_det_neg
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.theta_hankel_two_neg
#print axioms Erdos249257.ExternalVerification249PaperStatementsBG.theta_strict_logConcave
