import Solutions.ExternalVerification257PaperStructuresO

#print axioms Erdos249257.ExternalVerification257PaperStructuresO.overlappingMidpointReturns_twoPow_le_realBound
#print axioms Erdos249257.ExternalVerification257PaperStructuresO.overlappingReverseCarryWords_carryDifference_eq_twoPow_mul_odd
#print axioms Erdos249257.ExternalVerification257PaperStructuresO.overlappingReverseCarryWords_twoPow_le_realBound
