import Solutions.ExternalVerification257PaperStructuresCD

#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.half_mem_mersenneAchievementSet_iff_unboundedUpperOrMiddle
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.half_mem_mersenneAchievementSet_of_largestSkipLateStepSocket
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.half_mem_mersenneAchievementSet_of_middleProducerCardEscape
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.half_mem_mersenneAchievementSet_of_middleProducerRowEscape
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.half_mem_mersenneAchievementSet_of_upperResetDyadicBandEscape
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.middleProducer_allRight_forces_rational_skip
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresCD.wordPulse_le
