import Solutions.PalomarCorpus.E249_32

#print axioms PalomarCorpus.E249.CarryRankFrontier.carryShift_dvd_iff_tailDiff_mem_int
#print axioms PalomarCorpus.E249.CarryRankFrontier.finrank_canonicalCarryKernel_ge_of_certificate
#print axioms PalomarCorpus.E249.CarryRankFrontier.not_irrational_totientSeries_implies_mod_period_and_unbounded_rank
#print axioms PalomarCorpus.E249.CarryRankFrontier.not_irrational_totientSeries_implies_unbounded_carryRank_unconditional
#print axioms PalomarCorpus.E249.CarryRankFrontier.totient_carryKernel_diff
#print axioms PalomarCorpus.E249.DyadicTotientKernel.dyadicTotientKernelOddCoreBasisAndFiniteRanks
#print axioms PalomarCorpus.E249.FareyWindowExclusion.farey_int_exclusion
#print axioms PalomarCorpus.E249.FullDepthRayAmplifier.apFullDepthEscape_iff_irrational
#print axioms PalomarCorpus.E249.FullDepthRayAmplifier.cofinalFullDepthKillSupply_iff_irrational
#print axioms PalomarCorpus.E249.FullDepthRayAmplifier.cofinalFullDepthKillSupply_iff_periodMultipleKillSupply
#print axioms PalomarCorpus.E249.FullDepthRayAmplifier.eventually_twoSyndetic_fullDepthKillMultipliers_of_seed
#print axioms PalomarCorpus.E249.FullDepthRayAmplifier.exists_fullDepthKill_on_ray_iff_shift_notMem_int
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.lambertRung_shifted_hankelDet_eq_zero
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.mobiusMersenneLambertRung_eq
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.mobiusMersenneTheta_hankel_two_neg
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.mobiusMersenneTheta_ne_mobiusMersenneLambertRung
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.mobiusMersenneTheta_no_linearRecurrence
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.mobiusMersenneTheta_no_linearRecurrence_of_eventually
#print axioms PalomarCorpus.E249.MobiusMersenneLadderStructure.mobiusMersenneTheta_strict_logConcave
