import Solutions.ExternalVerification243PaperStructuresT

#print axioms Erdos249257.ExternalVerification243PaperStructuresT.R_delta_sub_amp_tendsto_zero
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.R_le_of_u_le
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.Rdelta_bddAbove_iff_amp
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.amp_bddAbove_iff_sylvester
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.coprimeMultiplier_cofinal
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.criticalRate
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.criticalRate_counterexample
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.delta_negPart_comparison
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.largePrime_coprimeMultiplier
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.primeBlock_supply
#print axioms Erdos249257.ExternalVerification243PaperStructuresT.recordAmplified
