import Solutions.ExternalVerification257PaperStatementsAQ

#print axioms Erdos249257.ExternalVerification257PaperStatementsAQ.half_lt_tsum_negativeMobius
#print axioms Erdos249257.ExternalVerification257PaperStatementsAQ.paper_first_positiveMobius_tail_term
#print axioms Erdos249257.ExternalVerification257PaperStatementsAQ.paper_mobius_support_overshoots_half
#print axioms Erdos249257.ExternalVerification257PaperStatementsAQ.tsum_negativeMobius_eq_half_add_positiveMobiusTail
