import Solutions.ExternalVerification257LiteralWeightedCover
#print axioms Erdos249257.ExternalVerification257LiteralWeightedCover.exists_weighted_not_strengthened_host
#print axioms Erdos249257.ExternalVerification257LiteralWeightedCover.exists_weighted_obstruction_with_mixed_heredity
