import Solutions.PalomarCorpus.E257_23

#print axioms PalomarCorpus.E257.PaperStatementsAC.dyadicBandEscape_iff_exists_critical
#print axioms PalomarCorpus.E257.PaperStatementsAC.exists_criticalDyadicBandIndex
#print axioms PalomarCorpus.E257.PaperStructuresBZ.exists_seamWord_minimal_above
#print axioms PalomarCorpus.E257.PaperStructuresBZ.integerGreedyBits_length
#print axioms PalomarCorpus.E257.PaperStructuresBZ.paper_critical_band_index_collapse
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamAboveWord_minimal
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamAboveWord_strict
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamAdjacentCut_below_admissible
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamAdjacentCut_below_maximal
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamPerturbedFamily_gap_pos
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamPerturbedFamily_oldSum_injective
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamPerturbedFamily_separated
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamUpperResetCriticalBandEscape_iff
#print axioms PalomarCorpus.E257.PaperStructuresBZ.seamWeights_length_eq
#print axioms PalomarCorpus.E257.PaperStructuresBZ.wordPulse_le
