import Solutions.ExternalVerification269PaperStatementsA

#print axioms Erdos249257.ExternalVerification269PaperStatementsA.actual_cubic_no_crossing_strips
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.actual_weighted_strip_decomposition
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.admissible_modular_minors
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.clearingCondition_iff_max
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.dyadicBlockBase235_cases
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.dyadicBlockBase235_mem_interval
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.dyadicInternalPower_exponent_unique
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.exists_dyadicInternalPower_iff_log_succ
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.fixed_base_recoding_whole
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.literal_triangle_whole
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.log_dyadic_succ_eq_of_no_internalPower
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.paper_jump_count
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.paper_two_by_two_fixture
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.paper_uniform_rank_and_nonseparation
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.radix_eq_height_ratio
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.threePrimeHeight_dyadicBlock_succ
#print axioms Erdos249257.ExternalVerification269PaperStatementsA.weighted_shift_whole
