import Solutions.PalomarCorpus.E243_11

#print axioms PalomarCorpus.E243.RecordAmplifiedCancellationVisibility.recordAmplified_error_after_cancellation
#print axioms PalomarCorpus.E243.RecordIncrementBarrier.recordIncrementOne_sylvesterNext_eventually
#print axioms PalomarCorpus.E243.RepairEntropy.eventually_recoveryPayment_eq_one_of_fixedLength
#print axioms PalomarCorpus.E243.RepairEntropy.repairedFamily_recovery_energy_divisionFree
#print axioms PalomarCorpus.E243.RepairEntropy.repaired_card_bound_of_independent
#print axioms PalomarCorpus.E243.SaturatedSquareTransport.legendre_defect_forces_nonsquare_content
#print axioms PalomarCorpus.E243.SaturatedSquareTransport.saturated_square_transport_raw
#print axioms PalomarCorpus.E243.SlowRiseBarrier.no_slowRise_reducedTail
#print axioms PalomarCorpus.E243.SummableNegativeMassRigidity.canonical_finite_negative_mass
#print axioms PalomarCorpus.E243.SummableNegativeMassRigidity.finite_negative_mass_scalar
#print axioms PalomarCorpus.E243.SummableNegativeMassRigidity.summableNegativeMass_completeRigidity
#print axioms PalomarCorpus.E243.WeightedRecordExcess.weighted_growth_record_excess
#print axioms PalomarCorpus.E243.WeightedRecordExcess.weighted_record_excess
