import Solutions.ExternalVerification257PaperStatementsAH

#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.halfTwoChannelCap_lt_mersenneTail
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.irrational_erdosBorweinMersenneConstant
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneGap_pos
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneTail_eq_weight_add
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneTail_le_two_mul_weight
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneTail_lt_weight
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.two_mul_mersenneWeight_succ_lt
