import Solutions.ExternalVerification257PaperStatementsAH

#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.greedy_survives_of_mem_mersenneAchievementSet
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.halfTwoChannelCap_lt_mersenneTail
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.half_mem_mersenneAchievementSet_of_secondChannelSeparation
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.half_mem_mersenneAchievementSet_of_secondChannelSeparationRat_from_seven
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.half_mem_mersenneAchievementSet_of_skipped_dyadicCap
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.half_mem_mersenneAchievementSet_of_skipped_twoChannelCap
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.irrational_erdosBorweinMersenneConstant
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mem_mersenneAchievementSet_iff_greedy_survival
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mem_mersenneAchievementSet_of_greedySkippedSupport_infinite
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mem_mersenneAchievementSet_of_greedy_survival
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneGap_pos
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneTail_eq_weight_add
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneTail_le_two_mul_weight
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.mersenneTail_lt_weight
#print axioms Erdos249257.ExternalVerification257PaperStatementsAH.two_mul_mersenneWeight_succ_lt
