import Solutions.ExternalVerification243PaperStatementsD

#print axioms Erdos249257.ExternalVerification243PaperStatementsD.energy_window_real_bound
#print axioms Erdos249257.ExternalVerification243PaperStatementsD.exists_avoiding_in_window
#print axioms Erdos249257.ExternalVerification243PaperStatementsD.exists_slow_rise_avoiding_sequence
#print axioms Erdos249257.ExternalVerification243PaperStatementsD.exists_sparse_prime_coprime_sequence
