import Solutions.ExternalVerification1041PaperStatementsAC

#print axioms Erdos249257.ExternalVerification1041PaperStatementsAC.circle_slice_packing
#print axioms Erdos249257.ExternalVerification1041PaperStatementsAC.circle_slice_packing_abstract
#print axioms Erdos249257.ExternalVerification1041PaperStatementsAC.dual_arity_floor_abstract
