import Solutions.ExternalVerification243RecordAmplifiedCancellationVisibility

#print axioms Erdos249257.ExternalVerification243RecordAmplifiedCancellationVisibility.recordAmplified_error_after_cancellation
