import Solutions.ExternalVerification257PaperStatementsAL

#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.finite_boolSupport_ne_half
#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.paper_coeffTail_le_index_add_two
#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.paper_zero_run_le_eps_logb
#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.paper_zero_run_le_of_mem
#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.supportCoeff_boundaryPair_unitDrop_at_double
#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.supportCoeff_extend_true_eq_false_add_one_at_double
#print axioms Erdos249257.ExternalVerification257PaperStatementsAL.supportCoeff_insert_divisor
