import Solutions.ExternalVerification1041PaperStatementsE

#print axioms Erdos249257.ExternalVerification1041PaperStatementsE.collinearDiameterBound_sharpConstant
#print axioms Erdos249257.ExternalVerification1041PaperStatementsE.exists_collinear_factorisation
#print axioms Erdos249257.ExternalVerification1041PaperStatementsE.sharpConstant_le_of_collinearDiameterBound
#print axioms Erdos249257.ExternalVerification1041PaperStatementsE.sharp_collinear_root_diameter
#print axioms Erdos249257.ExternalVerification1041PaperStatementsE.sharp_collinear_root_diameter_monic
