import Solutions.ExternalVerification249PaperStatementsBD

#print axioms Erdos249257.ExternalVerification249PaperStatementsBD.composite_dilation_divisor_count
#print axioms Erdos249257.ExternalVerification249PaperStatementsBD.composite_dilation_divisor_count_prime_support
#print axioms Erdos249257.ExternalVerification249PaperStatementsBD.lambert_support_series
#print axioms Erdos249257.ExternalVerification249PaperStatementsBD.lambert_support_series_restricted
