import Solutions.ExternalVerification257PaperStatementsAK

#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.localMersenneHalfTarget_lower_word_eq_greedy_and_remainder_eq
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.localMersenneWeightsFrom_gapDominates
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.localMersenneWeights_gapDominates_even
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.localMersenneWeights_gapDominates_odd
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_floor_quotient_geometric_sum
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_next_floor_quotient
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_next_floor_quotient_no_fixed_point
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_next_quotient_sum
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_repair_integer_eq_endpoint_defect
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_signed_endpoint_defect_succ
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_signed_endpoint_recurrence
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.paper_successor_remainders_fourteen_through_thirtyone
#print axioms Erdos249257.ExternalVerification257PaperStatementsAK.remainder_lt_gap_iff_eq_integerGreedyBits
