import Solutions.PalomarCorpus.E257_15

#print axioms PalomarCorpus.E257.PaperStatementsAH.irrational_erdosBorweinMersenneConstant
#print axioms PalomarCorpus.E257.PaperStatementsAJ.tsum_moebius_div_two_pow_sub_one_eq_half
#print axioms PalomarCorpus.E257.PaperStatementsAQ.half_lt_tsum_negativeMobius
#print axioms PalomarCorpus.E257.PaperStatementsAQ.tsum_negativeMobius_eq_half_add_positiveMobiusTail
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms PalomarCorpus.E257.PaperStatementsG.half_mem_mersenneAchievementSet_iff_no_lastHalfGreedySkip
#print axioms PalomarCorpus.E257.PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_cofinalTerminalFalse
#print axioms PalomarCorpus.E257.PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_exists_unboundedSkippedRanksAlong
#print axioms PalomarCorpus.E257.PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_not_seamGreedyEventuallyRight
#print axioms PalomarCorpus.E257.PaperStructuresBJ.half_mem_mersenneAchievementSet_iff_unboundedTerminalFalse
#print axioms PalomarCorpus.E257.PaperStructuresBJ.unboundedTerminalFalse_iff_greedyMersenneSkippedSupport_infinite
