import Solutions.PalomarCorpus.E257_15

#print axioms PalomarCorpus.E257.PaperStructuresBN.exists_seamWord_minimal_above
#print axioms PalomarCorpus.E257.PaperStructuresBN.integerGreedyBits_length
#print axioms PalomarCorpus.E257.PaperStructuresBN.paper_final_middle_cell_at_least_neg_two
#print axioms PalomarCorpus.E257.PaperStructuresBN.paper_final_middle_cell_ne_neg_three
#print axioms PalomarCorpus.E257.PaperStructuresBN.paper_final_middle_cell_remaining_cells
#print axioms PalomarCorpus.E257.PaperStructuresBN.paper_perturbed_nextRemainder_three_branches
#print axioms PalomarCorpus.E257.PaperStructuresBN.paper_perturbed_order_preservation
#print axioms PalomarCorpus.E257.PaperStructuresBN.paper_perturbed_prefixChoice_maximal
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamAboveWord_minimal
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamAboveWord_strict
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamAdjacentCut_below_admissible
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamAdjacentCut_below_maximal
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamPerturbedFamily_gap_pos
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamPerturbedFamily_oldSum_injective
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamPerturbedFamily_separated
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamUpperResetDyadicBandEscape_through_thirty
#print axioms PalomarCorpus.E257.PaperStructuresBN.seamWeights_length_eq
#print axioms PalomarCorpus.E257.PaperStructuresBN.wordPulse_le
