import Solutions.ExternalVerification1041CyclicTrinomialFiber
#print axioms Erdos249257.ExternalVerification1041CyclicTrinomialFiber.trinomialRoot_spoke_factorization
#print axioms Erdos249257.ExternalVerification1041CyclicTrinomialFiber.trinomialRoot_spoke_norm_lt_one_of_norm_lt_one
#print axioms Erdos249257.ExternalVerification1041CyclicTrinomialFiber.cyclicTrinomial_two_short_fiber_displacements
