import Solutions.PalomarCorpus.E257_34

#print axioms PalomarCorpus.E257.PaperStatementsAD.localPrefixQuotient_succ
#print axioms PalomarCorpus.E257.PaperStatementsAD.paper_finite_sum_inv_odd_den_odd
#print axioms PalomarCorpus.E257.PaperStatementsAD.paper_finite_sum_inv_odd_ne_half
#print axioms PalomarCorpus.E257.PaperStatementsAD.two_mem_of_exact_localMersenneQuotient
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_floor_quotient_geometric_sum
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_next_floor_quotient
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_next_floor_quotient_no_fixed_point
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_next_quotient_sum
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_repair_integer_eq_endpoint_defect
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_signed_endpoint_defect_succ
#print axioms PalomarCorpus.E257.PaperStatementsAK.paper_signed_endpoint_recurrence
#print axioms PalomarCorpus.E257.PaperStatementsAN.paper_endpoint_term_counts_divisors
#print axioms PalomarCorpus.E257.PaperStatementsAN.paper_finiteErdosSum_den_odd
#print axioms PalomarCorpus.E257.PaperStatementsAN.paper_finite_support_series_ne_half
#print axioms PalomarCorpus.E257.PaperStatementsAN.paper_half_representing_support_is_infinite
#print axioms PalomarCorpus.E257.PaperStatementsAR.abs_localMersennePrefixValue_sub_half_le
#print axioms PalomarCorpus.E257.PaperStatementsAR.exists_exactRowStrictUpperExtension_two_mul_sub_one_of_exact_below
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_one_lt_upperWindow_of_exact_below
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_capacity_band_exclusion
#print axioms PalomarCorpus.E257.PaperStatementsAS.paper_sharper_additive_estimate
#print axioms PalomarCorpus.E257.PaperStatementsAS.paper_unconditional_bound_one_extra_bit
#print axioms PalomarCorpus.E257.PaperStructuresAY.localMersenneWeightsFrom_gapDominates
#print axioms PalomarCorpus.E257.PaperStructuresAY.localMersenneWeights_gapDominates_even
