import Solutions.PalomarCorpus.E243t

#print axioms PalomarCorpus.E243.PaperStructuresT.R_delta_sub_amp_tendsto_zero
#print axioms PalomarCorpus.E243.PaperStructuresT.R_le_of_u_le
#print axioms PalomarCorpus.E243.PaperStructuresT.Rdelta_bddAbove_iff_amp
#print axioms PalomarCorpus.E243.PaperStructuresT.amp_bddAbove_iff_sylvester
#print axioms PalomarCorpus.E243.PaperStructuresT.coprimeMultiplier_cofinal
#print axioms PalomarCorpus.E243.PaperStructuresT.criticalRate
#print axioms PalomarCorpus.E243.PaperStructuresT.criticalRate_counterexample
#print axioms PalomarCorpus.E243.PaperStructuresT.delta_negPart_comparison
#print axioms PalomarCorpus.E243.PaperStructuresT.largePrime_coprimeMultiplier
#print axioms PalomarCorpus.E243.PaperStructuresT.primeBlock_supply
#print axioms PalomarCorpus.E243.PaperStructuresT.recordAmplified
