import Solutions.ExternalVerification251BoundedPerturbationCountermodel

#print axioms Erdos249257.ExternalVerification251BoundedPerturbationCountermodel.not_irrational_bounded_perturbation_primeGap
#print axioms Erdos249257.ExternalVerification251BoundedPerturbationCountermodel.exists_rational_bounded_perturbation_primeGap
#print axioms Erdos249257.ExternalVerification251BoundedPerturbationCountermodel.perturbed_gap_bounds
#print axioms Erdos249257.ExternalVerification251BoundedPerturbationCountermodel.exists_bounded_perturbation
#print axioms Erdos249257.ExternalVerification251BoundedPerturbationCountermodel.hasSum_binaryDigit
