import Solutions.ExternalVerification251FreePairEquivalence

#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.irrational_primeGap_tsum_iff_cofinalFreePairNonintegral
#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.irrational_initial_iff_cofinalFreePairNonintegral
#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.cofinalFreePairNonintegral_iff_cofinalNonintegralTailShifts
#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.exists_free_pair_lattice
#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.free_pair_integral_iff_modEq
#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.primeGapRealTail_recurrence
#print axioms Erdos249257.ExternalVerification251FreePairEquivalence.primeGapRealTail_zero
