import Solutions.PalomarCorpus.E249al

#print axioms PalomarCorpus.E249.PaperStatementsAL.basePower_dilation_not_universal
#print axioms PalomarCorpus.E249.PaperStatementsAL.digit_block
#print axioms PalomarCorpus.E249.PaperStatementsAL.exists_irrational_basePower_bounded_away
#print axioms PalomarCorpus.E249.PaperStatementsAL.fract_mem_Icc_of_no_three_equal
#print axioms PalomarCorpus.E249.PaperStatementsAL.fract_two_pow_mul_xi_mem_Icc
#print axioms PalomarCorpus.E249.PaperStatementsAL.irrational_tail_zero
#print axioms PalomarCorpus.E249.PaperStatementsAL.irrational_xi
#print axioms PalomarCorpus.E249.PaperStatementsAL.no_three_consecutive_equal
#print axioms PalomarCorpus.E249.PaperStatementsAL.not_approaches_int
#print axioms PalomarCorpus.E249.PaperStatementsAL.not_eventually_periodic
#print axioms PalomarCorpus.E249.PaperStatementsAL.not_near_integer_along_powers_of_two
#print axioms PalomarCorpus.E249.PaperStatementsAL.one_div_eight_le_abs_sub_int
#print axioms PalomarCorpus.E249.PaperStatementsAL.one_div_eight_le_dist_xi
#print axioms PalomarCorpus.E249.PaperStatementsAL.strict_lower_bound_needed
#print axioms PalomarCorpus.E249.PaperStatementsAL.tail_mem_Icc
#print axioms PalomarCorpus.E249.PaperStatementsAL.upper_bound_needed_for_every_q
