import Solutions.ExternalVerification257PaperStatementsD

#print axioms Erdos249257.ExternalVerification257PaperStatementsD.cofinalPositiveHalfGreedySkips_iff_half_mem
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.greedyHalf_mem_nextMersenneDyadicSliver_iff_excess
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.greedy_half_infinite_of_cofinalStripReturn
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.greedy_half_infinite_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.greedy_half_infinite_of_mobiusCenteredHalfCarry_upperBound
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.greedy_half_of_cofinal_upper_carry
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.greedy_mobiusCenteredHalfCarry_nonneg
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.half_mem_iff_every_actual_skip_survives
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.half_mem_mersenneAchievementSet_of_positiveHalfGreedySkips
#print axioms Erdos249257.ExternalVerification257PaperStatementsD.paper_greedy_survival
