import Solutions.PalomarCorpus.E249_26

#print axioms PalomarCorpus.E249.PaperStatementsAG.exists_later_arbitrarily_many_separated_parityCoboundaryWeight_carry_pairs
#print axioms PalomarCorpus.E249.PaperStatementsAG.parityCoboundaryWeight_le_self
#print axioms PalomarCorpus.E249.PaperStatementsAG.parityCoboundaryWeight_le_six
#print axioms PalomarCorpus.E249.PaperStatementsAG.parityCoboundaryWeight_mod_two_eq_totient
#print axioms PalomarCorpus.E249.PaperStatementsAJ.complementDenominator_dvd_scalar
#print axioms PalomarCorpus.E249.PaperStatementsAY.inversePhaseGauge_locks_row_and_preserves_minor
#print axioms PalomarCorpus.E249.PaperStatementsBB.canonicalTotientKernelFamily_independent_card_and_span
#print axioms PalomarCorpus.E249.PaperStatementsBH.rationalControl_periodic_with_unbounded_carry_rank
#print axioms PalomarCorpus.E249.PaperStatementsBH.rationality_gives_mod_period_and_unbounded_rank
#print axioms PalomarCorpus.E249.PaperStatementsBJ.rationalValue_integral_carry_and_rank_floor
