import Solutions.ExternalVerification257PaperStatementsN

#print axioms Erdos249257.ExternalVerification257PaperStatementsN.approx_orbit_induction
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.fatal_absorbing
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_cpgs_equiv
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_effective_horizon_test
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_eta_eq_coeffTail_sub_carry
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_eta_hasRationalValue
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_eventual_nonnegative_margin_equivalence
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_frozen_margin_limit_pos_iff
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_frozen_margin_normalised_monotone
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_frozen_margin_normalised_tendsto
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_frozen_margin_normalised_value
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_greedyHalfRemainder_ne_dyadicCap
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_halfGreedyPrefixSupport_eq_greedy_inter_Icc
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_no_ties
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_no_ties_skip
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_no_ties_take
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_one_orbit_stability
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_one_sided_finite_decision_boundary
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.paper_terminal_strip_equiv
#print axioms Erdos249257.ExternalVerification257PaperStatementsN.tailGreedyRemainder_mersenne
