import Solutions.ExternalVerification257PaperStatementsAU

#print axioms Erdos249257.ExternalVerification257PaperStatementsAU.binaryCoeffTail_supportCoeff_le_two_sqrt_add_four
#print axioms Erdos249257.ExternalVerification257PaperStatementsAU.erdosSupportSeries_rational_iff_exists_temperedCarry
#print axioms Erdos249257.ExternalVerification257PaperStatementsAU.erdosSupportSeries_two_eq_binaryCoeffSeries
#print axioms Erdos249257.ExternalVerification257PaperStatementsAU.mobius_supportCoeff_boolean
#print axioms Erdos249257.ExternalVerification257PaperStatementsAU.mobius_supportCoeff_eq_one_iff
#print axioms Erdos249257.ExternalVerification257PaperStatementsAU.moebius_mul_supportCoeffAF
