import Solutions.PalomarCorpus.E1049_07

#print axioms PalomarCorpus.E1049.ArchimedeanCap.archimedean_cap
#print axioms PalomarCorpus.E1049.BezoutPluckerJets.adjacent_det_zero_forces_all_det_zero
#print axioms PalomarCorpus.E1049.BezoutPluckerJets.anchor_det_zero_forces_all_det_zero
#print axioms PalomarCorpus.E1049.BezoutPluckerJets.binary_row_collision_of_anchor_det_zero
#print axioms PalomarCorpus.E1049.BezoutPluckerJets.zmod_binary_tail_collision_of_two_three_depth
#print axioms PalomarCorpus.E1049.HermitePadeNoGo.hpClearedGap_eq_zero_iff
#print axioms PalomarCorpus.E1049.HermitePadeNoGo.hpClearedGap_expansion
#print axioms PalomarCorpus.E1049.HermitePadeNoGo.hpClearedGap_nonpos
#print axioms PalomarCorpus.E1049.HermitePadeNoGo.rectangular_hp_threshold_eq_classical_iff
#print axioms PalomarCorpus.E1049.HermitePadeNoGo.rectangular_hp_threshold_le_classical
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.integerLinearForm_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.primePowerSupportedOneRow_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.primeSupportedOneRow_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.primeSupportedTwoSelector_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.rationalTwoSelector_notBothTendstoZero
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.twoSelector_detHeightDecay_tradeoff
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.twoSelector_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.twoSelector_unimodularHeightDecay_tradeoff
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.zeroDenominatorCoordinates_binaryCollision
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.eightyOneTwoHundredths_lt_threeHalves_log_ratio
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.threeHalves_outside_bundschuhVaananenHeightRegion
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.threeHalves_outside_zudilinHeightRegion
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.threeHalves_zudilin_power_obstruction
