import ErdosProblems.Erdos251.SparseIntervalR8
import Mathlib.Logic.Function.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Basic

/-!
# Ambient sparse rationalisation: the actual infinite coefficient word

This module discharges the ambient extension
and all-index congruence obligations left in SparseIntervalR8. The polylogarithmic
rate is separate; it is not inferred from upper Banach density zero.

Pinned Mathlib 5e932f97dd25535344f80f9dd8da3aab83df0fe6:
* Logic/Function/Basic.lean: Function.extend, Injective.extend_apply,
  Function.extend_apply'.
* Topology/Algebra/InfiniteSum/Basic.lean: hasSum_extend_zero (generated by
  to_additive from hasProd_extend_one), HasSum.congr.
* Algebra/BigOperators/Group/Finset/Basic.lean: sum_subset, sum_image.
* Order/Filter/AtTopBot/Basic.lean: eventually_atTop.
Nat.find_spec / Nat.find_min' are inherited core APIs.
-/

noncomputable section
open Filter Topology Finset

namespace ErdosProblems.Erdos251.PaperR9.SparseAmbient
open PaperR8.SparseSchedule

/-- Zero-extension of an indexed digit word along the chosen support. -/
def ambient (c d : ℕ → ℕ) : ℕ → ℕ := Function.extend c d 0

theorem ambient_at (c d : ℕ → ℕ) (hc : Function.Injective c) (j : ℕ) :
    ambient c d (c j) = d j := hc.extend_apply d 0 j

theorem ambient_off (c d : ℕ → ℕ) {n : ℕ} (hn : n ∉ Set.range c) :
    ambient c d n = 0 := Function.extend_apply' d (0 : ℕ → ℕ) n hn

theorem ambient_support (c d : ℕ → ℕ) {n : ℕ} (hn : ambient c d n ≠ 0) :
    n ∈ Set.range c := by
  by_contra h
  exact hn (ambient_off c d h)

/-- Number of support centres strictly before an ambient cutoff. -/
def cut (c : ℕ → ℕ) (hc : StrictMono c) (N : ℕ) : ℕ :=
  Nat.find (show ∃ j : ℕ, N ≤ c j from
    ⟨N, index_le_of_strictMono c hc N⟩)

theorem cut_spec (c : ℕ → ℕ) (hc : StrictMono c) (N : ℕ) :
    N ≤ c (cut c hc N) :=
  Nat.find_spec (show ∃ j : ℕ, N ≤ c j from
    ⟨N, index_le_of_strictMono c hc N⟩)

theorem before_cut_iff (c : ℕ → ℕ) (hc : StrictMono c) (N j : ℕ) :
    j < cut c hc N ↔ c j < N := by
  constructor
  · intro hj
    by_contra hnot
    have hle : N ≤ c j := Nat.le_of_not_gt hnot
    have hmin : cut c hc N ≤ j := Nat.find_min'
      (show ∃ i : ℕ, N ≤ c i from ⟨N, index_le_of_strictMono c hc N⟩) hle
    exact (Nat.not_lt_of_ge hmin) hj
  · intro hj
    by_contra hnot
    have hle : cut c hc N ≤ j := Nat.le_of_not_gt hnot
    have hbound : N ≤ c j := (cut_spec c hc N).trans (hc.monotone hle)
    exact (Nat.not_lt_of_ge hbound) hj

/-- Exact unweighted prefix identity, at every ambient index. -/
theorem ambient_prefix (c d : ℕ → ℕ) (hc : StrictMono c) (N : ℕ) :
    (∑ n ∈ range N, ambient c d n) = ∑ j ∈ range (cut c hc N), d j := by
  classical
  let I := (range N).filter (fun n => n ∈ Set.range c)
  have himage : (range (cut c hc N)).image c = I := by
    ext n
    constructor
    · intro hn
      obtain ⟨j, hj, rfl⟩ := mem_image.mp hn
      exact mem_filter.mpr ⟨mem_range.mpr
        ((before_cut_iff c hc N j).mp (mem_range.mp hj)), ⟨j, rfl⟩⟩
    · intro hn
      obtain ⟨hnN, j, rfl⟩ := mem_filter.mp hn
      exact mem_image.mpr ⟨j, mem_range.mpr
        ((before_cut_iff c hc N j).mpr (mem_range.mp hnN)), rfl⟩
  have hrestrict : (∑ n ∈ I, ambient c d n) = ∑ n ∈ range N, ambient c d n := by
    apply Finset.sum_subset (Finset.filter_subset _ _)
    intro n hnN hnI
    apply ambient_off
    intro hn
    exact hnI (mem_filter.mpr ⟨hnN, hn⟩)
  calc
    (∑ n ∈ range N, ambient c d n) = ∑ n ∈ I, ambient c d n := hrestrict.symm
    _ = ∑ n ∈ (range (cut c hc N)).image c, ambient c d n := by rw [himage]
    _ = ∑ j ∈ range (cut c hc N), ambient c d (c j) :=
      Finset.sum_image (fun i _ j _ hij => hc.injective hij)
    _ = ∑ j ∈ range (cut c hc N), d j :=
      Finset.sum_congr rfl (fun j _ => ambient_at c d hc.injective j)

/-- Reindexing proves the complete sum, not just a finite telescope. -/
theorem ambient_hasSum (c d : ℕ → ℕ) (hc : Function.Injective c) {y : ℝ}
    (hs : HasSum (fun j => (d j : ℝ) / 2 ^ (c j + 1)) y) :
    HasSum (fun n => (ambient c d n : ℝ) / 2 ^ (n + 1)) y := by
  have he : HasSum
      (Function.extend c (fun j => (d j : ℝ) / 2 ^ (c j + 1)) (0 : ℕ → ℝ)) y :=
    (hasSum_extend_zero hc).mpr hs
  convert he using 1
  funext n
  by_cases hn : n ∈ Set.range c
  · obtain ⟨j, rfl⟩ := hn
    rw [hc.extend_apply, ambient_at c d hc j]
  · rw [Function.extend_apply' _ _ _ hn, ambient_off c d hn]
    simp only [Pi.zero_apply, Nat.cast_zero, zero_div]

/-- Cumulative divisibility at every late index implies divisibility of
individual late digits. Both adjacent prefixes are used explicitly. -/
theorem digit_divisible_of_prefixes (d : ℕ → ℕ) (q J : ℕ)
    (hprefix : ∀ j, J ≤ j → q ∣ ∑ i ∈ range (j + 1), d i)
    {j : ℕ} (hj : J + 1 ≤ j) : q ∣ d j := by
  have hnext : (q : ℤ) ∣ ((∑ i ∈ range (j + 1), d i : ℕ) : ℤ) := by
    exact_mod_cast hprefix j (by omega)
  have hprevNat : q ∣ ∑ i ∈ range j, d i := by
    have hh := hprefix (j - 1) (by omega)
    simpa only [Nat.sub_add_cancel (by omega : 1 ≤ j)] using hh
  have hprev : (q : ℤ) ∣ ((∑ i ∈ range j, d i : ℕ) : ℤ) := by
    exact_mod_cast hprevNat
  have hdiff := dvd_sub hnext hprev
  rw [Finset.sum_range_succ, Nat.cast_add, add_sub_cancel_left] at hdiff
  exact_mod_cast hdiff

/-- Transfer a fixed eventual modulus from indexed prefixes to BOTH the
ambient digit and ambient prefix, including gaps between support sites. -/
theorem ambient_eventual_congruences (c d : ℕ → ℕ) (hc : StrictMono c)
    (q J : ℕ)
    (hp : ∀ j, J ≤ j → q ∣ ∑ i ∈ range (j + 1), d i) :
    ∀ N, c (J + 1) + 1 ≤ N →
      q ∣ ambient c d N ∧ q ∣ ∑ n ∈ range N, ambient c d n := by
  intro N hN
  have hcut : J + 1 < cut c hc N :=
    (before_cut_iff c hc N (J + 1)).mpr (by omega)
  constructor
  · by_cases hmem : N ∈ Set.range c
    · obtain ⟨j, rfl⟩ := hmem
      have hj : J + 1 ≤ j := by
        by_contra hnot
        have hm := hc.monotone (Nat.le_of_lt (Nat.lt_of_not_ge hnot))
        omega
      rw [ambient_at c d hc.injective j]
      exact digit_divisible_of_prefixes d q J hp hj
    · rw [ambient_off c d hmem]
      exact dvd_zero q
  · rw [ambient_prefix c d hc N]
    have hp' := hp (cut c hc N - 1) (by omega)
    simpa only [Nat.sub_add_cancel (by omega : 1 ≤ cut c hc N)] using hp'

/-- The complete ambient word for any already-ready seed. This preserves
its named support so that quantitative bounds can be attached later. -/
theorem generated_ambient_filling (f : ℕ → ℝ) (hf : Tendsto f atTop atTop)
    (start : ℕ) (hready : Ready f start 0) {y : ℝ}
    (hyl : lowerTail f start 0 ≤ y) (hyu : y ≤ upperTail f start 0) :
    ∃ e : ℕ → ℕ,
      (∀ n, e n ≠ 0 → n ∈ Set.range (centre f start)) ∧
      (∀ᶠ n : ℕ in atTop, (e n : ℝ) ≤ f n) ∧
      (∀ q : ℕ, 0 < q → ∀ᶠ n : ℕ in atTop,
        q ∣ e n ∧ q ∣ ∑ i ∈ range n, e i) ∧
      HasSum (fun n : ℕ => (e n : ℝ) / 2 ^ (n + 1)) y := by
  let c := centre f start
  have hc : StrictMono c := centre_strictMono f start
  obtain ⟨d, hd, hp, hs⟩ := generated_interval_filling f start hready hyl hyu
  refine ⟨ambient c d, fun n hn => ambient_support c d hn, ?_, ?_,
    ambient_hasSum c d hc.injective hs⟩
  · apply Filter.eventually_atTop.mpr
    refine ⟨start, ?_⟩
    intro n hn
    by_cases hmem : n ∈ Set.range c
    · obtain ⟨j, rfl⟩ := hmem
      rw [ambient_at c d hc.injective j]
      have hdc : (d j : ℝ) ≤ capacity f start j := by exact_mod_cast hd j
      exact hdc.trans (capacity_budget f start hready j).1
    · rw [ambient_off c d hmem]
      have hfpos := (hready n hn).1
      have hnonneg : (0 : ℝ) ≤ amplitude 0 := Nat.cast_nonneg _
      simpa only [Nat.cast_zero] using hnonneg.trans hfpos
  · intro q hq
    obtain ⟨J, hJ⟩ := every_modulus_eventually f hf start q hq
    have hpq : ∀ j, J ≤ j → q ∣ ∑ i ∈ range (j + 1), d i := by
      intro j hj
      have hM : modulus f start j ∣ ∑ i ∈ range (j + 1), d i := by
        exact_mod_cast hp j
      exact (hJ j hj).trans hM
    exact Filter.eventually_atTop.mpr
      ⟨c (J + 1) + 1, ambient_eventual_congruences c d hc q J hpq⟩

/-- End-to-end discharge of the R8 ambient target, for an arbitrary
(non-monotone) divergent envelope. The support is chosen before the value. -/
theorem arbitrary_envelope_ambient_interval (f : ℕ → ℝ)
    (hf : Tendsto f atTop atTop) (K : ℕ) :
    ∃ S : Set ℕ, ∃ lo hi : ℝ,
      S ⊆ Set.Ici K ∧ UpperBanachZero S ∧ 0 < lo ∧ lo < hi ∧
      ∀ y : ℝ, lo ≤ y → y ≤ hi → ∃ e : ℕ → ℕ,
        (∀ n, e n ≠ 0 → n ∈ S) ∧
        (∀ᶠ n : ℕ in atTop, (e n : ℝ) ≤ f n) ∧
        (∀ q : ℕ, 0 < q → ∀ᶠ n : ℕ in atTop,
          q ∣ e n ∧ q ∣ ∑ i ∈ range n, e i) ∧
        HasSum (fun n : ℕ => (e n : ℝ) / 2 ^ (n + 1)) y := by
  obtain ⟨start, hK, hready, hsupport, hdensity, hbudget⟩ :=
    exists_sparse_budgeted_support f hf K
  exact ⟨Set.range (centre f start), lowerTail f start 0, upperTail f start 0,
    hsupport, hdensity, lowerTail_positive f start hready,
    generated_interval_nonempty f start hready,
    fun _ hyl hyu => generated_ambient_filling f hf start hready hyl hyu⟩

/-- The previously unproved Prop in SparseIntervalR8 is now supplied with
proof text. Compilation is still required; this is not a kernel receipt. -/
theorem ambient_sparse_target : AmbientSparseRationalisation_target :=
  arbitrary_envelope_ambient_interval

/-- The actual paper's arbitrary-envelope clause, including the input word,
its complete sum, a common interval ABOVE that sum, and every target in it. -/
theorem arbitrary_word_sparse_rationalisation (a : ℕ → ℕ) {A : ℝ}
    (ha : HasSum (fun n => (a n : ℝ) / 2 ^ (n + 1)) A)
    (f : ℕ → ℝ) (hf : Tendsto f atTop atTop) (K : ℕ) :
    ∃ S : Set ℕ, ∃ l u : ℝ,
      S ⊆ Set.Ici K ∧ UpperBanachZero S ∧ A < l ∧ l < u ∧
      ∀ r : ℝ, l ≤ r → r ≤ u → ∃ e : ℕ → ℕ,
        (∀ n, e n ≠ 0 → n ∈ S) ∧
        (∀ᶠ n : ℕ in atTop, (e n : ℝ) ≤ f n) ∧
        (∀ q : ℕ, 0 < q → ∀ᶠ n : ℕ in atTop,
          q ∣ e n ∧ q ∣ ∑ i ∈ range n, e i) ∧
        HasSum (fun n => ((a n + e n : ℕ) : ℝ) / 2 ^ (n + 1)) r := by
  obtain ⟨S, lo, hi, hSK, hSZ, hlo, hhi, hy⟩ :=
    arbitrary_envelope_ambient_interval f hf K
  refine ⟨S, A + lo, A + hi, hSK, hSZ, by linarith, by linarith, ?_⟩
  intro r hrl hru
  obtain ⟨e, heS, hef, heq, hes⟩ := hy (r - A) (by linarith) (by linarith)
  refine ⟨e, heS, hef, heq, ?_⟩
  have hsum := ha.add hes
  have hvalue : A + (r - A) = r := by ring
  rw [hvalue] at hsum
  convert hsum using 1
  funext n
  rw [Nat.cast_add, add_div]

#print axioms arbitrary_envelope_ambient_interval
#print axioms arbitrary_word_sparse_rationalisation
end ErdosProblems.Erdos251.PaperR9.SparseAmbient
