import Solutions.ExternalVerification251PrimeGapIdentity

#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.prime0_le_polynomial
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeSeries_summable
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeGapSeries_summable
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeSeries_eq_two_add_primeGapSeries
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeSeries_irrational_iff_primeGapSeries
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeDisplayedSeries_eq_four_add_two_primeGapSeries
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeDisplayedSeries_irrational_iff_primeGapSeries
