import Solutions.ExternalVerification257PaperStructuresBN

#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.paper_final_middle_cell_at_least_neg_two
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.paper_final_middle_cell_ne_neg_three
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.paper_final_middle_cell_remaining_cells
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.paper_perturbed_nextRemainder_three_branches
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.paper_perturbed_order_preservation
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.paper_perturbed_prefixChoice_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamUpperResetDyadicBandEscape_through_thirty
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBN.wordPulse_le
