import Solutions.PalomarCorpus.E249_04

#print axioms PalomarCorpus.E249.PaperStatementsAD.two_pow_mul_totient_series_eq
#print axioms PalomarCorpus.E249.PaperStatementsAI.totient_carry_residue_window_1_240_eq
#print axioms PalomarCorpus.E249.PaperStatementsAI.totient_series_eq_half_add_visible_coprime_pairs
#print axioms PalomarCorpus.E249.PaperStatementsAI.tsum_moebius_div_two_pow_sub_one_sq_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms PalomarCorpus.E249.PaperStatementsAI.tsum_visible_coprime_pairs_eq_totient_series
#print axioms PalomarCorpus.E249.PaperStatementsAI.tsum_visible_coprime_pairs_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms PalomarCorpus.E249.PaperStatementsAJ.exists_rational_parityComparison
#print axioms PalomarCorpus.E249.PaperStatementsAJ.moebius_three_values
#print axioms PalomarCorpus.E249.PaperStatementsAJ.parityComparisonProperties_do_not_imply_irrational
#print axioms PalomarCorpus.E249.PaperStatementsAK.farey_gap
#print axioms PalomarCorpus.E249.PaperStatementsAK.gap_check_window_1_240_le_79639646646701375323355774875831053
#print axioms PalomarCorpus.E249.PaperStatementsAK.tsum_gcd_layer_pos_coprime_half_eq_one
#print axioms PalomarCorpus.E249.PaperStatementsAK.tsum_pos_pair_both_dvd_half_eq_inv_mersenne_sq
#print axioms PalomarCorpus.E249.PaperStatementsAY.irrational_totient_iff_mobius_square
#print axioms PalomarCorpus.E249.PaperStatementsAY.mobius_square_reduction
#print axioms PalomarCorpus.E249.PaperStatementsJ.b6_mobiusMersenneTheta_two_eq_totientSeries_sub_half
#print axioms PalomarCorpus.E249.PaperStatementsK.b6_mobius_incidence_unimodular_and_injective
#print axioms PalomarCorpus.E249.PaperStatementsL.b6_retained_dyadic_sections_independent
#print axioms PalomarCorpus.E249.PaperStatementsO.b6_mobiusMersennePrefix_eq_icc_sum
#print axioms PalomarCorpus.E249.PaperStatementsO.b6_mobiusMersenne_rung_estimates
