import ExternalVerification269ThreePrimeStructure.Solution

#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.smoothPrefixLcm_eq_threePrimeHeight
#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.threePrimeKernelQ_eq_of_sameLogCell
#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.threePrimePositiveJumpSet_card
#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.finiteSmoothKernelSum_groupedByHeight
#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.smoothExponentShell_card_quadratic
#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.kernel_235_minor_eq_neg_one_fifteen
#print axioms Erdos249257.ExternalVerification269ThreePrimeStructure.threePrimeKernel_infiniteRank_and_noFiniteSeparation
