import Solutions.PalomarCorpus.E1041f

#print axioms PalomarCorpus.E1041.PaperStatementsF.exists_mergerIntegral_lt
#print axioms PalomarCorpus.E1041.PaperStatementsF.mergerIntegral_eq_mul_phi
#print axioms PalomarCorpus.E1041.PaperStatementsF.orliczKernel_continuous
#print axioms PalomarCorpus.E1041.PaperStatementsF.orliczKernel_tendsto_zero
#print axioms PalomarCorpus.E1041.PaperStatementsF.orlicz_currency
#print axioms PalomarCorpus.E1041.PaperStatementsF.phi_div_tendsto_zero
#print axioms PalomarCorpus.E1041.PaperStatementsF.phi_strictConvexOn
#print axioms PalomarCorpus.E1041.PaperStatementsF.phi_strictMonoOn
