import Solutions.ExternalVerification257PaperStructuresBZ

#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.paper_critical_band_index_collapse
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamUpperResetCriticalBandEscape_iff
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBZ.wordPulse_le
