import Solutions.PalomarCorpus.E257_29

#print axioms PalomarCorpus.E257.PaperStatementsAD.localMersenneQuotient_eq_geometric
#print axioms PalomarCorpus.E257.PaperStatementsAE.binaryCoeffTail_div_pow_tendsto_zero
#print axioms PalomarCorpus.E257.PaperStatementsAE.binaryCoeffTail_le
#print axioms PalomarCorpus.E257.PaperStatementsAE.not_irrational_binaryCoeffSeries_iff_exists_temperedBinaryOrbit
#print axioms PalomarCorpus.E257.PaperStatementsAG.supportCoeff_le_card_divisors
#print axioms PalomarCorpus.E257.PaperStatementsAG.supportCoeff_le_self
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometric
#print axioms PalomarCorpus.E257.PaperStatementsAR.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometricCore
#print axioms PalomarCorpus.E257.PaperStatementsAU.erdosSupportSeries_rational_iff_exists_temperedCarry
#print axioms PalomarCorpus.E257.PaperStatementsAU.erdosSupportSeries_two_eq_binaryCoeffSeries
#print axioms PalomarCorpus.E257.PaperStatementsAU.mobius_supportCoeff_boolean
#print axioms PalomarCorpus.E257.PaperStatementsAU.mobius_supportCoeff_eq_one_iff
#print axioms PalomarCorpus.E257.PaperStatementsAU.moebius_mul_supportCoeffAF
#print axioms PalomarCorpus.E257.PaperStatementsAV.dyadic_support_fraction_reciprocalMass_diverges_or_gt_one
#print axioms PalomarCorpus.E257.PaperStatementsAV.exists_unbounded_shifted_odd_tail_nat_state_of_support_fraction
#print axioms PalomarCorpus.E257.PaperStatementsAV.one_lt_reciprocalMass_of_dyadic_support_fraction_of_two_pos_mem
#print axioms PalomarCorpus.E257.PaperStructuresAY.localMersenneHalfTarget_lower_word_eq_greedy_and_remainder_eq
#print axioms PalomarCorpus.E257.PaperStructuresAY.localMersenneWeights_gapDominates_odd
