import Solutions.ExternalVerification1041QuarticQuotientFiber

#print axioms Erdos249257.ExternalVerification1041QuarticQuotientFiber.rootLift_kernel_le_axis
#print axioms Erdos249257.ExternalVerification1041QuarticQuotientFiber.rootLift_axis_integral
#print axioms Erdos249257.ExternalVerification1041QuarticQuotientFiber.rootLift_endpoint_budget_lt_two
#print axioms Erdos249257.ExternalVerification1041QuarticQuotientFiber.rootLift_length_lt_two_of_le_endpoint_budget
