import Solutions.ExternalVerification243BoundedRiseReducedTail

#print axioms Erdos249257.ExternalVerification243BoundedRiseReducedTail.no_eventuallyBoundedRise_reducedTail
#print axioms Erdos249257.ExternalVerification243BoundedRiseReducedTail.no_boundedRise_reducedTail
#print axioms Erdos249257.ExternalVerification243BoundedRiseReducedTail.no_boundedRise_of_tailAvoidance
