import Solutions.ExternalVerification257PaperStatementsAS

#print axioms Erdos249257.ExternalVerification257PaperStatementsAS.paper_seam_limit_unconditional
#print axioms Erdos249257.ExternalVerification257PaperStatementsAS.paper_sharper_additive_estimate
#print axioms Erdos249257.ExternalVerification257PaperStatementsAS.paper_skipped_core_recycling_witness_bounded
#print axioms Erdos249257.ExternalVerification257PaperStatementsAS.paper_unconditional_bound_one_extra_bit
#print axioms Erdos249257.ExternalVerification257PaperStatementsAS.tendsto_seamGreedyFiniteValue_greedyHalfTargetValue
#print axioms Erdos249257.ExternalVerification257PaperStatementsAS.tendsto_seamGreedyNormalizedRemainder
