import Solutions.PalomarCorpus.E257_11

#print axioms PalomarCorpus.E257.PaperStatementsAM.straddle_all_depths_iff_mem
#print axioms PalomarCorpus.E257.PaperStatementsAM.straddle_limiting_support_inputs
#print axioms PalomarCorpus.E257.PaperStatementsAT.binaryCoeffTail_supportCoeff_coe_finset_le_card
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_secondChannelSeparation
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_secondChannelSeparationRat_from_seven
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_skipped_dyadicCap
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_skipped_twoChannelCap
#print axioms PalomarCorpus.E257.PaperStructuresBV.seamScaledRem_eq_tailGreedyRemainder
