import Solutions.ExternalVerification269WindowEscapeEquivalence

#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.actualCofinalLocalWindowEscape_iff_irrational_value
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.actualCofinalLocalWindowEscape_iff
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.cofinalLocalWindowEscape_of_irrational
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.cofinalLocalWindowEscape_of_irrational_of_quadratic
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.exists_reducedCarry_of_value_eq_rat
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.trueNormalizedState_window
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.near_integer_of_residue_le_general
#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.exists_pow_gt_quadratic

#print axioms Erdos249257.ExternalVerification269WindowEscapeEquivalence.octic_escape_whole
