import Solutions.ExternalVerification257PaperStructuresBI

#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.greedyHalfFrozenMargin_fullShell_eq_neg_seamRemainder_of_alignment
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.halfGreedy_skipped_endpoint_trichotomy
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.half_lt_upper_competitor_of_eventually_right
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBI.wordPulse_le
