import Solutions.ExternalVerification257PaperStructuresCE

#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.middleProducer_allRight_forces_carry_lt_tail
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.producerCarry_insert_seamBelowSupport_eq_middleCoordinate
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresCE.wordPulse_le
