import Solutions.PalomarCorpus.E269_01

#print axioms PalomarCorpus.E269.PaperStatementsA.paper_jump_count
#print axioms PalomarCorpus.E269.PaperStatementsB.exponent_unique_real_base_short_interval
#print axioms PalomarCorpus.E269.PaperStatementsD.realPrefixLcm_eq_of_sameLogCell
#print axioms PalomarCorpus.E269.PaperStatementsD.realPrefixLcm_jump_first
#print axioms PalomarCorpus.E269.PaperStatementsD.realPrefixLcm_jump_second
#print axioms PalomarCorpus.E269.PaperStatementsD.realPrefixLcm_jump_third
#print axioms PalomarCorpus.E269.PaperStatementsD.realSmoothExponentShell_bounds
#print axioms PalomarCorpus.E269.PaperStatementsD.running_lcm_real_cutoff_exact
#print axioms PalomarCorpus.E269.PaperStatementsD.threePrimeKernelQ_eq_of_sameRealLogCell
#print axioms PalomarCorpus.E269.PaperStatementsX.two_prime_sums_transcendental
#print axioms PalomarCorpus.E269.PaperStatementsX.two_prime_transcendence
#print axioms PalomarCorpus.E269.PaperStatementsY.transcendental_heckeValue
#print axioms PalomarCorpus.E269.ThreePrimeStructure.finiteSmoothKernelSum_groupedByHeight
