import Solutions.ExternalVerification257FourNinthsRepairWindows
#print axioms Erdos249257.ExternalVerification257FourNinthsRepairWindows.exists_repair_in_sqrt_window
#print axioms Erdos249257.ExternalVerification257FourNinthsRepairWindows.four_ninths_mem_iff_repairCofinal
#print axioms Erdos249257.ExternalVerification257FourNinthsRepairWindows.four_ninths_mem_iff_repair_sqrt_windows
#print axioms Erdos249257.ExternalVerification257FourNinthsRepairWindows.four_ninths_not_mem_of_strict_sqrt_window
