import Solutions.ExternalVerification257PaperStructuresBY

#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamUpperResetCharge_le
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBY.wordPulse_le
