import Solutions.ExternalVerification257RationalMembership
#print axioms Erdos249257.ExternalVerification257RationalMembership.greedyMersenneSkippedSupport_infinite_iff_cofinal_skips
#print axioms Erdos249257.ExternalVerification257RationalMembership.infinite_greedyMersenneSkippedSupport_of_rat_mem
#print axioms Erdos249257.ExternalVerification257RationalMembership.rat_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms Erdos249257.ExternalVerification257RationalMembership.rat_mem_mersenneAchievementSet_iff_cofinal_greedy_skips
