import Solutions.ExternalVerification269IntegralBranchPinning
#print axioms Erdos249257.ExternalVerification269IntegralBranchPinning.surviving_window_orbit_eq_true_state
#print axioms Erdos249257.ExternalVerification269IntegralBranchPinning.trueNormalizedState_eq_telescope
#print axioms Erdos249257.ExternalVerification269IntegralBranchPinning.integral_state_upward_closed
#print axioms Erdos249257.ExternalVerification269IntegralBranchPinning.trueNormalizedState_pinning
