import Solutions.ExternalVerification249PaperStatementsBH

#print axioms Erdos249257.ExternalVerification249PaperStatementsBH.no_generic_rationality_carryRank_ceiling
#print axioms Erdos249257.ExternalVerification249PaperStatementsBH.rationalControl_periodic_with_unbounded_carry_rank
#print axioms Erdos249257.ExternalVerification249PaperStatementsBH.rationality_forces_mod_period_and_unbounded_rank
#print axioms Erdos249257.ExternalVerification249PaperStatementsBH.rationality_gives_mod_period_and_unbounded_rank
