import Solutions.ExternalVerification257PaperStructuresBX

#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.paper_upperSupport_isRowUpper
#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBX.wordPulse_le
