import Solutions.ExternalVerification257PaperStructuresCG

#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.paper_theoremA_right_branch_forces_small_deviation
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.paper_two_sided_dyadic_bound
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.paper_universal_band_condition_unfolded
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresCG.wordPulse_le
