import Solutions.PalomarCorpus.E249_31

#print axioms PalomarCorpus.E249.ActualLcmOrbit.actualLcmTailOrbit_eq_scaled_totientSeries_sub_prefix
#print axioms PalomarCorpus.E249.ActualLcmOrbit.irrational_totientSeries_iff_actualLcmOrbitNonintegralitySupply
#print axioms PalomarCorpus.E249.BinaryCyclotomicAnchors.binaryCyclotomicAnchoredKillSupply_iff_irrational
#print axioms PalomarCorpus.E249.BinaryCyclotomicAnchors.binaryCyclotomicLayer_unboundedPrimeDivisorSupply
#print axioms PalomarCorpus.E249.BinaryCyclotomicAnchors.exists_clean_binaryCyclotomicAnchor
#print axioms PalomarCorpus.E249.BinaryCyclotomicAnchors.exists_unbounded_binaryCyclotomicSupport_with_periodLock_of_not_irrational
#print axioms PalomarCorpus.E249.CanonicalMersenneFrontier.fullMersenneBlockResidue_succ
#print axioms PalomarCorpus.E249.CanonicalMersenneFrontier.fullMersenneCanonicalBasepointResidueGapSupply_iff_irrational
#print axioms PalomarCorpus.E249.CanonicalMersenneFrontier.fullMersenneCenteredResidueGapSupply_of_canonicalBasepoint
