import Solutions.PalomarCorpus.E257_51

#print axioms PalomarCorpus.E257.LiteralWeightedCover.exists_weighted_not_strengthened_host
#print axioms PalomarCorpus.E257.LiteralWeightedCover.exists_weighted_obstruction_with_mixed_heredity
#print axioms PalomarCorpus.E257.PaperStructuresCI.exists_strengthened_not_old_or_weighted_host
#print axioms PalomarCorpus.E257.PaperStructuresCO.finite_monotone_witness_rule_realised
#print axioms PalomarCorpus.E257.PositiveSkipEquivalence.greedyMersenneRemainderRat_half_pos
#print axioms PalomarCorpus.E257.RationalMembership.greedyMersenneSkippedSupport_infinite_iff_cofinal_skips
#print axioms PalomarCorpus.E257.RationalMembership.infinite_greedyMersenneSkippedSupport_of_rat_mem
#print axioms PalomarCorpus.E257.RationalMembership.rat_mem_mersenneAchievementSet_iff_cofinal_greedy_skips
#print axioms PalomarCorpus.E257.RationalMembership.rat_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
