import Solutions.PalomarCorpus.E249_02

#print axioms PalomarCorpus.E249.PaperStatementsAE.discrepancy_prefix
#print axioms PalomarCorpus.E249.PaperStatementsAE.exact_denominator
#print axioms PalomarCorpus.E249.PaperStatementsAE.gamma_le
#print axioms PalomarCorpus.E249.PaperStatementsAE.gamma_not_separation
#print axioms PalomarCorpus.E249.PaperStatementsAE.gamma_prefix
#print axioms PalomarCorpus.E249.PaperStatementsAE.no_certificate_after_prefix
#print axioms PalomarCorpus.E249.PaperStatementsAE.no_uniform_prefix_rule
#print axioms PalomarCorpus.E249.PaperStatementsAG.tsum_parityCoboundaryWeight_eq_three_halves
#print axioms PalomarCorpus.E249.PaperStatementsAW.certificate_sound
#print axioms PalomarCorpus.E249.PaperStatementsAW.exact_series
#print axioms PalomarCorpus.E249.PaperStatementsAW.generic_tail_period
#print axioms PalomarCorpus.E249.PaperStatementsAW.scaled_difference
#print axioms PalomarCorpus.E249.PaperStatementsAW.scaled_tail_split
#print axioms PalomarCorpus.E249.PaperStatementsAW.truncation_error_bound
#print axioms PalomarCorpus.E249.PaperStatementsAW.value_cast
