import Solutions.ExternalVerification249PaperStatementsA

#print axioms Erdos249257.ExternalVerification249PaperStatementsA.actualLcmTailDiff_shift_pos
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.actualLcm_integral_forces_topEdgeResidue
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.carryOrbit_eq_tail_diff
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.dvd_periodLcm
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.eq_prime_pow_of_not_dvd_periodLcm
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.irrational_totient_series_iff_lcm_diagonal_certificate_supply
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.irrational_totient_series_of_lcm_cone_nonintegrality_supply
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.irrational_totient_series_of_lcm_diagonal_nonintegrality_supply
#print axioms Erdos249257.ExternalVerification249PaperStatementsA.periodLcm_diagonal_kill_iff_tail_diff_notMem_int
