import Solutions.ExternalVerification257PaperStatementsF

#print axioms Erdos249257.ExternalVerification257PaperStatementsF.cofinalExactLocalMersenneHalfRows_of_positiveHalfGreedySkips
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.eq_halfGreedyPrefixSupport_of_critical_crossing
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.exactLocalMersenneHalfRow_of_positiveHalfGreedySkip
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.halfGreedySkippedCriticalQuotientSupply_of_precriticalSuffix
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.halfGreedySkippedPrecriticalSuffixSupply_iff_preTake
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.halfGreedy_precriticalSuffix_lt_iff_futureSkipCoverage
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.halfGreedy_precriticalSuffix_lt_of_future_skip_after_takenBlock
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.halfGreedy_precriticalSuffix_lt_of_next_skip
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.half_mem_mersenneAchievementSet_of_skippedFullShellNonnegative
#print axioms Erdos249257.ExternalVerification257PaperStatementsF.skippedCoreCriticalQuotientSupply_iff_halfGreedySkipped
