import Solutions.ExternalVerification249PaperStatementsAD

#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.certifiedKill_all_upto_sixteen
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.certifiedKill_depth_floor
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.dtwWindowSeparatedPairs_iff_irrational_totient_series
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.exists_certifiedKill_iff_tail_diff_notMem_int
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.irrational_totient_series_iff_all_tail_diffs_nonintegral
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.irrational_totient_series_iff_certificate_supply
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.tail_diff_int_of_den_dvd
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.tail_diff_mem_int_iff_scaled_series_mem_int
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.tail_diff_notMem_int_of_certifiedKill
#print axioms Erdos249257.ExternalVerification249PaperStatementsAD.two_pow_mul_totient_series_eq
