import Solutions.ExternalVerification68MovingFactorScaleSplit
#print axioms Erdos249257.ExternalVerification68MovingFactorScaleSplit.movingPrivateFactorScaleSplit_implies_irrational
#print axioms Erdos249257.ExternalVerification68MovingFactorScaleSplit.splitFactorNormalizedCollision_implies_irrational
#print axioms Erdos249257.ExternalVerification68MovingFactorScaleSplit.fixedOwnerPair_eventually_absorbed
