import Solutions.ExternalVerification249FullDepthRayAmplifier
#print axioms Erdos249257.ExternalVerification249FullDepthRayAmplifier.eventually_twoSyndetic_fullDepthKillMultipliers_of_seed
#print axioms Erdos249257.ExternalVerification249FullDepthRayAmplifier.exists_fullDepthKill_on_ray_iff_shift_notMem_int
#print axioms Erdos249257.ExternalVerification249FullDepthRayAmplifier.apFullDepthEscape_iff_irrational
#print axioms Erdos249257.ExternalVerification249FullDepthRayAmplifier.cofinalFullDepthKillSupply_iff_periodMultipleKillSupply
#print axioms Erdos249257.ExternalVerification249FullDepthRayAmplifier.cofinalFullDepthKillSupply_iff_irrational
