import Solutions.ExternalVerification257PaperStructuresCO

#print axioms Erdos249257.ExternalVerification257PaperStructuresCO.finite_monotone_witness_rule_realised
#print axioms Erdos249257.ExternalVerification257PaperStructuresCO.irrational_erdosSupportSeries_positivePeriodic
#print axioms Erdos249257.ExternalVerification257PaperStructuresCO.paper_terminalhalf_iff
