import Solutions.ExternalVerification1049PrimeSupportSelectors

#print axioms Erdos249257.ExternalVerification1049PrimeSupportSelectors.primeSupportedTwoSelector_rationalGap
#print axioms Erdos249257.ExternalVerification1049PrimeSupportSelectors.rationalTwoSelector_notBothTendstoZero
#print axioms Erdos249257.ExternalVerification1049PrimeSupportSelectors.primeSupportedOneRow_rationalGap
#print axioms Erdos249257.ExternalVerification1049PrimeSupportSelectors.primePowerSupportedOneRow_rationalGap
#print axioms Erdos249257.ExternalVerification1049PrimeSupportSelectors.twoSelector_unimodularHeightDecay_tradeoff
#print axioms Erdos249257.ExternalVerification1049PrimeSupportSelectors.zeroDenominatorCoordinates_binaryCollision
