import Solutions.ExternalVerification68StrictSuccessorCarry
#print axioms Erdos249257.ExternalVerification68StrictSuccessorCarry.companionOrbit_completeCharacterization
#print axioms Erdos249257.ExternalVerification68StrictSuccessorCarry.strictSuccessorCarry_completeCharacterization
