import Solutions.ExternalVerification257PaperStatementsB

#print axioms Erdos249257.ExternalVerification257PaperStatementsB.greedy_survives_of_mem_mersenneAchievementSet
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.half_mem_mersenneAchievementSet_of_secondChannelSeparation
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.half_mem_mersenneAchievementSet_of_secondChannelSeparationRat_from_seven
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.half_mem_mersenneAchievementSet_of_skipped_dyadicCap
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.half_mem_mersenneAchievementSet_of_skipped_twoChannelCap
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.mem_mersenneAchievementSet_iff_greedy_survival
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.mem_mersenneAchievementSet_of_greedySkippedSupport_infinite
#print axioms Erdos249257.ExternalVerification257PaperStatementsB.mem_mersenneAchievementSet_of_greedy_survival
