import ErdosProblems.Erdos243.DynamicCancellation

/-!
# Erdős #243: feedback realizability

Exact algebraic interfaces distinguishing the true reduced feedback orbit
from artificial solutions of its square-residue congruence.
-/

namespace ErdosProblems.Erdos243

/-- The denominator-transport defect is exactly the failure of the centered
quotient to generate the next multiplier.  This is the local realizability
condition missing from a bare square-residue congruence. -/
theorem feedback_transport_defect
    {a aNext u uNext h : ℕ}
    {e eNext Δ : ℤ}
    (hq : (h * uNext : ℤ) = (u : ℤ) - e)
    (hres :
      (h : ℤ) * eNext =
        (a : ℤ) ^ 2 * e - Δ * ((u : ℤ) - e)) :
    (h : ℤ) *
          (((aNext : ℤ) - 1) * (uNext : ℤ) + eNext) -
        (a : ℤ) * (((a : ℤ) - 1) * (u : ℤ) + e) =
      ((u : ℤ) - e) *
        ((aNext : ℤ) -
          ((a : ℤ) ^ 2 - (a : ℤ) + 1 + Δ)) := by
  calc
    (h : ℤ) *
            (((aNext : ℤ) - 1) * (uNext : ℤ) + eNext) -
          (a : ℤ) * (((a : ℤ) - 1) * (u : ℤ) + e) =
        ((u : ℤ) - e) *
          ((aNext : ℤ) -
            ((a : ℤ) ^ 2 - (a : ℤ) + 1 + Δ)) := by
      have hu : (u : ℤ) = (h : ℤ) * uNext + e := by linarith
      rw [hu] at hres ⊢
      rw [mul_add, hres]
      ring

/-- Once the next multiplier is generated by the centered quotient, the
reduced denominator transports exactly. -/
theorem feedback_denominator_transport
    {a aNext u uNext h : ℕ}
    {e eNext Δ : ℤ}
    (hq : (h * uNext : ℤ) = (u : ℤ) - e)
    (hres :
      (h : ℤ) * eNext =
        (a : ℤ) ^ 2 * e - Δ * ((u : ℤ) - e))
    (haNext :
      (aNext : ℤ) = (a : ℤ) ^ 2 - (a : ℤ) + 1 + Δ) :
    (h : ℤ) *
          (((aNext : ℤ) - 1) * (uNext : ℤ) + eNext) =
      (a : ℤ) * (((a : ℤ) - 1) * (u : ℤ) + e) := by
  have hdefect :=
    feedback_transport_defect
      (a := a) (aNext := aNext) (u := u) (uNext := uNext)
      (h := h) (e := e) (eNext := eNext) (Δ := Δ) hq hres
  rw [haNext] at hdefect ⊢
  linarith

/-- Exact converse: when the raw next numerator is nonzero, denominator
transport holds precisely when the centered quotient generates the next
multiplier. -/
theorem feedback_denominator_transport_iff
    {a aNext u uNext h : ℕ}
    {e eNext Δ : ℤ}
    (hq : (h * uNext : ℤ) = (u : ℤ) - e)
    (hres :
      (h : ℤ) * eNext =
        (a : ℤ) ^ 2 * e - Δ * ((u : ℤ) - e))
    (hq0 : (u : ℤ) - e ≠ 0) :
    (h : ℤ) *
          (((aNext : ℤ) - 1) * (uNext : ℤ) + eNext) =
        (a : ℤ) * (((a : ℤ) - 1) * (u : ℤ) + e) ↔
      (aNext : ℤ) = (a : ℤ) ^ 2 - (a : ℤ) + 1 + Δ := by
  have hdefect :=
    feedback_transport_defect
      (a := a) (aNext := aNext) (u := u) (uNext := uNext)
      (h := h) (e := e) (eNext := eNext) (Δ := Δ) hq hres
  constructor
  · intro htransport
    have hzero :
        ((u : ℤ) - e) *
            ((aNext : ℤ) -
              ((a : ℤ) ^ 2 - (a : ℤ) + 1 + Δ)) = 0 := by
      rw [← hdefect, htransport]
      ring
    exact sub_eq_zero.mp ((mul_eq_zero.mp hzero).resolve_left hq0)
  · intro haNext
    exact feedback_denominator_transport hq hres haNext

/-- On a cancellation-free step, two centered multiplications by `a`
recover the square quotient.  The same quotients generate both the current
denominator and the next multiplier. -/
theorem primitive_squareRoot_feedback
    {a aNext u uNext : ℤ}
    {e eNext Δ L r t v : ℤ}
    (huNext : uNext ≠ 0)
    (hU : uNext = u - e)
    (hV : v = (a - 1) * u + e)
    (hfirst : a * e = L * uNext + t)
    (hsecond : a * t = r * uNext + eNext)
    (hdefect : a ^ 2 * e = Δ * uNext + eNext)
    (haNext : aNext = a ^ 2 - a + 1 + Δ) :
    Δ = a * L + r ∧
      v = (a - 1 + L) * uNext + t ∧
      aNext = a * (a - 1 + L) + (r + 1) := by
  have hquotient :
      Δ * uNext = (a * L + r) * uNext := by
    calc
      Δ * uNext = a ^ 2 * e - eNext := by linarith
      _ = a * (L * uNext + t) - eNext := by rw [← hfirst]; ring
      _ = (a * L + r) * uNext := by
        have heNext : eNext = a * t - r * uNext := by linarith
        rw [heNext]
        ring
  have hΔ : Δ = a * L + r := by
    exact mul_right_cancel₀ huNext hquotient
  constructor
  · exact hΔ
  constructor
  · have hu : u = uNext + e := by linarith
    rw [hV, hu]
    calc
      (a - 1) * (uNext + e) + e =
          (a - 1) * uNext + a * e := by ring
      _ = (a - 1) * uNext + (L * uNext + t) := by rw [hfirst]
      _ = (a - 1 + L) * uNext + t := by ring
  · rw [haNext, hΔ]
    ring

/-- The intermediate centered residue has an exact norm defect divisible by
the next primitive numerator. -/
theorem primitive_squareRoot_norm
    {a e eNext L r t uNext : ℤ}
    (hfirst : a * e = L * uNext + t)
    (hsecond : a * t = r * uNext + eNext) :
    t ^ 2 - e * eNext = (r * e - L * t) * uNext := by
  have heNext : eNext = a * t - r * uNext := by linarith
  rw [heNext]
  calc
    t ^ 2 - e * (a * t - r * uNext) =
        r * e * uNext - t * (a * e - t) := by ring
    _ = (r * e - L * t) * uNext := by rw [hfirst]; ring

/-- In the artificial square-unit pattern `a = u+2`, `e = -1`, the true
centered quotient is `-(u+3)` and therefore forces the quadratic next
multiplier `u*(u+2)`. -/
theorem artificial_squareUnit_true_nextMultiplier
    {u aNext : ℤ}
    (haNext :
      aNext = (u + 2) ^ 2 - (u + 2) + 1 - (u + 3)) :
    aNext = u * (u + 2) := by
  rw [haNext]
  ring

/-- The linear fake continuation `u+3` cannot equal the multiplier required
by true feedback once `u ≥ 3`. -/
theorem artificial_squareUnit_not_realizable
    {u : ℤ}
    (hu : 3 ≤ u) :
    u + 3 ≠ u * (u + 2) := by
  nlinarith

end ErdosProblems.Erdos243
