import Solutions.ExternalVerification257PaperStructuresCC

#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.finalMiddleCell_neg_three_not_last
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresCC.wordPulse_le
