import Solutions.PalomarCorpus.E1049_09

#print axioms PalomarCorpus.E1049.PaperStructuresV.tail_prefix_lattice
#print axioms PalomarCorpus.E1049.PaperStructuresW.geometric_universality
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.integerLinearForm_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.primePowerSupportedOneRow_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.primeSupportedOneRow_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.primeSupportedTwoSelector_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.rationalTwoSelector_notBothTendstoZero
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.twoSelector_detHeightDecay_tradeoff
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.twoSelector_rationalGap
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.twoSelector_unimodularHeightDecay_tradeoff
#print axioms PalomarCorpus.E1049.PrimeSupportSelectors.zeroDenominatorCoordinates_binaryCollision
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.eightyOneTwoHundredths_lt_threeHalves_log_ratio
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.threeHalves_outside_bundschuhVaananenHeightRegion
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.threeHalves_outside_zudilinHeightRegion
#print axioms PalomarCorpus.E1049.PublishedHeightRegions.threeHalves_zudilin_power_obstruction
#print axioms PalomarCorpus.E1049.RationalBaseBarrier.twoPow_le_rationalBaseForcingNat
#print axioms PalomarCorpus.E1049.RationalBaseRegion.rational_base_measure
#print axioms PalomarCorpus.E1049.RationalBaseRegion.rational_base_region
#print axioms PalomarCorpus.E1049.RationalBaseRegion.thirtyone_four
#print axioms PalomarCorpus.E1049.RationalBaseRegion.thirtyone_four_power_measure_lt_paper_fraction
