import Solutions.ExternalVerification68PrimeUnitTranslator

#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.primeTranslator_moment_zero
#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.primeTranslator_channel_zero_of_lt_p
#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.primeTranslator_channel_at_prime
#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.primeTranslator_channel_zero_of_p_lt
#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.primeTranslator_channelResidual_eq_one
#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.channelResidual_appendPrimeTranslator
#print axioms Erdos249257.ExternalVerification68PrimeUnitTranslator.exists_remote_factorialGrid_primeTranslator_reduction
