import Solutions.ExternalVerification249PaperStatementsBA

#print axioms Erdos249257.ExternalVerification249PaperStatementsBA.alpha_divisor_sum_eq_totient
#print axioms Erdos249257.ExternalVerification249PaperStatementsBA.forwardMultipleShift_least
#print axioms Erdos249257.ExternalVerification249PaperStatementsBA.forwardMultiple_enumeration
#print axioms Erdos249257.ExternalVerification249PaperStatementsBA.forwardMultiple_spec
#print axioms Erdos249257.ExternalVerification249PaperStatementsBA.lambertValue_alpha_eq_totientSeries
