import Solutions.PalomarCorpus.E257_43

#print axioms PalomarCorpus.E257.PaperStatementsAA.paper_half_lcm_horizon
#print axioms PalomarCorpus.E257.PaperStatementsAA.paper_mod_twelve_filter
#print axioms PalomarCorpus.E257.PaperStatementsAA.paper_parity_excludes_finite_support
#print axioms PalomarCorpus.E257.PaperStatementsAA.paper_theoremA_crossing_bound_square_le
#print axioms PalomarCorpus.E257.PaperStatementsAA.paper_witness_exclusion
#print axioms PalomarCorpus.E257.PaperStatementsAI.paper_forced_greedy_low_ranks
#print axioms PalomarCorpus.E257.PaperStatementsAM.irrational_mersenneTail
#print axioms PalomarCorpus.E257.PaperStatementsJ.paper_forced_greedy_unique_support_and_criterion
#print axioms PalomarCorpus.E257.PaperStatementsJ.paper_rung_finite_decision
#print axioms PalomarCorpus.E257.PaperStatementsN.approx_orbit_induction
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_no_ties
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_no_ties_skip
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_no_ties_take
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_one_orbit_stability
#print axioms PalomarCorpus.E257.PaperStatementsN.paper_one_sided_finite_decision_boundary
#print axioms PalomarCorpus.E257.PaperStatementsN.tailGreedyRemainder_mersenne
