import Solutions.PalomarCorpus.E249_15

#print axioms PalomarCorpus.E249.PaperStatementsAJ.exists_prime_totient_shift_four_mul_congr_two_mod_four
#print axioms PalomarCorpus.E249.PaperStatementsAJ.shortWindow_inequalities
#print axioms PalomarCorpus.E249.PaperStatementsAK.totient_one_eq_one
#print axioms PalomarCorpus.E249.PaperStatementsAT.actualLcmTailOrbit_eq_tail_difference
#print axioms PalomarCorpus.E249.PaperStatementsAT.eventual_tail_period_of_not_irrational
#print axioms PalomarCorpus.E249.PaperStatementsAT.exists_certifiedKill_iff_tail_diff_nonintegral
#print axioms PalomarCorpus.E249.PaperStatementsAT.exists_prime_integral_tailDiff_half_pulse
#print axioms PalomarCorpus.E249.PaperStatementsAT.exists_prime_twoAdic_pulse_block
#print axioms PalomarCorpus.E249.PaperStatementsAT.fixedRank_cleanWindow_structure
#print axioms PalomarCorpus.E249.PaperStatementsAT.irrational_of_certificate_supply
#print axioms PalomarCorpus.E249.PaperStatementsAU.pulse_delta_of_divisor_data
#print axioms PalomarCorpus.E249.PaperStatementsAU.rational_tail_period_explicit_witnesses
#print axioms PalomarCorpus.E249.PaperStatementsAU.shortWindow_certificates_kill_omega_four_and_six
#print axioms PalomarCorpus.E249.PaperStatementsAU.tail_diff_notMem_int_of_irrational
#print axioms PalomarCorpus.E249.PaperStatementsAU.two_mul_totient_dvd_totient_second_difference
#print axioms PalomarCorpus.E249.PaperStatementsBA.forwardMultipleShift_least
#print axioms PalomarCorpus.E249.PaperStatementsBA.forwardMultiple_enumeration
#print axioms PalomarCorpus.E249.PaperStatementsBA.forwardMultiple_spec
#print axioms PalomarCorpus.E249.PaperStatementsBC.carryShift_dvd_iff_tailDiff_integral
#print axioms PalomarCorpus.E249.PaperStatementsBC.temperedCarry_eq_scaledTail_and_shift
#print axioms PalomarCorpus.E249.PaperStatementsBH.rationality_forces_mod_period_and_unbounded_rank
#print axioms PalomarCorpus.E249.PaperStatementsBM.totientTail_eq_tsum_mobius_inversion
