import Solutions.ExternalVerification257PaperStatementsAY

#print axioms Erdos249257.ExternalVerification257PaperStatementsAY.one_div_twenty_one_mem_iff_not_fatalAlignedBranch
#print axioms Erdos249257.ExternalVerification257PaperStatementsAY.twentyOneFatalAlignedBranch_eventually_affine_supercapacity
#print axioms Erdos249257.ExternalVerification257PaperStatementsAY.twentyOneFatalAlignedBranch_eventually_strict_supercapacity
