import Solutions.ExternalVerification1049PaperStatementsF

#print axioms Erdos249257.ExternalVerification1049PaperStatementsF.bottomJet3_eq_zero_iff_dvd
#print axioms Erdos249257.ExternalVerification1049PaperStatementsF.commonMultiplier_not_two_not_three_of_endpoint_units
#print axioms Erdos249257.ExternalVerification1049PaperStatementsF.cyclotomicHomEval_isCoprime_mul
