-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Aggregator for the conditional-row source port, 21 Sep 2026: imports every module that
states a paper result proved from one named input, copied verbatim from the paper
repository, so one target elaborates all of them in a single environment. The band
entries under `PalomarCorpus/E<n>[xyz]` compare those statements with the named input in
the signature. Generated by the coverage lane; regenerate rather than hand-edit.
-/

import ErdosProblems.Erdos1041.PaperCompleteR21.ConstantFactorAreaCriteria
import ErdosProblems.Erdos1041.PaperCompleteR21.CriticalValueSeparationTransport
import ErdosProblems.Erdos1041.PaperCompleteR21.HyperbolicCirclePacking
import ErdosProblems.Erdos1041.PaperCompleteR21.HyperbolicLawOfCosines
import ErdosProblems.Erdos1041.PaperCompleteR21.LobeAndArity
import ErdosProblems.Erdos1041.PaperCompleteR21.LowCriticalScaleTransport
import ErdosProblems.Erdos1041.PaperCompleteR21.SeparationParent
import ErdosProblems.Erdos1041.PaperCompleteR21.SubcriticalPerimeterPath
import ErdosProblems.Erdos1049.PaperCompleteR21.SimultaneousMahlerSystem
import ErdosProblems.Erdos243.PaperCompleteR11.CubicQuarticCertificates
import ErdosProblems.Erdos243.PaperCompleteR20.CubicModularSquareSpecialisation
import ErdosProblems.Erdos243.PaperCompleteR20.CubicRateCanonicalBridge
import ErdosProblems.Erdos251.BinarySourceR11
import ErdosProblems.Erdos251.NonconcentrationConsequencesR11
import ErdosProblems.Erdos251.PaperCompleteR21.PerturbedPrimePositions
import ErdosProblems.Erdos251.PerturbationGrowthR11
import ErdosProblems.Erdos269.PaperCompleteR21.TwoPrimeSums
import ErdosProblems.Erdos243.PaperCompleteR20.CubicSquareSpecializationAssembly
import ErdosProblems.Erdos243.PaperCompleteR21.ChebotarevSquareSpecialisation
import ErdosProblems.Erdos251.ActualPrimePaperR11
import ErdosProblems.Erdos251.PaperCompleteR21.TwoWindowSparsity
import ErdosProblems.Erdos243.PaperCompleteR21.CubicRateExclusionChain
import ErdosProblems.Erdos251.PaperCompleteR21.JointPrimeGapCountermodel
import ErdosProblems.Erdos243.PaperCompleteR21.GaloisSignFlipClosure
