import Solutions.PalomarCorpus.E257d

#print axioms PalomarCorpus.E257.PaperStatementsD.cofinalPositiveHalfGreedySkips_iff_half_mem
#print axioms PalomarCorpus.E257.PaperStatementsD.greedyHalf_mem_nextMersenneDyadicSliver_iff_excess
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_infinite_of_cofinalStripReturn
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_infinite_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_infinite_of_mobiusCenteredHalfCarry_upperBound
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_half_of_cofinal_upper_carry
#print axioms PalomarCorpus.E257.PaperStatementsD.greedy_mobiusCenteredHalfCarry_nonneg
#print axioms PalomarCorpus.E257.PaperStatementsD.half_mem_iff_every_actual_skip_survives
#print axioms PalomarCorpus.E257.PaperStatementsD.half_mem_mersenneAchievementSet_of_positiveHalfGreedySkips
#print axioms PalomarCorpus.E257.PaperStatementsD.paper_greedy_survival
