import Solutions.ExternalVerification243PaperStatementsK

#print axioms Erdos249257.ExternalVerification243PaperStatementsK.epoch_energy_named_crossing_set
#print axioms Erdos249257.ExternalVerification243PaperStatementsK.forcedOrbit_survives_iff_of_factorial_modEq
#print axioms Erdos249257.ExternalVerification243PaperStatementsK.forcedSurvives_iff_of_modEq_factorial
