#!/usr/bin/env python3
"""Regenerate the `Erdos257PeriodNoncollapse` alias shims over the `Erdos249257` library.

Background
----------
This corpus used to carry its own copy of the paper repository's `Erdos249257` library under the
module prefix `Erdos257PeriodNoncollapse`. The two are the same mathematics: the same module
basenames, the same declaration names below the root namespace, and the same statement text. The
only systematic difference is the root namespace, `Erdos249257` in the paper repository against
`Erdos257PeriodNoncollapse` here.

Carrying two copies meant the corpus could not import the paper repository's own sources, because
seven modules used the paper repository's bare namespaces and collided. The corpus now carries one
real library, `Erdos249257`, copied verbatim, and each `Erdos257PeriodNoncollapse.X` module becomes
a generated shim that imports `Erdos249257.X` and re-exports its declarations under the old names.
Every fully qualified name the `Solutions/` and `PalomarCorpus/` entries cite keeps resolving, so no
Challenge, comparator record or replay digest changes.

Why an explicit export list
---------------------------
Lean 4 has no wildcard `export`. Each alias is named. The list is derived from the two trees, so it
is regenerated rather than maintained by hand. Aliases are emitted inside the matching sub-namespace
(`namespace Erdos257PeriodNoncollapse.GreedyAchievementSet`, not just the root), because entry
modules write `open Erdos257PeriodNoncollapse.GreedyAchievementSet` and that needs the namespace to
exist, not only the names.

Five modules (`GapFareyBound`, `GcdMomentCalculus`, `GeometricCoprimality`,
`MersenneLambertLadder`, `SternBrocotRunGeometry`) declare into bare namespaces rather than into the
library root, and the corpus copy used exactly the same names. Those need no alias: the library
already publishes the name the entries cite, and an `export` would name a constant that does not
exist. Their shims are a bare import, which is still required, because the entries import the module
path `Erdos257PeriodNoncollapse.X` and that path has to keep resolving.

Declarations this corpus has that the paper repository does not keep in supplement modules, which
the generator leaves alone.

Usage
-----
    python3 scripts/generate_fork_alias_shims.py --paper-lean <path to plectis-erdos>/lean [--check]

`--check` writes nothing and exits non-zero if any shim is out of date.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_LIB = 'Erdos249257'
DST_LIB = 'Erdos257PeriodNoncollapse'

DECL_RE = re.compile(
    r'^(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|noncomputable\s+)*'
    r'(theorem|lemma|def|abbrev|instance|structure|inductive)\s+([^\s:({\[]+)', re.M)
NS_RE = re.compile(r'^\s*(namespace|end)\s+([A-Za-z_][\w.]*)\s*$', re.M)
IMPORT_RE = re.compile(r'^\s*import\s+([A-Za-z_][\w.]*)', re.M)

# Names the corpus published from one module that the paper repository now declares in another, so
# the shim for the module the corpus published them from has to name them explicitly. Only the
# library's own module boundaries moved; the declarations are the same. `allBaseTotientKernelSeq`
# was split out of `AllBaseTotientKernel` into `TotientKernelConditional`, which that module still
# imports, so the constant is in scope for the export. Keyed by shim module, valued by
# (sub-namespace, name). Regenerated by the coverage lane's `lost_classify.py`.
MOVED: dict[str, tuple[tuple[str, str], ...]] = {
    'AllBaseTotientKernel': (('', 'allBaseTotientKernelSeq'),),
}

# `export` publishes an ALIAS, and Lean resolves a `_root_.`-prefixed identifier against real
# constants only, so an entry that writes `_root_.Erdos257PeriodNoncollapse.X` cannot see one. Those
# names therefore need a real declaration at that exact fully qualified name, not an alias. The list
# is scanned out of the citing trees rather than written by hand, so it cannot drift.
ROOT_CITE_RE = re.compile(r'_root_\.' + DST_LIB + r'\.([A-Za-z_][\w.\']*)')
CITING_ROOTS = ('Solutions', 'PalomarCorpus', 'ErdosProblems')
DECL_KIND_RE = re.compile(
    r'^(?P<mods>(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|noncomputable\s+)*)'
    r'(?P<kind>theorem|lemma|def|abbrev|instance|structure|inductive)\s+(?P<name>[^\s:({\[]+)', re.M)


# Modules that stay REAL corpus modules rather than becoming shims. `SignedQMomentObstruction` is
# here because its results are used by `rw`: an `abbrev` at the cited name is a different constant
# from the library's, so a rewrite lemma stated about one does not fire on a term built from the
# other. Keeping the corpus copy is safe precisely because the two libraries differ only by root
# namespace, so `Erdos257PeriodNoncollapse.SignedQMomentObstruction.*` and
# `Erdos249257.SignedQMomentObstruction.*` can coexist in one environment without colliding.
KEEP_REAL = {'SignedQMomentObstruction'}


def cited_real_names() -> set[str]:
    """Names the corpus cites with a `_root_.` prefix, relative to the fork root."""
    out: set[str] = set()
    roots = [REPO / d for d in CITING_ROOTS]
    roots += [d for d in sorted(REPO.iterdir()) if d.is_dir() and d.name.startswith('ExternalVerification')]
    for r in roots:
        if not r.is_dir():
            continue
        for f in r.rglob('*.lean'):
            out |= set(ROOT_CITE_RE.findall(f.read_text(encoding='utf-8', errors='ignore')))
    return out


def declaration_kinds(text: str) -> dict[str, tuple[str, bool]]:
    """Namespace-qualified name -> (kind, is noncomputable)."""
    text = DOC_RE.sub(lambda m: '\n' * m.group(0).count('\n'), text)
    events = [(m.start(), m.group(1), m.group(2)) for m in NS_RE.finditer(text)]
    marks = [(s, 'ns', k, n, '') for s, k, n in events]
    for m in DECL_KIND_RE.finditer(text):
        marks.append((m.start(), 'decl', m.group('kind'), m.group('name'),
                      'noncomputable' in m.group('mods')))
    marks.sort(key=lambda x: x[0])
    stack: list[str] = []
    out: dict[str, tuple[str, bool]] = {}
    for _, tag, k, name, nc in marks:
        if tag == 'ns':
            if k == 'namespace':
                stack.append(name)
            elif stack and stack[-1] == name:
                stack.pop()
        else:
            out['.'.join(stack + [name.strip()]) if stack else name.strip()] = (k, bool(nc))
    return out
# `private` declarations cannot be exported; `example` and prose in doc comments must not be picked up.
PRIVATE_RE = re.compile(r'^(?:@\[[^\]]*\]\s*)?private\s', re.M)
DOC_RE = re.compile(r'/-.*?-/', re.S)


def declarations(text: str) -> list[str]:
    """Namespace-qualified, exportable declaration names, in source order.

    Doc comments are stripped first: prose such as "This theorem says that ..." otherwise reads as a
    declaration named `says`.
    """
    text = DOC_RE.sub(lambda m: '\n' * m.group(0).count('\n'), text)
    events = [(m.start(), m.group(1), m.group(2)) for m in NS_RE.finditer(text)]
    for m in DECL_RE.finditer(text):
        if PRIVATE_RE.match(text, m.start()):
            continue
        events.append((m.start(), 'decl', m.group(2)))
    events.sort()
    stack: list[str] = []
    out: list[str] = []
    for _, kind, name in events:
        if kind == 'namespace':
            stack.append(name)
        elif kind == 'end':
            if stack and stack[-1] == name:
                stack.pop()
        else:
            out.append('.'.join(stack + [name.strip()]) if stack else name.strip())
    return out


def real_text(sub: str, leaf: str, kind: str, noncomputable: bool) -> str:
    src = f'{SRC_LIB}.{sub}.{leaf}' if sub else f'{SRC_LIB}.{leaf}'
    # `abbrev` for every kind, including theorems. Mathlib's `alias` would be the natural spelling
    # for a theorem, but the module that provides it is not in this toolchain's Mathlib, and an
    # `abbrev` is already what is needed: a real constant at the exact fully qualified name, of the
    # same type, reducible so a `simp` set or an `exact` written against the original sees through
    # it. For a proposition the type is the statement, so the name still behaves as the theorem.
    pre = 'noncomputable abbrev' if noncomputable else 'abbrev'
    return f'{pre} {leaf} := @{src}'


def shim_text(module: str, groups: dict[str, list[str]], siblings: list[str],
              real: dict[str, list[tuple[str, str, bool]]] | None = None) -> str:
    body = (['this module re-exports it under the names this corpus has always cited, so',
             'the Challenge, comparator and replay records of the eight entries are unaffected.']
            if groups else
            ['it declares into bare namespaces rather than into the library root, so the names this',
             'corpus cites are already the names it publishes and no alias is needed here.'])
    lines = [
        '-- SPDX-FileCopyrightText: 2026 Will Cook',
        '-- SPDX-License-Identifier: Apache-2.0',
        '/-',
        f'Compatibility shim. The mathematics lives in `{SRC_LIB}.{module}`, copied verbatim from the',
        'paper repository; ' + body[0],
        body[1],
        '',
        'Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.',
        '-/',
        f'import {SRC_LIB}.{module}',
    ]
    # The corpus module this replaces imported its siblings, and an entry that imported it saw
    # their names too. Importing `Erdos249257.<module>` alone would bring the library's names back
    # but not the aliases, so the shim imports the sibling shims as well and visibility is
    # unchanged. The list is the module's own imports on both sides, which is why regenerating over
    # an already generated shim reproduces it.
    lines += [f'import {DST_LIB}.{s}' for s in siblings]
    lines.append('')
    for sub in sorted(groups):
        names = sorted(groups[sub])
        dst_ns = f'{DST_LIB}.{sub}' if sub else DST_LIB
        src_ns = f'{SRC_LIB}.{sub}' if sub else SRC_LIB
        lines.append(f'namespace {dst_ns}')
        width = 0
        chunk: list[str] = []
        for n in names:
            chunk.append(n)
            width += len(n) + 1
            if width > 90:
                lines.append(f'export {src_ns} ({" ".join(chunk)})')
                chunk, width = [], 0
        if chunk:
            lines.append(f'export {src_ns} ({" ".join(chunk)})')
        for leaf, kind, nc in sorted((real or {}).get(sub, [])):
            lines.append(real_text(sub, leaf, kind, nc))
        lines.append(f'end {dst_ns}')
        lines.append('')
    for sub in sorted(set((real or {})) - set(groups)):
        dst_ns = f'{DST_LIB}.{sub}' if sub else DST_LIB
        lines.append(f'namespace {dst_ns}')
        for leaf, kind, nc in sorted(real[sub]):
            lines.append(real_text(sub, leaf, kind, nc))
        lines.append(f'end {dst_ns}')
        lines.append('')
    return '\n'.join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--paper-lean', required=True, type=Path,
                    help="the paper repository's `lean/` directory, which owns Erdos249257")
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    src_root = args.paper_lean / SRC_LIB
    if not src_root.is_dir():
        print(f'no {SRC_LIB} library under {args.paper_lean}', file=sys.stderr)
        return 2

    cited_real = cited_real_names()
    stale, written, skipped, realised = [], 0, [], []
    for src in sorted(src_root.rglob('*.lean')):
        rel = src.relative_to(src_root)
        module = rel.with_suffix('').as_posix().replace('/', '.')
        dst = REPO / DST_LIB / rel
        if not dst.is_file():
            continue                                  # corpus never carried this module
        if module in KEEP_REAL:
            continue
        src_text = src.read_text(encoding='utf-8', errors='ignore')
        dst_text = dst.read_text(encoding='utf-8', errors='ignore')
        names = declarations(src_text)
        groups: dict[str, list[str]] = {}
        for n in names:
            parts = n.split('.')
            if parts[0] != SRC_LIB:
                # Declared outside the library root, so the corpus copy carried this exact name and
                # the library already publishes it. Aliasing it would export a constant that is not
                # there.
                continue
            parts = parts[1:]
            if not parts:
                continue
            groups.setdefault('.'.join(parts[:-1]), []).append(parts[-1])
        for sub, name in MOVED.get(module, ()):
            groups.setdefault(sub, []).append(name)
        # Anything this module publishes that the corpus cites through `_root_.` becomes a real
        # declaration instead of an alias, and must not also be exported, or the name is declared
        # twice.
        kinds = declaration_kinds(src_text)
        real: dict[str, list[tuple[str, str, bool]]] = {}
        for sub in list(groups):
            keep = []
            for leaf in groups[sub]:
                qualified = f'{sub}.{leaf}' if sub else leaf
                if qualified in cited_real:
                    src_fqn = f'{SRC_LIB}.{qualified}'
                    kind, nc = kinds.get(src_fqn, ('theorem', False))
                    real.setdefault(sub, []).append((leaf, kind, nc))
                    realised.append(f'{DST_LIB}.{qualified}')
                else:
                    keep.append(leaf)
            if keep:
                groups[sub] = keep
            else:
                del groups[sub]
        if not groups:
            skipped.append(module)
        siblings = sorted(
            {m for m in IMPORT_RE.findall(src_text) if m.startswith(SRC_LIB + '.')} |
            {m.replace(DST_LIB + '.', SRC_LIB + '.', 1)
             for m in IMPORT_RE.findall(dst_text) if m.startswith(DST_LIB + '.')})
        siblings = [m.split('.', 1)[1] for m in siblings
                    if (REPO / DST_LIB / (m.split('.', 1)[1].replace('.', '/') + '.lean')).is_file()]
        body = shim_text(module, groups, siblings, real)
        if dst.read_text(encoding='utf-8', errors='ignore') != body:
            stale.append(dst.relative_to(REPO).as_posix())
            if not args.check:
                dst.write_text(body, encoding='utf-8')
                written += 1
    if args.check:
        for p in stale:
            print('stale:', p)
        print(f'{len(stale)} shim(s) out of date')
        return 1 if stale else 0
    print(f'wrote {written} shim(s); {len(skipped)} need no alias, only the import: {skipped}')
    print(f'{len(realised)} name(s) emitted as real declarations for `_root_.` citations: {realised}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
