import Solutions.PalomarCorpus.E269a

#print axioms PalomarCorpus.E269.PaperStatementsA.actual_cubic_no_crossing_strips
#print axioms PalomarCorpus.E269.PaperStatementsA.actual_weighted_strip_decomposition
#print axioms PalomarCorpus.E269.PaperStatementsA.admissible_modular_minors
#print axioms PalomarCorpus.E269.PaperStatementsA.clearingCondition_iff_max
#print axioms PalomarCorpus.E269.PaperStatementsA.dyadicBlockBase235_cases
#print axioms PalomarCorpus.E269.PaperStatementsA.dyadicBlockBase235_mem_interval
#print axioms PalomarCorpus.E269.PaperStatementsA.dyadicInternalPower_exponent_unique
#print axioms PalomarCorpus.E269.PaperStatementsA.exists_dyadicInternalPower_iff_log_succ
#print axioms PalomarCorpus.E269.PaperStatementsA.fixed_base_recoding_whole
#print axioms PalomarCorpus.E269.PaperStatementsA.literal_triangle_whole
#print axioms PalomarCorpus.E269.PaperStatementsA.log_dyadic_succ_eq_of_no_internalPower
#print axioms PalomarCorpus.E269.PaperStatementsA.paper_jump_count
#print axioms PalomarCorpus.E269.PaperStatementsA.paper_two_by_two_fixture
#print axioms PalomarCorpus.E269.PaperStatementsA.paper_uniform_rank_and_nonseparation
#print axioms PalomarCorpus.E269.PaperStatementsA.radix_eq_height_ratio
#print axioms PalomarCorpus.E269.PaperStatementsA.threePrimeHeight_dyadicBlock_succ
#print axioms PalomarCorpus.E269.PaperStatementsA.weighted_shift_whole
