import Solutions.ExternalVerification249ActualLcmOrbit
#print axioms Erdos249257.ExternalVerification249ActualLcmOrbit.actualLcmTailOrbit_eq_scaled_totientSeries_sub_prefix
#print axioms Erdos249257.ExternalVerification249ActualLcmOrbit.irrational_totientSeries_iff_actualLcmOrbitNonintegralitySupply
