import Solutions.ExternalVerification257PaperStatementsK

#print axioms Erdos249257.ExternalVerification257PaperStatementsK.paper_both_cofinal_statements_iff_half_membership
#print axioms Erdos249257.ExternalVerification257PaperStatementsK.paper_critical_crossing_support_is_greedy_prefix
#print axioms Erdos249257.ExternalVerification257PaperStatementsK.six_membership_conditions
