import ExternalVerification243PeriodicNegativeOrbit.Solution

#print axioms Erdos249257.ExternalVerification243PeriodicNegativeOrbit.no_phasePrimitivePeriodicNegative_orbit
#print axioms Erdos249257.ExternalVerification243PeriodicNegativeOrbit.no_periodicNegative_orbit
#print axioms Erdos249257.ExternalVerification243PeriodicNegativeOrbit.no_eventuallyPeriodicNegative_orbit
