import Solutions.ExternalVerification257PaperStatementsAC

#print axioms Erdos249257.ExternalVerification257PaperStatementsAC.arithmetic_logarithmic_counterexample
#print axioms Erdos249257.ExternalVerification257PaperStatementsAC.dyadicBandEscape_iff_exists_critical
#print axioms Erdos249257.ExternalVerification257PaperStatementsAC.exists_criticalDyadicBandIndex
#print axioms Erdos249257.ExternalVerification257PaperStatementsAC.logarithmic_initial_interval
#print axioms Erdos249257.ExternalVerification257PaperStatementsAC.no_absolute_dyadic_kappaOne_constant
