import Solutions.ExternalVerification257PaperStatementsAG

#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.coprime_base_den_finiteErdosSum
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.erdosSupportSeries_multiples_eq_pow_base_full_support
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_coeff_series_of_weighted_coeff_block_certificates
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSum_factorial_support
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSum_full_support
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSum_of_lcm_gap
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSum_two_pow_support
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_eventuallyPeriodic
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_multiples
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_odd
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_of_tail
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_pairwise_coprime
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_periodic
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_residueClass
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_erdosSupportSeries_tail_of_irrational
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_intWeightedErdosSeries_periodic_of_coeff_nonneg_of_frequently_ne_zero
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_intWeightedErdosSeries_periodic_of_coeff_nonpos_of_frequently_ne_zero
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.irrational_or_bpow_mul_eq_intCast_intWeightedErdosSeries_periodic
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.lcm_lt_den_finiteErdosSum
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.supportCoeff_le_card_divisors
#print axioms Erdos249257.ExternalVerification257PaperStatementsAG.supportCoeff_le_self
