import Solutions.ExternalVerification249CarryRankFrontier
namespace Erdos249257.ExternalVerification249CarryRankFrontier

#print axioms not_irrational_binaryCoeffSeries_iff_exists_temperedBinaryOrbit
#print axioms totient_carryKernel_diff
#print axioms finrank_canonicalCarryKernel_ge_of_certificate
#print axioms not_irrational_totientSeries_implies_unbounded_carryRank_unconditional
#print axioms carryShift_dvd_iff_tailDiff_mem_int
#print axioms not_irrational_totientSeries_implies_mod_period_and_unbounded_rank

end Erdos249257.ExternalVerification249CarryRankFrontier
