import Solutions.ExternalVerification269PaperStatementsB

#print axioms Erdos249257.ExternalVerification269PaperStatementsB.exponent_unique_real_base_short_interval
#print axioms Erdos249257.ExternalVerification269PaperStatementsB.no_bounded_positive_int_state_of_leastPositiveResidue
#print axioms Erdos249257.ExternalVerification269PaperStatementsB.real_two_prime_separation
