-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.AllBaseReciprocalSupportIrrationality`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.AllBaseReciprocalSupportIrrationality
import Erdos257PeriodNoncollapse.ReciprocalSupportIrrationality

namespace Erdos257PeriodNoncollapse
export Erdos249257 (exists_shiftedRadixSupportAtom_closeReturn_of_summable_reciprocal irrational_erdosSupportSeries_of_summable_reciprocal)
export Erdos249257 (shiftedRadixAtom shiftedRadixAtom_le_pow_mul_zero shiftedRadixAtom_nonneg shiftedRadixAtom_step)
export Erdos249257 (shiftedRadixAtom_sub_zero_le_two_mul_binary_sub_zero shiftedRadixAtom_zero shiftedRadixAtom_zero_le)
export Erdos249257 (shiftedRadixAtom_zero_lt_of_lt shiftedRadixSupportAtom shiftedRadixSupportAtom_step shiftedRadixSupportAtom_sub_zero_le_two_mul_binary_sub_zero)
export Erdos249257 (shiftedRadixSupportAtom_zero_strictMinimum summable_shiftedRadixSupportAtom tsum_shiftedRadixSupportAtom_step)
export Erdos249257 (tsum_shiftedRadixSupportAtom_zero)
end Erdos257PeriodNoncollapse
