-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.BinaryTailWindowTransfer`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.BinaryTailWindowTransfer
import Erdos257PeriodNoncollapse.GenericTailOrbitRigidity

namespace Erdos257PeriodNoncollapse
export Erdos249257 (BinaryCoeffTailEnvelope BinaryTailWindowLowerBound CoeffZeroWindow binaryCoeffTailEnvelope_two_mul_rpow)
export Erdos249257 (binaryCoeffTail_le_two_mul_rpow binaryTailWindowLowerBound_le_mul_envelope binaryTailWindowLowerBound_of_natState)
export Erdos249257 (coeffZeroWindow_one_iff coeffZeroWindow_zero exists_nat_two_le_inv_sub_one_le le_epsilon_mul_logb_add_constant_div_of_affine_log_bound)
export Erdos249257 (length_le_logb_of_binaryTailWindowLowerBound length_le_logb_of_pow_le_mul_add_invNat_rpow logb_nat_affine_le_add)
export Erdos249257 (logb_nat_succ_le_one_add nat_add_one_le_two_pow pow_sub_one_mul_le_of_pow_le_mul_add_invNat_rpow)
export Erdos249257 (state_eq_pow_mul_of_coeffZeroWindow summable_succ_div_two_pow tsum_succ_div_two_pow)
end Erdos257PeriodNoncollapse
