-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.BooleanMobiusCofinalExactRows`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.BooleanMobiusCofinalExactRows
import Erdos257PeriodNoncollapse.BooleanMobiusGlobalRepair
import Erdos257PeriodNoncollapse.BooleanMobiusGreedyReduction

namespace Erdos257PeriodNoncollapse
export Erdos249257 (CofinalExactLocalMersenneHalfRows ExactLocalMersenneHalfRow abs_exactLocalMersenneRowValue_sub_half_le)
export Erdos249257 (exactLocalMersenneRowValue exactLocalMersenneRowValue_mem_mersenneAchievementSet half_mem_mersenneAchievementSet_of_cofinalExactLocalRows)
end Erdos257PeriodNoncollapse
