-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.BooleanMobiusSkipRow`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.BooleanMobiusSkipRow
import Erdos257PeriodNoncollapse.BooleanMobiusCofinalExactRows
import Erdos257PeriodNoncollapse.BooleanMobiusSkippedCoreExactRow

namespace Erdos257PeriodNoncollapse
export Erdos249257 (exactLocalMersenneHalfRow_two_mul_sub_two_of_skippedCore exactLocalMersenneHalfRow_two_mul_sub_two_of_skippedCoreSharpCapacity)
export Erdos249257 (exists_exactRowStrictUpperFill_of_skippedCoreSharpCapacity localPrefixQuotient_upperSupportFromWord)
export Erdos249257 (strictUpperFill_filter_le_eq_core upperSupportFromWord upperSupportFromWord_le_top upperSupportFromWord_lower_bound)
end Erdos257PeriodNoncollapse
