-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.BooleanMobiusExactTransition`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.BooleanMobiusExactTransition
import Erdos257PeriodNoncollapse.BooleanMobiusLocalRepair

namespace Erdos257PeriodNoncollapse
export Erdos249257 (halfEndpointTarget halfEndpointTarget_succ localEndpointDefect localEndpointDefect_succ localMersenneQuotient_endpoint_succ)
export Erdos249257 (localPrefixQuotient_succ localPrefixQuotient_succ_eq_halfEndpointTarget_iff localRepairInteger_eq_localEndpointDefect_succ)
end Erdos257PeriodNoncollapse
