-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.BooleanMobiusSkipRowCofinal`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.BooleanMobiusSkipRowCofinal
import Erdos257PeriodNoncollapse.BooleanMobiusSkipRow
import Erdos257PeriodNoncollapse.HalfCylinderFullShellSeamBridge

namespace Erdos257PeriodNoncollapse
export Erdos249257 (CofinalPositiveHalfGreedySkips cofinalExactLocalMersenneHalfRows_of_positiveHalfGreedySkips)
export Erdos249257 (cofinalPositiveHalfGreedySkips_iff_half_mem exactLocalMersenneHalfRow_of_positiveHalfGreedySkip)
export Erdos249257 (greedyMersenneRemainderRat_half_pos half_mem_mersenneAchievementSet_of_positiveHalfGreedySkips)
end Erdos257PeriodNoncollapse
