-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.BooleanMobiusSkippedCoreExactRow`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.BooleanMobiusSkippedCoreExactRow
import Erdos257PeriodNoncollapse.BooleanMobiusLocalRepair

namespace Erdos257PeriodNoncollapse
export Erdos249257 (card_le_sub_two_of_mem_lt exists_upperHalfBooleanWord_of_skippedCore localBinarySuffix_two_mul_sub_two_lt_upperHalfCapacity)
export Erdos249257 (localFractionMass_le_card_skippedCore localMersenneFraction_lt_one_skippedCore localMersenneQuotient_two_mul_sub_two_self)
end Erdos257PeriodNoncollapse
