-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.FirstHarmonicGap`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.FirstHarmonicGap
import Erdos257PeriodNoncollapse.LcmConeFlatness

namespace Erdos257PeriodNoncollapse.TotientTailPeriodKiller
export Erdos249257.TotientTailPeriodKiller (exists_certifiedKill_of_first_harmonic_gap exists_certifiedKill_of_first_harmonic_gap_subset)
export Erdos249257.TotientTailPeriodKiller (windowFirstCos)
end Erdos257PeriodNoncollapse.TotientTailPeriodKiller
