-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.GcdMomentCalculus`, copied verbatim from the
paper repository; it declares into bare namespaces rather than into the library root, so the names this
corpus cites are already the names it publishes and no alias is needed here.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.GcdMomentCalculus
import Erdos257PeriodNoncollapse.GeometricCoprimality
