-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderFinalMiddleCellEscape`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderFinalMiddleCellEscape
import Erdos257PeriodNoncollapse.HalfCylinderFatalGapRightTail
import Erdos257PeriodNoncollapse.HalfCylinderProducerLowerBound

namespace Erdos257PeriodNoncollapse
export Erdos249257 (cofiniteRightTail_ne_zero_centeredEndpoint finalMiddleCell_neg_three_not_last integerHalfCarry_union_Ioi_eq_producerCarry_add_four)
export Erdos249257 (mobiusCenteredHalfCarry_add_two mobiusCenteredHalfCarry_add_two_mul mobiusCenteredHalfCarry_nonneg_of_supportSeries_lt_half)
export Erdos249257 (mobiusCenteredHalfCarry_union_Ioi_eq_producerCarry_add_three pairedCenteredForcing positiveMersenneSupportValue_union_Ioi_eq_add_tail)
export Erdos249257 (two_le_supportCoeff_two_mul_add_four_of_Ioi_subset)
end Erdos257PeriodNoncollapse
