-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderProducerCarrySocket`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderProducerCarrySocket
import Erdos257PeriodNoncollapse.BooleanMobiusCarry
import Erdos257PeriodNoncollapse.GreedyAchievementSet

namespace Erdos257PeriodNoncollapse
export Erdos249257 (mersenneGap_lt_eight_div_four_pow_succ producerCarry producerCarry_gt_tail_iff_supportSeries_lt_half)
export Erdos249257 (producerCarry_le_neg_eight_forces_belowTail_gt_half producerCarry_le_neg_eight_forces_gap_margin)
export Erdos249257 (producerCarry_linear_sufficient producerCarry_lt_tail_iff_half_lt_supportSeries producerCarry_neg_forces_half_lt_supportSeries)
export Erdos249257 (producerCarry_residual_identity producerCarry_sqrt_sufficient)
end Erdos257PeriodNoncollapse
