-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfGreedyFatalGap`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfGreedyFatalGap
import Erdos257PeriodNoncollapse.GreedyAchievementSet

namespace Erdos257PeriodNoncollapse.HalfGreedyFatalGap
export Erdos249257.HalfGreedyFatalGap (mersenneTailLB3 mersenneTailLB3_lt_mersenneTail sharp_of_dyadic sharp_strictly_stronger skipSafe_actualTail_of_two_mul_le_three_mul)
export Erdos249257.HalfGreedyFatalGap (skipSafe_of_two_mul_le_three_mul three_div_lt_mersenneTailLB3 three_le_of_actualTail_fatal_of_odd)
export Erdos249257.HalfGreedyFatalGap (three_le_of_fatal_of_odd three_mul_lt_two_mul_of_actualTail_fatal three_mul_lt_two_mul_of_fatal)
export Erdos249257.HalfGreedyFatalGap (two_le_of_fatal unitNumerator_skipSafe unitNumerator_skipSafe_actualTail)
end Erdos257PeriodNoncollapse.HalfGreedyFatalGap
