-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderFinalMiddleTailSocket`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderFinalMiddleTailSocket
import Erdos257PeriodNoncollapse.HalfCylinderFinalMiddleCellEscape

namespace Erdos257PeriodNoncollapse
export Erdos249257 (binaryCoeffTail_lt_integerHalfCarry_of_supportSeries_lt_half binaryCoeffTail_union_Ioi_lt_producerCarry_add_four)
export Erdos249257 (binaryCoeffTail_union_Ioi_lt_three_of_producerCarry_eq_neg_one binaryCoeffTail_union_Ioi_lt_two_of_producerCarry_eq_neg_two)
end Erdos257PeriodNoncollapse
