-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderSkippedRankLimit`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderSkippedRankLimit
import Erdos257PeriodNoncollapse.HalfCylinderSeamLimit

namespace Erdos257PeriodNoncollapse
export Erdos249257 (SeamGreedyUnboundedSkippedRanksAlong half_mem_mersenneAchievementSet_of_unboundedSkippedRanks)
export Erdos249257 (integerGreedyRemainder_lt_of_get?_eq_false seamGreedyNormalizedRemainder_lt_mersenneWeight_of_false)
export Erdos249257 (seamGreedyRemainderSubquadraticAlong_of_unboundedSkippedRanks seamIntegerGreedyRemainder_lt_truncatedWeight_of_false)
export Erdos249257 (tendsto_mersenneWeight_atTop_zero)
end Erdos257PeriodNoncollapse
