-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderBoundaryPulse`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderBoundaryPulse
import Erdos257PeriodNoncollapse.HalfCylinderLargestSkipGap

namespace Erdos257PeriodNoncollapse
export Erdos249257 (exists_lowerPrefix_wordPulse_eq_of_largestFalse_late late_firstCrossing_boundary not_dvd_two_mul_add_one_of_late_strictSuffix)
export Erdos249257 (not_dvd_two_mul_add_two_of_late_strictSuffix rowPulse_boundary_of_late_firstCrossing rowPulse_eq_one_of_boundary_two)
export Erdos249257 (rowPulse_eq_two_of_boundary_one rowPulse_eq_zero_of_late_strictSuffix wordPulse_eq_sum_seamWordSupport)
end Erdos257PeriodNoncollapse
