-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderSeamProducerAlignment`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderSeamProducerAlignment
import Erdos257PeriodNoncollapse.HalfCylinderFiniteShadow
import Erdos257PeriodNoncollapse.HalfCylinderProducerCarrySocket

namespace Erdos257PeriodNoncollapse
export Erdos249257 (producerCarry_insert_eq_four_mul_shiftedHole_sub_pulse)
end Erdos257PeriodNoncollapse
