-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderResetDeficitEscape`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderResetDeficitEscape
import Erdos257PeriodNoncollapse.HalfCylinderLargestSkipGap

namespace Erdos257PeriodNoncollapse
export Erdos249257 (rightBranch_remainder_succ_eq rightBranch_remainder_window seamAdjacentCut_abovePulse_le seamAdjacentCut_belowPulse_le)
export Erdos249257 (seamAdjacentCut_gap_eq seamAdjacentCut_terminalWeight_eq seamGreedy_weight_add_remainder seamGreedy_weight_eq_largestSkipLowerWord)
export Erdos249257 (successorCarries_of_twelve_mul_remainder_ge three_mul_remainder_lt_exactLateGap upperOrMiddle_of_four_mul_remainder_lt)
export Erdos249257 (upperOrMiddle_within_of_two_pow_deficit)
end Erdos257PeriodNoncollapse
