-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderSeamLimit`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderSeamLimit
import Erdos257PeriodNoncollapse.HalfCylinderFloorErrorReset

namespace Erdos257PeriodNoncollapse
export Erdos249257 (SeamGreedyRemainderGapBound SeamGreedyRemainderSubquadraticAlong half_mem_mersenneAchievementSet_of_seamRemainderGapBound)
export Erdos249257 (half_mem_mersenneAchievementSet_of_subquadraticAlong seamGreedyFiniteValue seamGreedyFiniteValue_eq_cast_rationalSum)
export Erdos249257 (seamGreedyFiniteValue_error_bounds seamGreedyFiniteValue_general_error_bounds seamGreedyFiniteValue_mem_achievementSet)
export Erdos249257 (seamGreedyNormalizedRemainder seamGreedyRationalRemainder_bounds seamGreedyRationalRemainder_general_bounds)
export Erdos249257 (tendsto_seamGreedyFiniteValue_half tendsto_seamGreedyFiniteValue_half_of_subquadraticAlong)
export Erdos249257 (zero_not_mem_seamWordSupport)
end Erdos257PeriodNoncollapse
