-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderLargestSkipInduction`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderLargestSkipInduction
import Erdos257PeriodNoncollapse.HalfCylinderLargestSkipGap

namespace Erdos257PeriodNoncollapse
export Erdos249257 (LargestSkipLateAt LargestSkipLateStepSocket half_mem_mersenneAchievementSet_of_largestSkipLateStepSocket)
export Erdos249257 (largestSkipLateAt_fourteen largestSkipLateAt_of_stepSocket seamGreedyUnboundedSkippedRanksAlong_of_largestSkipLateStepSocket)
end Erdos257PeriodNoncollapse

namespace Erdos257PeriodNoncollapse.LargestSkipLateStepSocket
export Erdos249257.LargestSkipLateStepSocket (largestSkipLateAt_succ)
end Erdos257PeriodNoncollapse.LargestSkipLateStepSocket
