-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderFalseBitSupply`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderFalseBitSupply
import Erdos257PeriodNoncollapse.HalfCylinderSkippedRankLimit

namespace Erdos257PeriodNoncollapse
export Erdos249257 (half_mem_mersenneAchievementSet_of_cofinalTerminalFalse half_mem_mersenneAchievementSet_of_unboundedTerminalFalse)
export Erdos249257 (seamGreedyUnboundedSkippedRanksAlong_succ_of_cofinalTerminalFalse)
end Erdos257PeriodNoncollapse
