-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.HalfCylinderProducerLowerBound`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.HalfCylinderProducerLowerBound
import Erdos257PeriodNoncollapse.HalfCylinderBoundaryPulse
import Erdos257PeriodNoncollapse.HalfCylinderSeamProducerAlignment

namespace Erdos257PeriodNoncollapse
export Erdos249257 (pairedSupportCoeff_insert_terminal_eq_wordPulse producerCarry_insert_seamAboveSupport_eq_neg_upperCoordinate)
export Erdos249257 (producerCarry_insert_seamBelowSupport_eq_middleCoordinate producerCarry_insert_seamWordSupport_eq)
export Erdos249257 (wordPulse_eq_pairedSupportCoeff)
end Erdos257PeriodNoncollapse
