-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.PrimePowerJumpDynamics`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.PrimePowerJumpDynamics
import Erdos257PeriodNoncollapse.CyclotomicProjectionOfShadow

namespace Erdos257PeriodNoncollapse.PrimePowerJumpDynamics
export Erdos249257.PrimePowerJumpDynamics (cyclotomic_dvd_primeJump_new_fibre cyclotomic_dvd_primeJump_new_fibre_constant cyclotomic_dvd_primeJump_old_fibre)
export Erdos249257.PrimePowerJumpDynamics (expand_spacedRepunit mobiusNumeratorPolynomial_mul_prime mobiusNumeratorPolynomial_mul_prime_comp)
export Erdos249257.PrimePowerJumpDynamics (mobiusNumeratorPolynomial_mul_prime_eval mobiusNumeratorPolynomial_prime_mul mobiusNumeratorPolynomial_six_fixture)
export Erdos249257.PrimePowerJumpDynamics (mobiusNumeratorPolynomial_two_fixture primeJump_new_fibre_six_factorization primeJump_old_fibre_two_factorization)
end Erdos257PeriodNoncollapse.PrimePowerJumpDynamics
