-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.PrimitiveSupportBridge`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.PrimitiveSupportBridge
import Erdos257PeriodNoncollapse.BooleanMobiusCarry

namespace Erdos257PeriodNoncollapse
export Erdos249257 (binaryCoeffTail_supportCoeff_eq_prefix_add_residual divisor_eq_self_of_cutoff_lt_of_le_two_mul)
export Erdos249257 (nextSupport_power_bound prefixDenominator_shell_power_bound primitiveBit primitiveCrossCarry)
export Erdos249257 (primitiveCrossCarry_eq_residualTail primitiveCrossCarry_first_shell_recurrence primitiveCrossCarry_pos)
export Erdos249257 (primitivePrefix primitiveResidual scaledPrefixCarry scaledSupportCarry supportCoeff_eq_primitivePrefix_add_residual)
export Erdos249257 (supportCoeff_primitiveResidual_first_shell)
end Erdos257PeriodNoncollapse
