-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.RadicalMobiusShadow`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.RadicalMobiusShadow

namespace Erdos257PeriodNoncollapse.RadicalMobiusShadow
export Erdos249257.RadicalMobiusShadow (baseMobiusShadow baseMobiusShadow_den baseMobiusShadow_den_of_gcd_eq baseMobiusShadow_den_prime)
export Erdos249257.RadicalMobiusShadow (baseMobiusShadow_den_twicePrime mersenne mobiusNumerator mobiusNumerator_prime mobiusNumerator_prime_gcd)
export Erdos249257.RadicalMobiusShadow (mobiusNumerator_twicePrime mobiusNumerator_twicePrime_gcd numericMobiusShadow numericMobiusShadow_radical)
export Erdos249257.RadicalMobiusShadow (prime5_den_fixture prime5_numerator_fixture prime_dvd_squarefreeKernel_iff radical210_den_fixture)
export Erdos249257.RadicalMobiusShadow (radical210_gcd_fixture radical210_numerator_fixture scaledMobiusShadow_eq_radicalBase scaledMobiusShadow_eq_radicalNumerator)
export Erdos249257.RadicalMobiusShadow (squarefreeKernel squarefreeKernel_dvd squarefreeKernel_idem squarefreeKernel_pos squarefreeKernel_primeFactors)
export Erdos249257.RadicalMobiusShadow (squarefreeKernel_squarefree twicePrime5_den_fixture twicePrime5_gcd_fixture twicePrime5_numerator_fixture)
end Erdos257PeriodNoncollapse.RadicalMobiusShadow
