-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.RationalDenominatorSurvival`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.RationalDenominatorSurvival

namespace Erdos257PeriodNoncollapse.RationalDenominatorSurvival
export Erdos249257.RationalDenominatorSurvival (divisor_dvd_divInt_den survivingDivisor_dvd_scaled_divInt_den)
end Erdos257PeriodNoncollapse.RationalDenominatorSurvival
