-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.RepunitMobiusNumerator`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.RepunitMobiusNumerator
import Erdos257PeriodNoncollapse.RadicalMobiusShadow

namespace Erdos257PeriodNoncollapse.RepunitMobiusNumerator
export Erdos249257.RepunitMobiusNumerator (gcdWord gcdWordCoeff gcdWordCoeff_pos gcdWord_coeff_eq_zero_of_le gcdWord_coeff_of_lt mobiusNumeratorPolynomial)
export Erdos249257.RepunitMobiusNumerator (mobiusNumeratorPolynomial_coeff mobiusNumeratorPolynomial_coeff_nonneg mobiusNumeratorPolynomial_coeff_pos)
export Erdos249257.RepunitMobiusNumerator (mobiusNumeratorPolynomial_eq_gcdWord mobiusNumeratorPolynomial_eval_two spacedRepunit sum_divisors_moebius_ratio_eq_baseMobiusShadow)
export Erdos249257.RepunitMobiusNumerator (sum_divisors_moebius_ratio_eq_scaledMobiusShadow)
end Erdos257PeriodNoncollapse.RepunitMobiusNumerator
