-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.TerminalOnlyCofinal`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.TerminalOnlyCofinal
import Erdos257PeriodNoncollapse.HalfCarryReachability

namespace Erdos257PeriodNoncollapse.HalfCarryReachability
export Erdos249257.HalfCarryReachability (HalfCarryCofinalTerminalOnlyStrip HalfTerminalOnlyStripWitness dist_half_erdosSupportSeries_wordSupport_le_of_terminalOnlyWitness)
export Erdos249257.HalfCarryReachability (exists_infinite_support_half_of_cofinalTerminalOnlyStrip half_mem_mersenneAchievementSet_of_cofinalTerminalOnlyStrip)
export Erdos249257.HalfCarryReachability (one_not_mem_wordSupport_of_terminalOnlyWitness zero_not_mem_wordSupport_of_terminalOnlyWitness)
end Erdos257PeriodNoncollapse.HalfCarryReachability
