-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.TotientActualLcmOrbitNonintegrality`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.TotientActualLcmOrbitNonintegrality
import Erdos257PeriodNoncollapse.TotientActualLcmOrbitSeparation

namespace Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine
export Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine (PowerTwoActualLcmOrbitNonintegralitySupply actualLcmTailOrbit_notMem_int_of_irrational irrational_totientSeries_iff_actualLcmOrbitNonintegralitySupply)
export Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine (irrational_totientSeries_of_actualLcmOrbitNonintegralitySupply)
end Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine
