-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.TotientActualLcmOrbitSign`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.TotientActualLcmOrbitSign
import Erdos257PeriodNoncollapse.TotientActualLcmOrbitArithmetic
import Erdos257PeriodNoncollapse.TotientTailCarryPeriod

namespace Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine
export Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine (actualLcmTailDiff_shift_pos actualLcmTailOrbit_integralRepresentative_pos actualLcmTailOrbit_pos)
export Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine (actualLcm_integral_forces_topEdgeResidue actualLcm_trueEndpointSurvivor_neg)
end Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine
