-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.TotientTailPeriodKiller`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.TotientTailPeriodKiller

namespace Erdos257PeriodNoncollapse.TotientTailPeriodKiller
export Erdos249257.TotientTailPeriodKiller (certifiedKill certifiedKill_all_small certifiedKill_depth_floor eventual_period_of_not_irrational)
export Erdos249257.TotientTailPeriodKiller (irrational_totient_series_of_certificate_supply summable_totientTail_terms summable_totient_div_two_pow)
export Erdos249257.TotientTailPeriodKiller (tail_after_le tail_after_nonneg tail_diff_int_of_den_dvd tail_diff_notMem_int_of_certifiedKill)
export Erdos249257.TotientTailPeriodKiller (tail_diff_not_int_small totientPrefix totientTail totientTail_eq_partial_add_tail totient_series_ne_rat_of_den_dvd)
export Erdos249257.TotientTailPeriodKiller (two_pow_mul_totient_series_eq windowDiscrepancy windowDiscrepancy_div_eq)
end Erdos257PeriodNoncollapse.TotientTailPeriodKiller
