-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.TropicalCurvatureCarry`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.TropicalCurvatureCarry
import Erdos257PeriodNoncollapse.CurvatureCarry

namespace Erdos257PeriodNoncollapse.TotientTailPeriodKiller
export Erdos249257.TotientTailPeriodKiller (VUCompatible VUOrbit VUSymbol fixedPrecisionTropicalNoGo vuBaseDigit vuCentredStep vuModulus)
export Erdos249257.TotientTailPeriodKiller (vuModulus_eq_two_mul_radius vuRadius vu_step_has_centred_completion vu_word_has_prefix_locked_completion)
end Erdos257PeriodNoncollapse.TotientTailPeriodKiller
