-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.TwentyOneQuotientCompactness`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import Erdos249257.TwentyOneQuotientCompactness
import Erdos257PeriodNoncollapse.BooleanMobiusGlobalRepair

namespace Erdos257PeriodNoncollapse
export Erdos249257 (TwentyOneEvenQuotientWindowSupply abs_localMersennePrefixValue_sub_one_div_twenty_one_le one_div_twenty_one_mem_mersenneAchievementSet_of_evenQuotientWindow)
export Erdos249257 (scaled_localMersennePrefixValue_sub_one_div_twenty_one scaled_one_div_twenty_one_eq_target_add_fraction)
export Erdos249257 (tendsto_twentyOne_evenQuotientWindow_error twentyOneQuotientDefect twentyOneQuotientTarget)
export Erdos249257 (twentyOneTargetFraction twentyOneTargetFraction_lt_one twentyOneTargetFraction_nonneg)
end Erdos257PeriodNoncollapse
