import Solutions.ExternalVerification249ParityPerturbedRationalControl

#print axioms Erdos249257.ExternalVerification249ParityPerturbedRationalControl.parity_perturbed_rational_control
#print axioms Erdos249257.ExternalVerification249ParityPerturbedRationalControl.control_series
#print axioms Erdos249257.ExternalVerification249ParityPerturbedRationalControl.not_irrational_control
#print axioms Erdos249257.ExternalVerification249ParityPerturbedRationalControl.control_temperedOrbit_carryRank_unbounded
#print axioms Erdos249257.ExternalVerification249ParityPerturbedRationalControl.finrank_canonicalCarryKernel_ge_of_oddAgree
