import Solutions.PalomarCorpus.E257ae

#print axioms PalomarCorpus.E257.PaperStatementsAE.affineBinaryOrbit_mod_twoPow_eq
#print axioms PalomarCorpus.E257.PaperStatementsAE.balancedPulse_endpoint_fanout
#print axioms PalomarCorpus.E257.PaperStatementsAE.balancedPulse_label_card_lower_bound
#print axioms PalomarCorpus.E257.PaperStatementsAE.balancedPulse_no_autonomous_decoder
#print axioms PalomarCorpus.E257.PaperStatementsAE.balancedPulse_weighted_pair
#print axioms PalomarCorpus.E257.PaperStatementsAE.binaryCoeffSeries_rational_iff_exists_temperedBinaryOrbit
#print axioms PalomarCorpus.E257.PaperStatementsAE.binaryCoeffTail_div_pow_tendsto_zero
#print axioms PalomarCorpus.E257.PaperStatementsAE.binaryCoeffTail_le
#print axioms PalomarCorpus.E257.PaperStatementsAE.binaryCoeffTail_nonneg
#print axioms PalomarCorpus.E257.PaperStatementsAE.not_irrational_binaryCoeffSeries_iff_exists_temperedBinaryOrbit
#print axioms PalomarCorpus.E257.PaperStatementsAE.temperedBinaryOrbit_eq_scaledTail
