import Solutions.PalomarCorpus.E249_33

#print axioms PalomarCorpus.E249.PaperStructuresS.linearIndependent_one_and_least_residue_values
#print axioms PalomarCorpus.E249.PaperStructuresS.positiveRadixValue_eq_of_even_constant
#print axioms PalomarCorpus.E249.PaperStructuresS.radix_residue_series_irrational
#print axioms PalomarCorpus.E249.PaperStructuresS.rational_mixed_moduli_with_constant_iff
#print axioms PalomarCorpus.E249.PaperStructuresS.rational_zmod_radix_observable_iff
#print axioms PalomarCorpus.E249.PaperStructuresT.irrational_totient_series_of_goodBase_gap
#print axioms PalomarCorpus.E249.PaperStructuresU.irrational_totient_series_of_support_gap
#print axioms PalomarCorpus.E249.PrefixTwoAdicExclusion.oddPart_mul_prefixTail_eq_intCast
#print axioms PalomarCorpus.E249.PrefixTwoAdicExclusion.prefix_twoAdic_denominator_exclusion
#print axioms PalomarCorpus.E249.PrefixTwoAdicExclusion.prefix_twoAdic_denominator_lower_bound
#print axioms PalomarCorpus.E249.PrefixTwoAdicExclusion.prefix_twoAdic_odd_denominator_floor
#print axioms PalomarCorpus.E249.PrefixTwoAdicExclusion.totientPrefix_eq_corpusForm
#print axioms PalomarCorpus.E249.PrefixTwoAdicExclusion.totientPrefix_succ
#print axioms PalomarCorpus.E249.RankOneSharpFloor.not_forall_rankOneSubrankQuotient_sub_theta_two_gt_one_div_fifteen
#print axioms PalomarCorpus.E249.RankOneSharpFloor.primitive_form_abs_gt_twentyOne_div_threeTwenty
#print axioms PalomarCorpus.E249.RankOneSharpFloor.rankOneSubrankQuotient_ge_one_five
#print axioms PalomarCorpus.E249.RankOneSharpFloor.rankOneSubrankQuotient_sub_theta_two_gt_one_div_sixteen
