import Solutions.PalomarCorpus.E251_06

#print axioms PalomarCorpus.E251.ActualPrimeGapTail.exists_rationalPrimeGapTailState_representation_of_not_irrational
#print axioms PalomarCorpus.E251.ActualPrimeGapTail.rationalPrimeGapTailShift_eventuallyIntegral
#print axioms PalomarCorpus.E251.ActualPrimeGapTail.rationalPrimeGapTailState_recurrence
#print axioms PalomarCorpus.E251.ActualPrimeGapTail.rationalPrimeGapTail_has_positive_shift_not_eventually_small
#print axioms PalomarCorpus.E251.AffineCircularity.adjacent_small_mismatch_iff_signed_two_window
#print axioms PalomarCorpus.E251.AffineCircularity.cofinal_affinePowTwo_escape_iff_not_eventuallyIntegral
#print axioms PalomarCorpus.E251.AffineCircularity.cofinal_blockResidue_escape_iff_not_eventuallyIntegral
#print axioms PalomarCorpus.E251.AllResidueLogarithmicCountermodel.exists_every_residue_logarithmic_countermodel
#print axioms PalomarCorpus.E251.FreePairEquivalence.cofinalFreePairNonintegral_iff_cofinalNonintegralTailShifts
#print axioms PalomarCorpus.E251.FreePairEquivalence.exists_free_pair_lattice
#print axioms PalomarCorpus.E251.FreePairEquivalence.free_pair_integral_iff_modEq
#print axioms PalomarCorpus.E251.FreePairEquivalence.irrational_initial_iff_cofinalFreePairNonintegral
#print axioms PalomarCorpus.E251.FreePairEquivalence.irrational_primeGap_tsum_iff_cofinalFreePairNonintegral
#print axioms PalomarCorpus.E251.FreePairEquivalence.primeGapRealTail_recurrence
#print axioms PalomarCorpus.E251.FreePairEquivalence.primeGapRealTail_zero
#print axioms PalomarCorpus.E251.KernelDenominatorFloor.cert_10000
#print axioms PalomarCorpus.E251.KernelDenominatorFloor.den_bound_of_certCheck
#print axioms PalomarCorpus.E251.KernelDenominatorFloor.kernel_denominator_floor
#print axioms PalomarCorpus.E251.KernelDenominatorFloor.kernel_denominator_floor_primeGap
#print axioms PalomarCorpus.E251.LcmDiagonalCriterion.notIrrationalInitial_iff_exists_integral_positive_tailShift
