import Solutions.ExternalVerification1041CriticalGeometry

#print axioms Erdos249257.ExternalVerification1041CriticalGeometry.criticalGeometricMean_twoRootProximity
#print axioms Erdos249257.ExternalVerification1041CriticalGeometry.criticalDiskInverseBalance_twoRootProximity
#print axioms Erdos249257.ExternalVerification1041CriticalGeometry.criticalDiskInverseBalance_twoRootProximity_strict
#print axioms Erdos249257.ExternalVerification1041CriticalGeometry.nearestSpoke_unique_nearest_spoke_escapes
#print axioms Erdos249257.ExternalVerification1041CriticalGeometry.allStraightCubic_every_pair_midpoint_escapes
