import Solutions.PalomarCorpus.E249bb

#print axioms PalomarCorpus.E249.PaperStatementsBB.canonicalTotientKernelFamily_entries
#print axioms PalomarCorpus.E249.PaperStatementsBB.canonicalTotientKernelFamily_independent_card_and_span
#print axioms PalomarCorpus.E249.PaperStatementsBB.canonical_family_basis_through_level
#print axioms PalomarCorpus.E249.PaperStatementsBB.canonical_level_zero_channels
#print axioms PalomarCorpus.E249.PaperStatementsBB.card_canonical_dyadic_index
#print axioms PalomarCorpus.E249.PaperStatementsBB.completeLevelZeroTruncation_is_totient_and_rank_one
#print axioms PalomarCorpus.E249.PaperStatementsBB.finrank_throughLevel_zero_eq_one
#print axioms PalomarCorpus.E249.PaperStatementsBB.linearIndependent_canonical_dyadic_family
#print axioms PalomarCorpus.E249.PaperStatementsBB.retainedSections_basis_and_rank
