import Solutions.PalomarCorpus.E1049_03

#print axioms PalomarCorpus.E1049.AdelicHeightBridge.coeff_zudilinNormalizedHankelDet_all_rat
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.exists_distinct_binary_selectors_same_fourJet_of_power_certificate
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.exists_distinct_binary_selectors_same_fourJet_of_rank_41
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.exists_ne_map_eq_map_ne_of_card_mul_lt
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.fourJet_card_gt_two_pow_of_rank_41
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.threeHalves_hankelChargeThreshold_lt_eightFortyOne
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.threeHalves_rectangular_hp_gap_gt_threeThirteenths
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.threePow_fortyOne_lt_twoPow_sixtyFive
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.three_two_scalar_margin_lt_explicit
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.twoPow_sixtyFour_lt_threePow_fortyOne
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.zudilinScalarContent_cannot_meet_required_charge
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.zudilinScalarPlusBorder_cannot_meet_required_charge
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.zudilinSharpHankelOrderAndCoeff_algebraicAssembly
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.zudilinSharpHankelOrderAndCoeff_all
#print axioms PalomarCorpus.E1049.AdelicHeightBridge.zudilin_firstTransformedRow_initialMonomial
#print axioms PalomarCorpus.E1049.PaperStatementsK.charge_ceilings
#print axioms PalomarCorpus.E1049.PaperStatementsK.power_bracket
#print axioms PalomarCorpus.E1049.PaperStatementsN.height_and_hankel_deficits
