import Solutions.ExternalVerification269PaperStatementsF

#print axioms Erdos249257.ExternalVerification269PaperStatementsF.firstClearingIndex_le_sufficient
#print axioms Erdos249257.ExternalVerification269PaperStatementsF.firstClearingIndex_minimal
#print axioms Erdos249257.ExternalVerification269PaperStatementsF.firstClearingIndex_spec
#print axioms Erdos249257.ExternalVerification269PaperStatementsF.long_window_growth
#print axioms Erdos249257.ExternalVerification269PaperStatementsF.scaled_state_is_integer_iff_firstClearingIndex_le
