import Solutions.ExternalVerification257PaperStatementsBD

#print axioms Erdos249257.ExternalVerification257PaperStatementsBD.balancedPulseCoeff_injective
#print axioms Erdos249257.ExternalVerification257PaperStatementsBD.four_le_halfStripBound
#print axioms Erdos249257.ExternalVerification257PaperStatementsBD.paper_balanced_pulse_fanout_is_radius_succ
#print axioms Erdos249257.ExternalVerification257PaperStatementsBD.paper_balanced_pulse_fanout_unbounded_corrected
#print axioms Erdos249257.ExternalVerification257PaperStatementsBD.paper_pulse_family_finite_state_card
#print axioms Erdos249257.ExternalVerification257PaperStatementsBD.paper_pulse_family_no_autonomous_decoder
