import Solutions.PalomarCorpus.E249_06

#print axioms PalomarCorpus.E249.PaperStatementsAE.signed_dyadic_clearing
#print axioms PalomarCorpus.E249.PaperStatementsAE.signed_dyadic_sum_ne_zero
#print axioms PalomarCorpus.E249.PaperStatementsAF.scaled_dyadic_sum_odd
#print axioms PalomarCorpus.E249.PaperStatementsAR.lcmHeight_scaledMobiusShadow_den_exact
#print axioms PalomarCorpus.E249.PaperStatementsG.historical_table_size_and_initial_depths
#print axioms PalomarCorpus.E249.PaperStatementsG.sixteen_certificate_windows
#print axioms PalomarCorpus.E249.PaperStatementsG.small_certificate_windows
#print axioms PalomarCorpus.E249.PaperStatementsI.historical_table_and_complete_band
#print axioms PalomarCorpus.E249.PaperStatementsI.sixteen_certificates_and_exclusions
#print axioms PalomarCorpus.E249.PaperStatementsI.small_certificates_and_exclusions
