-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
/-
Compatibility shim. The mathematics lives in `Erdos249257.MersenneTailAtoms`, copied verbatim from the
paper repository; this module re-exports it under the names this corpus has always cited, so
the Challenge, comparator and replay records of the eight entries are unaffected.

Generated by `scripts/generate_fork_alias_shims.py`. Do not edit by hand.
-/
import P2M_Erdos257_20260927.Erdos249257.MersenneTailAtoms
import P2M_Erdos257_20260927.Erdos257PeriodNoncollapse.MersenneLambertLadder

namespace P2M_Erdos257_20260927

namespace Erdos257PeriodNoncollapse
export Erdos249257 (det_mersenneAtomMatrix mersenneAtomMatrix mersenneAtomNumeratorMatrix mersenneAtom_denominatorProduct_mul_det)
export Erdos249257 (mersenneTailAtom mersenneTailAtom_step one_le_abs_mersenneAtom_cleared_det one_le_abs_weightedMersenneAtom_cleared_det)
export Erdos249257 (weightedMersenneAtomMatrix weightedMersenneAtom_denominatorProduct_mul_det)
end Erdos257PeriodNoncollapse

end P2M_Erdos257_20260927
