import Solutions.PalomarCorpus.E257_14

#print axioms PalomarCorpus.E257.PaperStatementsAT.binaryCoeffTail_supportCoeff_coe_finset_le_card
#print axioms PalomarCorpus.E257.PaperStructuresCE.exists_seamWord_minimal_above
#print axioms PalomarCorpus.E257.PaperStructuresCE.integerGreedyBits_length
#print axioms PalomarCorpus.E257.PaperStructuresCE.middleProducer_allRight_forces_carry_lt_tail
#print axioms PalomarCorpus.E257.PaperStructuresCE.producerCarry_insert_seamBelowSupport_eq_middleCoordinate
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamAboveWord_minimal
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamAboveWord_strict
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamAdjacentCut_below_admissible
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamAdjacentCut_below_maximal
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamPerturbedFamily_gap_pos
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamPerturbedFamily_oldSum_injective
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamPerturbedFamily_separated
#print axioms PalomarCorpus.E257.PaperStructuresCE.seamWeights_length_eq
#print axioms PalomarCorpus.E257.PaperStructuresCE.wordPulse_le
