import Solutions.ExternalVerification68AdjacentUnitCarryWindow
#print axioms Erdos249257.ExternalVerification68AdjacentUnitCarryWindow.consecutive_unit_carries_iff_positive_offset_le_den
#print axioms Erdos249257.ExternalVerification68AdjacentUnitCarryWindow.twoStep_den_mul_transitionNormalizers
#print axioms Erdos249257.ExternalVerification68AdjacentUnitCarryWindow.adjacentUnitCarryWindowDen_eq_twoStep_den
#print axioms Erdos249257.ExternalVerification68AdjacentUnitCarryWindow.adjacentUnitCarryWindowOffset_eq_twoStep_factorization
