import Solutions.ExternalVerification249PaperStatementsBE

#print axioms Erdos249257.ExternalVerification249PaperStatementsBE.divisorChannels_sum_eq
#print axioms Erdos249257.ExternalVerification249PaperStatementsBE.foreignComplementBound_paper
#print axioms Erdos249257.ExternalVerification249PaperStatementsBE.projectedForeignDefect_paper
#print axioms Erdos249257.ExternalVerification249PaperStatementsBE.residueKernel_increment_of_dvd
#print axioms Erdos249257.ExternalVerification249PaperStatementsBE.residueOffset_of_dvd
#print axioms Erdos249257.ExternalVerification249PaperStatementsBE.transportResidueKernel_eq_mobiusTermKernel
