import Solutions.PalomarCorpus.E257_28

#print axioms PalomarCorpus.E257.PaperStatementsAA.sub_two_le_two_pow_sub_four
#print axioms PalomarCorpus.E257.PaperStatementsAD.exists_boolean_word_of_lt_two_pow
#print axioms PalomarCorpus.E257.PaperStatementsAD.localMersenneQuotient_eq_two_pow_sub_of_half_lt
#print axioms PalomarCorpus.E257.PaperStatementsAR.exactLocalMersenneHalfRow_two_mul_sub_two_of_skippedCoreSharpCapacity
#print axioms PalomarCorpus.E257.PaperStatementsAR.exists_exactRowStrictUpperFill_of_skippedCoreSharpCapacity
#print axioms PalomarCorpus.E257.PaperStatementsAR.paper_exact_row_from_skipped_prefix
#print axioms PalomarCorpus.E257.PaperStatementsAR.precriticalCrossingTax_of_futureThreshold
#print axioms PalomarCorpus.E257.PaperStatementsBE.paper_critical_dyadic_band_index_eq_top_of_le_two
#print axioms PalomarCorpus.E257.PaperStatementsBE.paper_critical_dyadic_band_index_unique
#print axioms PalomarCorpus.E257.PaperStatementsBE.paper_critical_dyadic_boundary_is_smallest
#print axioms PalomarCorpus.E257.PaperStatementsBE.paper_dyadic_band_escape_iff_single_test
#print axioms PalomarCorpus.E257.PaperStatementsF.halfGreedySkippedCriticalQuotientSupply_of_precriticalSuffix
#print axioms PalomarCorpus.E257.PaperStatementsF.halfGreedySkippedPrecriticalSuffixSupply_iff_preTake
#print axioms PalomarCorpus.E257.PaperStatementsF.halfGreedy_precriticalSuffix_lt_of_future_skip_after_takenBlock
#print axioms PalomarCorpus.E257.PaperStatementsF.halfGreedy_precriticalSuffix_lt_of_next_skip
