import Solutions.ExternalVerification249PaperStructuresN

#print axioms Erdos249257.ExternalVerification249PaperStructuresN.certifiedKill_diagonal_t64
#print axioms Erdos249257.ExternalVerification249PaperStructuresN.certifiedKill_diagonal_t64_paper
#print axioms Erdos249257.ExternalVerification249PaperStructuresN.shortWindowSupply_single_witness_six_ninetyThree
#print axioms Erdos249257.ExternalVerification249PaperStructuresN.shortWindowSupply_witness_eq_t64_certificate
