import Solutions.ExternalVerification243PaperStructuresU

#print axioms Erdos249257.ExternalVerification243PaperStructuresU.energySqrt_summable_iff
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.energy_criterion
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.energy_le_two_energySqrt
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.energy_summable_iff
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.exists_late_energy_window
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.oddPrimePower_supply
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.oddPrimePower_supply_nat
#print axioms Erdos249257.ExternalVerification243PaperStructuresU.unitRecordIncrement_criterion
