import Solutions.ExternalVerification243PaperStatementsL

#print axioms Erdos249257.ExternalVerification243PaperStatementsL.canonicalCorrection_pos_and_lt_three_div
#print axioms Erdos249257.ExternalVerification243PaperStatementsL.canonical_frontier
#print axioms Erdos249257.ExternalVerification243PaperStatementsL.canonical_growthDefect_identity
#print axioms Erdos249257.ExternalVerification243PaperStatementsL.canonical_tail_ratio_quantitative
#print axioms Erdos249257.ExternalVerification243PaperStatementsL.finite_negative_mass_paper
#print axioms Erdos249257.ExternalVerification243PaperStatementsL.original_coordinate_slow_growth_defect
#print axioms Erdos249257.ExternalVerification243PaperStatementsL.prefix_ratio_le_canonicalNumerator
