import Solutions.PalomarCorpus.E68_09

#print axioms PalomarCorpus.E68.MultiplicativeSuccessorRigidity.eventually_dvd_gapSuccessor_of_not_irrational
#print axioms PalomarCorpus.E68.MultiplicativeSuccessorRigidity.irrational_factorialGapSeries_of_cofinal_not_dvd_gapSuccessor
#print axioms PalomarCorpus.E68.MultiplicativeSuccessorRigidity.irrational_factorialGapSeries_of_cofinal_odd_gapSuccessor
#print axioms PalomarCorpus.E68.MultiplicativeSuccessorRigidity.not_eventually_odd_gapSuccessor_of_not_irrational
#print axioms PalomarCorpus.E68.PrimePole.factorialGapPrefixLCMNumerator_mod_prime
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.channelResidual_appendPrimeTranslator
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.exists_remote_factorialGrid_primeTranslator_reduction
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.primeTranslator_channelResidual_eq_one
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.primeTranslator_channel_at_prime
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.primeTranslator_channel_zero_of_lt_p
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.primeTranslator_channel_zero_of_p_lt
#print axioms PalomarCorpus.E68.PrimeUnitTranslator.primeTranslator_moment_zero
