import Solutions.PalomarCorpus.E257b

#print axioms PalomarCorpus.E257.PaperStatementsB.greedy_survives_of_mem_mersenneAchievementSet
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_secondChannelSeparation
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_secondChannelSeparationRat_from_seven
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_skipped_dyadicCap
#print axioms PalomarCorpus.E257.PaperStatementsB.half_mem_mersenneAchievementSet_of_skipped_twoChannelCap
#print axioms PalomarCorpus.E257.PaperStatementsB.mem_mersenneAchievementSet_iff_greedy_survival
#print axioms PalomarCorpus.E257.PaperStatementsB.mem_mersenneAchievementSet_of_greedySkippedSupport_infinite
#print axioms PalomarCorpus.E257.PaperStatementsB.mem_mersenneAchievementSet_of_greedy_survival
