import Solutions.PalomarCorpus.E249ax

#print axioms PalomarCorpus.E249.PaperStatementsAX.finite_grid_nonintegral_pair
#print axioms PalomarCorpus.E249.PaperStatementsAX.joint35ConeWindow_eq
#print axioms PalomarCorpus.E249.PaperStatementsAX.joint35_nonintegral_of_separated_window
#print axioms PalomarCorpus.E249.PaperStatementsAX.joint35_truncation_error
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperGridNumerator_eq
#print axioms PalomarCorpus.E249.PaperStatementsAX.paperTeChain_item_one_unfolded
#print axioms PalomarCorpus.E249.PaperStatementsAX.specified_euler_tail_period
#print axioms PalomarCorpus.E249.PaperStatementsAX.sum_sq_dist_from_phase_one
#print axioms PalomarCorpus.E249.PaperStatementsAX.tailDifference_eq_coefficient_mul_series
#print axioms PalomarCorpus.E249.PaperStatementsAX.tailDifference_sub_rationalApproximation
#print axioms PalomarCorpus.E249.PaperStatementsAX.teChain_item_five_unfolded
#print axioms PalomarCorpus.E249.PaperStatementsAX.teChain_item_four_unfolded
#print axioms PalomarCorpus.E249.PaperStatementsAX.teChain_item_three_unfolded
#print axioms PalomarCorpus.E249.PaperStatementsAX.teChain_item_two_unfolded
#print axioms PalomarCorpus.E249.PaperStatementsAX.totientTail_enclosure
