import Solutions.PalomarCorpus.E1041_07

#print axioms PalomarCorpus.E1041.CriticalGeometry.allStraightCubic_every_pair_midpoint_escapes
#print axioms PalomarCorpus.E1041.CriticalGeometry.allStraightCubic_roots
#print axioms PalomarCorpus.E1041.CriticalGeometry.allStraightCubic_roots_in_unitDisk
#print axioms PalomarCorpus.E1041.CriticalGeometry.criticalDiskInverseBalance_twoRootProximity
#print axioms PalomarCorpus.E1041.CriticalGeometry.criticalDiskInverseBalance_twoRootProximity_strict
#print axioms PalomarCorpus.E1041.CriticalGeometry.criticalGeometricMean_twoRootProximity
#print axioms PalomarCorpus.E1041.CriticalGeometry.nearestSpoke_reciprocal_balance
#print axioms PalomarCorpus.E1041.CriticalGeometry.nearestSpoke_unique_nearest_normSq
#print axioms PalomarCorpus.E1041.CriticalGeometry.nearestSpoke_unique_nearest_spoke_escapes
#print axioms PalomarCorpus.E1041.CyclicTrinomialFiber.cyclicTrinomial_two_short_fiber_displacements
#print axioms PalomarCorpus.E1041.CyclicTrinomialFiber.trinomialRoot_spoke_factorization
#print axioms PalomarCorpus.E1041.CyclicTrinomialFiber.trinomialRoot_spoke_norm_le_constant
#print axioms PalomarCorpus.E1041.CyclicTrinomialFiber.trinomialRoot_spoke_norm_lt_one
#print axioms PalomarCorpus.E1041.CyclicTrinomialFiber.trinomialRoot_spoke_norm_lt_one_of_norm_lt_one
#print axioms PalomarCorpus.E1041.DegreeSevenCounterexample.degreeSevenCounterexample
#print axioms PalomarCorpus.E1041.FirstMergeCriticalValueSeparation.firstMerge_exact_convenient_thresholds
#print axioms PalomarCorpus.E1041.FirstMergeCriticalValueSeparation.firstMerge_length_lt_two_of_squared_bound
#print axioms PalomarCorpus.E1041.QuarticQuotientFiber.rootLift_axis_integral
#print axioms PalomarCorpus.E1041.QuarticQuotientFiber.rootLift_endpoint_budget_lt_two
#print axioms PalomarCorpus.E1041.QuarticQuotientFiber.rootLift_kernel_le_axis
#print axioms PalomarCorpus.E1041.QuarticQuotientFiber.rootLift_length_lt_two_of_le_endpoint_budget
