import Solutions.PalomarCorpus.E243_10

#print axioms PalomarCorpus.E243.BoundedNegativePartRigidity.boundedNegativePart_completeRigidity
#print axioms PalomarCorpus.E243.BoundedRiseReducedTail.no_boundedRise_of_tailAvoidance
#print axioms PalomarCorpus.E243.BoundedRiseReducedTail.no_boundedRise_reducedTail
#print axioms PalomarCorpus.E243.BoundedRiseReducedTail.no_eventuallyBoundedRise_reducedTail
#print axioms PalomarCorpus.E243.PeriodicNegativeOrbit.no_eventuallyPeriodicNegative_orbit
#print axioms PalomarCorpus.E243.PeriodicNegativeOrbit.no_periodicNegative_orbit
#print axioms PalomarCorpus.E243.PeriodicNegativeOrbit.no_phasePrimitivePeriodicNegative_orbit
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.centeredZero_forces_unit
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.exists_oddMultiple_trapHeight
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.numerator_bounded_of_oddPrimePower
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.odd_record_cut
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.primitive_valuation_no_drop
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.protectedPrimePower_persists
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.recordRiseTwo_sylvesterNext_eventually
#print axioms PalomarCorpus.E243.PrimitiveRecordRigidity.sylvesterStep_of_centeredZero_pair
#print axioms PalomarCorpus.E243.ProtectedEpochEnergy.protected_epoch_energy_integer
