import Solutions.PalomarCorpus.E257_27

#print axioms PalomarCorpus.E257.PaperStatementsAL.finite_boolSupport_ne_half
#print axioms PalomarCorpus.E257.PaperStatementsAR.abs_exactLocalMersenneRowValue_sub_half_le
#print axioms PalomarCorpus.E257.PaperStatementsAR.cofinalExactLocalMersenneHalfRows_of_criticalQuotientSupply
#print axioms PalomarCorpus.E257.PaperStatementsAR.half_mem_mersenneAchievementSet_of_cofinalExactLocalRows
#print axioms PalomarCorpus.E257.PaperStatementsAR.half_mem_mersenneAchievementSet_of_criticalQuotientSupply
#print axioms PalomarCorpus.E257.PaperStatementsD.cofinalPositiveHalfGreedySkips_iff_half_mem
#print axioms PalomarCorpus.E257.PaperStatementsD.half_mem_mersenneAchievementSet_of_positiveHalfGreedySkips
#print axioms PalomarCorpus.E257.PaperStatementsF.cofinalExactLocalMersenneHalfRows_of_positiveHalfGreedySkips
#print axioms PalomarCorpus.E257.PaperStatementsF.exactLocalMersenneHalfRow_of_positiveHalfGreedySkip
#print axioms PalomarCorpus.E257.PaperStatementsF.skippedCoreCriticalQuotientSupply_iff_halfGreedySkipped
#print axioms PalomarCorpus.E257.PaperStructuresAW.paper_compatible_first_condition_gives_nonneg
#print axioms PalomarCorpus.E257.PaperStructuresBA.exists_laterProtectedExactLocalMersenneRow
#print axioms PalomarCorpus.E257.PaperStructuresT.paper_compatible_rows_agree_with_limit
#print axioms PalomarCorpus.E257.PaperStructuresW.paper_compatible_bit_stable
