import Solutions.PalomarCorpus.E257_27

#print axioms PalomarCorpus.E257.PaperStatementsAL.finite_boolSupport_ne_half
#print axioms PalomarCorpus.E257.PaperStatementsAR.abs_exactLocalMersenneRowValue_sub_half_le
#print axioms PalomarCorpus.E257.PaperStatementsAR.half_mem_mersenneAchievementSet_of_cofinalExactLocalRows
#print axioms PalomarCorpus.E257.PaperStatementsD.cofinalPositiveHalfGreedySkips_iff_half_mem
#print axioms PalomarCorpus.E257.PaperStatementsD.half_mem_mersenneAchievementSet_of_positiveHalfGreedySkips
#print axioms PalomarCorpus.E257.PaperStatementsF.cofinalExactLocalMersenneHalfRows_of_positiveHalfGreedySkips
#print axioms PalomarCorpus.E257.PaperStatementsF.exactLocalMersenneHalfRow_of_positiveHalfGreedySkip
#print axioms PalomarCorpus.E257.PaperStructuresAW.paper_compatible_first_condition_gives_nonneg
#print axioms PalomarCorpus.E257.PaperStructuresCJ.above_newSum_le_capacity_iff
#print axioms PalomarCorpus.E257.PaperStructuresCJ.below_newSum_le_capacity
#print axioms PalomarCorpus.E257.PaperStructuresCJ.nextRemainder_trichotomy
#print axioms PalomarCorpus.E257.PaperStructuresCJ.prefixChoice_maximal
#print axioms PalomarCorpus.E257.PaperStructuresCJ.prefixRemainder_eq_capacity_sub_choice
#print axioms PalomarCorpus.E257.PaperStructuresT.paper_compatible_rows_agree_with_limit
