import Solutions.ExternalVerification243PaperStatementsQ

#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.canonicalError_div_overlapDebt
#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.digitProductScale_eq_canonicalDenominator
#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.erdosStrausQuantity_ne_productDefect_ne_lcmShift
#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.erdosStrausQuantity_sign
#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.erdosStraus_lcm_includes_digit_not_denominator
#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.overlapDebt_dvd_gcd
#print axioms Erdos249257.ExternalVerification243PaperStatementsQ.overlapDebt_mul_lcmClearedNumerator
