import Solutions.ExternalVerification257PaperStatementsL

#print axioms Erdos249257.ExternalVerification257PaperStatementsL.paper_cofiniteRightTail_ne_zero_centeredEndpoint
#print axioms Erdos249257.ExternalVerification257PaperStatementsL.paper_relaxed_constant_six_every_depth
#print axioms Erdos249257.ExternalVerification257PaperStatementsL.paper_square_depth_terminal_bound
#print axioms Erdos249257.ExternalVerification257PaperStatementsL.paper_terminal_strip_forces_half_membership
#print axioms Erdos249257.ExternalVerification257PaperStatementsL.square_depth_witness
