import Solutions.PalomarCorpus.E257u

#print axioms PalomarCorpus.E257.PaperStructuresU.IsStraddlePrefix.half_step_forced
#print axioms PalomarCorpus.E257.PaperStructuresU.isStraddlePrefix_step_trichotomy
