import Solutions.PalomarCorpus.E257al

#print axioms PalomarCorpus.E257.PaperStatementsAL.finite_boolSupport_ne_half
#print axioms PalomarCorpus.E257.PaperStatementsAL.half_of_cofinal_absolute_carry
#print axioms PalomarCorpus.E257.PaperStatementsAL.infinite_support_half_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms PalomarCorpus.E257.PaperStatementsAL.integerHalfCarry_eq_scaled_residual_add_tail
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_coeffTail_le_index_add_two
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_cofiniteRightTail_ne_zero_centeredEndpoint
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_relaxed_constant_six_every_depth
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_square_depth_terminal_bound
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_terminal_strip_forces_half_membership
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_zero_run_le_eps_logb
#print axioms PalomarCorpus.E257.PaperStatementsAL.paper_zero_run_le_of_mem
#print axioms PalomarCorpus.E257.PaperStatementsAL.square_depth_witness
#print axioms PalomarCorpus.E257.PaperStatementsAL.supportCoeff_boundaryPair_unitDrop_at_double
#print axioms PalomarCorpus.E257.PaperStatementsAL.supportCoeff_extend_true_eq_false_add_one_at_double
#print axioms PalomarCorpus.E257.PaperStatementsAL.supportCoeff_insert_divisor
