import Solutions.ExternalVerification257PaperStructuresCF

#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.paper_final_middle_cell_remaining_negative_values
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.paper_finite_band_check_thirteen_to_thirty
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresCF.wordPulse_le
