import Solutions.PalomarCorpus.E269c

#print axioms PalomarCorpus.E269.PaperStatementsC.actual_sharp_tail_bound
#print axioms PalomarCorpus.E269.PaperStatementsC.actual_tail_rank_bound
#print axioms PalomarCorpus.E269.PaperStatementsC.allReducedTailsNonintegral_iff
#print axioms PalomarCorpus.E269.PaperStatementsC.dyadic_alphabet_whole
#print axioms PalomarCorpus.E269.PaperStatementsC.longPaperCap_le_three_squareR11
#print axioms PalomarCorpus.E269.PaperStatementsC.long_actual_orbit
#print axioms PalomarCorpus.E269.PaperStatementsC.long_all_scale_lattice_exact
#print axioms PalomarCorpus.E269.PaperStatementsC.long_fixed_split_bridgeR11
#print axioms PalomarCorpus.E269.PaperStatementsC.paper_finite_endpoint_obstruction
#print axioms PalomarCorpus.E269.PaperStatementsC.paper_pinning_and_eight_scale_rigidity
#print axioms PalomarCorpus.E269.PaperStatementsC.scaled_integer_or_cofinal_separation
#print axioms PalomarCorpus.E269.PaperStatementsC.short_actual_orbit
#print axioms PalomarCorpus.E269.PaperStatementsC.short_fixed_split_bridge
