import Solutions.ExternalVerification1049PublishedHeightRegions
#print axioms Erdos249257.ExternalVerification1049PublishedHeightRegions.threeHalves_zudilin_power_obstruction
#print axioms Erdos249257.ExternalVerification1049PublishedHeightRegions.eightyOneTwoHundredths_lt_threeHalves_log_ratio
#print axioms Erdos249257.ExternalVerification1049PublishedHeightRegions.threeHalves_outside_zudilinHeightRegion
#print axioms Erdos249257.ExternalVerification1049PublishedHeightRegions.threeHalves_outside_bundschuhVaananenHeightRegion
