import Solutions.ExternalVerification257PaperStatementsAT

#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.binaryCoeffTail_supportCoeff_coe_finset_le_card
#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.mobiusCenteredHalfCarry_add_two
#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.mobiusCenteredHalfCarry_nonneg_of_supportSeries_lt_half
#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.paper_exact_row_integerHalfCarry_eq_one
#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.paper_integerHalfCarry_eq_two_pow_sub_localPrefixQuotient
#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.paper_mobiusCenteredHalfCarry_add_two
#print axioms Erdos249257.ExternalVerification257PaperStatementsAT.paper_terminal_strip_witness_six
