import Solutions.ExternalVerification257PaperStructuresBK

#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.exists_seamWord_minimal_above
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.half_mem_mersenneAchievementSet_of_resetSqrtEscape
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.integerGreedyBits_length
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.paper_seam_escape_forces_remainder_band
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.paper_seam_escape_implies_full_shell_nonnegative
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamAboveWord_minimal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamAboveWord_strict
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamAdjacentCut_below_admissible
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamAdjacentCut_below_maximal
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamPerturbedFamily_gap_pos
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamPerturbedFamily_oldSum_injective
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamPerturbedFamily_pulseCap_lt_three_gap
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamPerturbedFamily_separated
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.seamWeights_length_eq
#print axioms Erdos249257.ExternalVerification257PaperStructuresBK.wordPulse_le
